/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/agentflow-outlined` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/reltio/agentflow-outlined";
 * Optional component: import { ReltioAgentflowOutlined } from "@reltio/design/icons/reltio/agentflow-outlined";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { registerReltioIcon } from "../registerReltioIcon";

const ICON_NAME = registerReltioIcon("agentflow-outlined", {
	viewBox: "0 0 16 16",
	customTemplateAsString:
		'<g fill="none"><path d="M14.1187 0V4.79909H9.66503C7.98977 4.79935 6.62715 6.13488 6.58661 7.79766C7.35512 7.51648 8.18534 7.36336 9.05073 7.36336H13.7402V12.0586H10.0257C8.12573 12.0587 6.58563 13.5965 6.58561 15.4934V15.9999H5.97033V16.0039H1.88129V7.15759C1.88132 3.20441 5.09146 3.87955e-05 9.05073 0H14.1187ZM2.89587 14.9909H4.95575V14.9869H5.60076C5.85264 12.7691 7.73703 11.0457 10.0257 11.0455H12.7256V8.3764H9.05073C8.06332 8.37641 7.13161 8.60936 6.30522 9.02143L5.57103 9.38747V7.87384L5.57599 7.66312C5.68586 5.50349 7.47484 3.78634 9.66503 3.78605H13.1041V1.01304H9.05073C5.65162 1.01308 2.8959 3.76406 2.89587 7.15759V14.9909Z" fill="currentColor"/></g>',
});

export type ReltioAgentflowOutlinedProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/agentflow-outlined" />` after this module is evaluated. */
export function ReltioAgentflowOutlined(props: ReltioAgentflowOutlinedProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`reltio/agentflow-outlined`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
