/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/analyze-match-rules` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/reltio/analyze-match-rules";
 * Optional component: import { ReltioAnalyzeMatchRules } from "@reltio/design/icons/reltio/analyze-match-rules";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { registerReltioIcon } from "../registerReltioIcon";

const ICON_NAME = registerReltioIcon("analyze-match-rules", {
	viewBox: "0 0 21 21",
	customTemplateAsString:
		'<g fill="none"><path d="M14.5 10.3467C15.6538 10.3467 16.6347 10.75 17.4424 11.5576C18.25 12.3653 18.6533 13.3462 18.6533 14.5C18.6533 14.9333 18.591 15.351 18.4648 15.7529C18.3385 16.1548 18.1514 16.5242 17.9053 16.8613L20.6445 19.5996L19.5996 20.6445L16.8613 17.9053C16.5242 18.1514 16.1548 18.3385 15.7529 18.4648C15.351 18.591 14.9333 18.6533 14.5 18.6533C13.3462 18.6533 12.3653 18.25 11.5576 17.4424C10.75 16.6347 10.3467 15.6538 10.3467 14.5C10.3467 13.3462 10.75 12.3653 11.5576 11.5576C12.3653 10.75 13.3462 10.3467 14.5 10.3467ZM14.5 11.8467C13.7552 11.8467 13.1264 12.1021 12.6143 12.6143C12.1021 13.1264 11.8457 13.7552 11.8457 14.5C11.8457 15.2448 12.1021 15.8736 12.6143 16.3857C13.1264 16.8979 13.7552 17.1533 14.5 17.1533C15.2448 17.1533 15.8736 16.8979 16.3857 16.3857C16.8979 15.8736 17.1533 15.2448 17.1533 14.5C17.1533 13.7552 16.8979 13.1264 16.3857 12.6143C15.8736 12.1021 15.2448 11.8467 14.5 11.8467ZM5 16.5H1.5V9.59668H5V16.5ZM10.75 9.19238C9.0868 10.3696 8 12.3073 8 14.5C8 15.1979 8.11086 15.8699 8.31445 16.5H7.25V1.5H10.75V9.19238ZM16.5 8.31445C15.8699 8.11086 15.1979 8 14.5 8C13.9836 8 13.4816 8.06198 13 8.17578V6.4043H16.5V8.31445Z" fill="currentColor"/></g>',
});

export type ReltioAnalyzeMatchRulesProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/analyze-match-rules" />` after this module is evaluated. */
export function ReltioAnalyzeMatchRules(props: ReltioAnalyzeMatchRulesProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`reltio/analyze-match-rules`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
