/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/area` icon. Tree-shakable single import:
 * import "@reltio/design/icons/reltio/area";
 * Optional component: import { ReltioArea } from "@reltio/design/icons/reltio/area";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { unsafeRegisterIcon } from "@ui5/webcomponents-base/dist/asset-registries/Icons.js";

unsafeRegisterIcon("area", {
	collection: "reltio",
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path d="M13.5299 4.47168L12.4694 5.53223L10.7496 3.8125V12.0586L17.818 15.9854L17.1803 13.6025L18.6285 13.2139L19.9215 18.0371L15.0983 19.3291L14.7106 17.8799L17.024 17.2598L9.99963 13.3584L2.97913 17.2568L5.28674 17.876L4.89905 19.3242L0.0758057 18.0322L1.36877 13.21L2.81702 13.5986L2.17639 15.9873L9.24963 12.0586V3.8125L7.52991 5.53223L6.46936 4.47168L9.99963 0.941406L13.5299 4.47168Z" fill="currentColor"/></g>',
});

const ICON_NAME = "reltio/area";

export type ReltioAreaProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/area" />` after this module is evaluated. */
export function ReltioArea(props: ReltioAreaProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
