/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/bar-chart` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/reltio/bar-chart";
 * Optional component: import { ReltioBarChart } from "@reltio/design/icons/reltio/bar-chart";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { registerReltioIcon } from "../registerReltioIcon";

const ICON_NAME = registerReltioIcon("bar-chart", {
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path d="M14 17.5V11.5963H17.5V17.5H14ZM8.25 17.5V2.5H11.75V17.5H8.25ZM2.5 17.5V7.404H6V17.5H2.5Z" fill="currentColor"/></g>',
});

export type ReltioBarChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/bar-chart" />` after this module is evaluated. */
export function ReltioBarChart(props: ReltioBarChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`reltio/bar-chart`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
