/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/chart` icon. Tree-shakable single import:
 * import "@reltio/design/icons/reltio/chart";
 * Optional component: import { ReltioChart } from "@reltio/design/icons/reltio/chart";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { unsafeRegisterIcon } from "@ui5/webcomponents-base/dist/asset-registries/Icons.js";

unsafeRegisterIcon("chart", {
	collection: "reltio",
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><mask id="chart-mask0_51_6242" style="mask-type:alpha" maskUnits="userSpaceOnUse" x="-2" y="-2" width="24" height="24"> <rect x="-2" y="-2" width="24" height="24" fill="#D9D9D9"/> </mask> <g mask="url(#chart-mask0_51_6242)"> <path d="M17.7496 16.6348H2.24963V15.1348H17.7496V16.6348ZM16.7565 5.62988L17.7106 4.67578V6.79688L16.7565 7.75098L14.6168 5.61133L7.81116 12.417L4.43225 9.03809L2.19592 11.1045V9.0625L4.47327 6.95801L7.81116 10.2959L14.6168 3.49023L16.7565 5.62988Z" fill="currentColor"/> </g></g>',
});

const ICON_NAME = "reltio/chart";

export type ReltioChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/chart" />` after this module is evaluated. */
export function ReltioChart(props: ReltioChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
