/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/chemical-substance` icon. Tree-shakable single import:
 * import "@reltio/design/icons/reltio/chemical-substance";
 * Optional component: import { ReltioChemicalSubstance } from "@reltio/design/icons/reltio/chemical-substance";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { unsafeRegisterIcon } from "@ui5/webcomponents-base/dist/asset-registries/Icons.js";

unsafeRegisterIcon("chemical-substance", {
	collection: "reltio",
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path d="M2.99994 18.5C2.36211 18.5 1.90878 18.2154 1.63994 17.6462C1.37094 17.0769 1.43586 16.5474 1.83469 16.0577L7.49995 9.173V3H6.30769C6.09519 3 5.91703 2.92808 5.77319 2.78425C5.62953 2.64042 5.55769 2.46225 5.55769 2.24975C5.55769 2.03708 5.62953 1.859 5.77319 1.7155C5.91703 1.57183 6.09519 1.5 6.30769 1.5H13.6922C13.9047 1.5 14.0829 1.57192 14.2267 1.71575C14.3704 1.85958 14.4422 2.03775 14.4422 2.25025C14.4422 2.46292 14.3704 2.641 14.2267 2.7845C14.0829 2.92817 13.9047 3 13.6922 3H12.4999V9.173L18.1652 16.0577C18.564 16.5474 18.6289 17.0769 18.3599 17.6462C18.0911 18.2154 17.6378 18.5 16.9999 18.5H2.99994ZM4.99994 16H14.9999L11.5999 12H8.39995L4.99994 16ZM2.99994 17H16.9999L10.9999 9.7V3H8.99995V9.7L2.99994 17Z" fill="currentColor"/></g>',
});

const ICON_NAME = "reltio/chemical-substance";

export type ReltioChemicalSubstanceProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/chemical-substance" />` after this module is evaluated. */
export function ReltioChemicalSubstance(props: ReltioChemicalSubstanceProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
