/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/compare` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/reltio/compare";
 * Optional component: import { ReltioCompare } from "@reltio/design/icons/reltio/compare";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { registerReltioIcon } from "../registerReltioIcon";

const ICON_NAME = registerReltioIcon("compare", {
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path d="M9.75 20H8.25V18H3C2.44772 18 2 17.5523 2 17V3C2 2.44772 2.44772 2 3 2H8.25V0H9.75V20ZM17 2C17.5523 2 18 2.44772 18 3V17C18 17.5523 17.5523 18 17 18H11.75V16.5H16.5V3.5H11.75V2H17ZM8.25 6.40234C6.91793 7.05151 6 8.41848 6 10C6 11.5814 6.91814 12.9474 8.25 13.5967V6.40234ZM11.75 6.40332C13.0818 7.05253 13.9999 8.41873 14 10C13.9999 11.5812 13.0817 12.9475 11.75 13.5967V6.40332Z" fill="currentColor"/></g>',
});

export type ReltioCompareProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/compare" />` after this module is evaluated. */
export function ReltioCompare(props: ReltioCompareProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`reltio/compare`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
