/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/crosswalk` icon. Tree-shakable single import:
 * import "@reltio/design/icons/reltio/crosswalk";
 * Optional component: import { ReltioCrosswalk } from "@reltio/design/icons/reltio/crosswalk";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { unsafeRegisterIcon } from "@ui5/webcomponents-base/dist/asset-registries/Icons.js";

unsafeRegisterIcon("crosswalk", {
	collection: "reltio",
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path d="M18 1.5C19.1046 1.5 20 2.39543 20 3.5V16.5C20 17.6046 19.1046 18.5 18 18.5H2C0.895431 18.5 0 17.6046 0 16.5V3.5C0 2.39543 0.895431 1.5 2 1.5H18ZM2 3C1.72386 3 1.5 3.22386 1.5 3.5V16.5C1.5 16.7761 1.72386 17 2 17H18C18.2761 17 18.5 16.7761 18.5 16.5V3.5C18.5 3.22386 18.2761 3 18 3H2ZM15 15.25H5V13.75H15V15.25ZM15 12.25H5V10.75H15V12.25ZM15 9.25H5V7.75H15V9.25ZM15 6.25H5V4.75H15V6.25Z" fill="currentColor"/></g>',
});

const ICON_NAME = "reltio/crosswalk";

export type ReltioCrosswalkProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/crosswalk" />` after this module is evaluated. */
export function ReltioCrosswalk(props: ReltioCrosswalkProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
