/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/data-cloud-warehouse-pipeline` icon. Tree-shakable single import:
 * import "@reltio/design/icons/reltio/data-cloud-warehouse-pipeline";
 * Optional component: import { ReltioDataCloudWarehousePipeline } from "@reltio/design/icons/reltio/data-cloud-warehouse-pipeline";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { unsafeRegisterIcon } from "@ui5/webcomponents-base/dist/asset-registries/Icons.js";

unsafeRegisterIcon("data-cloud-warehouse-pipeline", {
	collection: "reltio",
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path d="M10.75 15.5V18.5H15.75V20H4.25V18.5H9.25V15.5H10.75ZM16.7002 7.67285C17.6942 7.67296 18.4999 8.4787 18.5 9.47266V12.5449C18.4997 13.5387 17.6941 14.3456 16.7002 14.3457H3.2998C2.30594 14.3456 1.50026 13.5387 1.5 12.5449V9.47266C1.50011 8.4787 2.30585 7.67296 3.2998 7.67285H16.7002ZM3.2998 9.17285C3.13427 9.17296 3.00011 9.30713 3 9.47266V12.5449C3.00026 12.7103 3.13437 12.8456 3.2998 12.8457H16.7002C16.8656 12.8456 16.9997 12.7103 17 12.5449V9.47266C16.9999 9.30713 16.8657 9.17296 16.7002 9.17285H3.2998ZM6.19238 11.8994H4.38477V10.0918H6.19238V11.8994ZM16.7002 0C17.6942 0.000105643 18.4999 0.805847 18.5 1.7998V4.87207C18.5 5.86612 17.6942 6.67275 16.7002 6.67285H3.2998C2.30578 6.67275 1.5 5.86612 1.5 4.87207V1.7998C1.50011 0.805847 2.30585 0.000105514 3.2998 0H16.7002ZM3.2998 1.5C3.13427 1.50011 3.00011 1.63427 3 1.7998V4.87207C3 5.03769 3.13421 5.17275 3.2998 5.17285H16.7002C16.8658 5.17275 17 5.03769 17 4.87207V1.7998C16.9999 1.63427 16.8657 1.50011 16.7002 1.5H3.2998ZM6.19238 4.22656H4.38477V2.41895H6.19238V4.22656Z" fill="currentColor"/></g>',
});

const ICON_NAME = "reltio/data-cloud-warehouse-pipeline";

export type ReltioDataCloudWarehousePipelineProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/data-cloud-warehouse-pipeline" />` after this module is evaluated. */
export function ReltioDataCloudWarehousePipeline(
	props: ReltioDataCloudWarehousePipelineProps,
) {
	return <Icon name={ICON_NAME} {...props} />;
}
