/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/entity-type` icon. Tree-shakable single import:
 * import "@reltio/design/icons/reltio/entity-type";
 * Optional component: import { ReltioEntityType } from "@reltio/design/icons/reltio/entity-type";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { unsafeRegisterIcon } from "@ui5/webcomponents-base/dist/asset-registries/Icons.js";

unsafeRegisterIcon("entity-type", {
	collection: "reltio",
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path d="M11.5 19.5H1V9.5H11.5V19.5ZM19 19.5H13V9.5H19V19.5ZM2.5 18H10V11H2.5V18ZM14.5 18H17.5V11H14.5V18ZM19 8H1V1H19V8ZM2.5 6.5H17.5V2.5H2.5V6.5ZM4.46973 3.59473C4.71455 3.59473 4.92321 3.68119 5.0957 3.85352C5.26811 4.02599 5.35449 4.23473 5.35449 4.47949C5.35443 4.72421 5.26814 4.93303 5.0957 5.10547C4.92323 5.27788 4.71449 5.36425 4.46973 5.36426C4.22496 5.36426 4.01622 5.27787 3.84375 5.10547C3.67148 4.93303 3.58502 4.72421 3.58496 4.47949C3.58496 4.23472 3.6715 4.02599 3.84375 3.85352C4.01625 3.68118 4.22489 3.59473 4.46973 3.59473Z" fill="currentColor"/></g>',
});

const ICON_NAME = "reltio/entity-type";

export type ReltioEntityTypeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/entity-type" />` after this module is evaluated. */
export function ReltioEntityType(props: ReltioEntityTypeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
