/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/export-configuration` icon. Tree-shakable single import:
 * import "@reltio/design/icons/reltio/export-configuration";
 * Optional component: import { ReltioExportConfiguration } from "@reltio/design/icons/reltio/export-configuration";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { unsafeRegisterIcon } from "@ui5/webcomponents-base/dist/asset-registries/Icons.js";

unsafeRegisterIcon("export-configuration", {
	collection: "reltio",
	viewBox: "0 0 22 20",
	customTemplateAsString:
		'<g fill="none"><path d="M3.30775 18.5C2.80258 18.5 2.375 18.325 2.025 17.975C1.675 17.625 1.5 17.1974 1.5 16.6923V3.30775C1.5 2.80258 1.675 2.375 2.025 2.025C2.375 1.675 2.80258 1.5 3.30775 1.5H16.6923C17.1974 1.5 17.625 1.675 17.975 2.025C18.325 2.375 18.5 2.80258 18.5 3.30775V5H3V16.6923C3 16.7692 3.03208 16.8398 3.09625 16.9038C3.16025 16.9679 3.23075 17 3.30775 17H16.6923C16.7692 17 16.8398 16.9679 16.9038 16.9038C16.9679 16.8398 17 16.7692 17 16.6923V16H18.5V16.6923C18.5 17.1974 18.325 17.625 17.975 17.975C17.625 18.325 17.1974 18.5 16.6923 18.5H3.30775Z" fill="currentColor"/> <path d="M16.773 13.2538L17.827 14.3075L21.4807 10.6538L17.827 7L16.773 8.05375L18.623 9.90375H11.077V11.4038H18.623L16.773 13.2538Z" fill="currentColor"/></g>',
});

const ICON_NAME = "reltio/export-configuration";

export type ReltioExportConfigurationProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/export-configuration" />` after this module is evaluated. */
export function ReltioExportConfiguration(
	props: ReltioExportConfigurationProps,
) {
	return <Icon name={ICON_NAME} {...props} />;
}
