/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/export` icon. Tree-shakable single import:
 * import "@reltio/design/icons/reltio/export";
 * Optional component: import { ReltioExport } from "@reltio/design/icons/reltio/export";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { unsafeRegisterIcon } from "@ui5/webcomponents-base/dist/asset-registries/Icons.js";

unsafeRegisterIcon("export", {
	collection: "reltio",
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path d="M4.5 15C5.05213 15.0002 5.5 15.4478 5.5 16V19C5.5 19.5522 5.05213 19.9998 4.5 20H1.5C0.947865 19.9998 0.5 19.5522 0.5 19V16C0.5 15.4478 0.947865 15.0002 1.5 15H4.5ZM11.5 15C12.0521 15.0002 12.5 15.4478 12.5 16V19C12.5 19.5522 12.0521 19.9998 11.5 20H8.5C7.94787 19.9998 7.5 19.5522 7.5 19V16C7.5 15.4478 7.94787 15.0002 8.5 15H11.5ZM18.5 15C19.0521 15.0002 19.5 15.4478 19.5 16V19C19.5 19.5522 19.0521 19.9998 18.5 20H15.5C14.9479 19.9998 14.5 19.5522 14.5 19V16C14.5 15.4478 14.9479 15.0002 15.5 15H18.5ZM2 18.5H4V16.5H2V18.5ZM9 18.5H11V16.5H9V18.5ZM16 18.5H18V16.5H16V18.5ZM19.5 12H17.75V14H16.25V12H10.75V14H9.25V12H3.75V14H2.25V12H0.5V10H19.5V12ZM13.5 0C14.0523 0 14.5 0.447715 14.5 1V6C14.5 6.55228 14.0523 7 13.5 7H10.75V8.5H9.25V7H6.5C5.94772 7 5.5 6.55228 5.5 6V1C5.5 0.447715 5.94772 0 6.5 0H13.5ZM7 5.5H13V1.5H7V5.5ZM8.96973 2.59473C9.21455 2.59473 9.42321 2.68119 9.5957 2.85352C9.76811 3.02599 9.85449 3.23473 9.85449 3.47949C9.85443 3.72421 9.76814 3.93303 9.5957 4.10547C9.42323 4.27788 9.21449 4.36425 8.96973 4.36426C8.72496 4.36426 8.51622 4.27787 8.34375 4.10547C8.17148 3.93303 8.08502 3.72421 8.08496 3.47949C8.08496 3.23472 8.1715 3.02599 8.34375 2.85352C8.51625 2.68118 8.72489 2.59473 8.96973 2.59473Z" fill="currentColor"/></g>',
});

const ICON_NAME = "reltio/export";

export type ReltioExportProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/export" />` after this module is evaluated. */
export function ReltioExport(props: ReltioExportProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
