/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/facet-attributes` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/reltio/facet-attributes";
 * Optional component: import { ReltioFacetAttributes } from "@reltio/design/icons/reltio/facet-attributes";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { registerReltioIcon } from "../registerReltioIcon";

const ICON_NAME = registerReltioIcon("facet-attributes", {
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path d="M11.25 7V1.5H18.5V7H11.25ZM1.5 10.5V1.5H8.75V10.5H1.5ZM11.25 18.5V9.5H18.5V18.5H11.25ZM1.5 18.5V13H8.75V18.5H1.5ZM3 9H7.25V3H3V9ZM12.75 17H17V11H12.75V17ZM12.75 5.5H17V3H12.75V5.5ZM3 17H7.25V14.5H3V17Z" fill="currentColor"/></g>',
});

export type ReltioFacetAttributesProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/facet-attributes" />` after this module is evaluated. */
export function ReltioFacetAttributes(props: ReltioFacetAttributesProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`reltio/facet-attributes`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
