/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/film` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/reltio/film";
 * Optional component: import { ReltioFilm } from "@reltio/design/icons/reltio/film";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { registerReltioIcon } from "../registerReltioIcon";

const ICON_NAME = registerReltioIcon("film", {
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M1 3V2H19V3H18.5V4.5H19V15.5H18.5V17H19V18H1V17H2V15.5H1V4.5H2V3H1ZM2.5 5.5V14.5H17.5V5.5H2.5ZM3.5 3H5V4.5H3.5V3ZM8 3H6.5V4.5H8V3ZM9.5 3H11V4.5H9.5V3ZM14 3H12.5V4.5H14V3ZM15.5 3H17V4.5H15.5V3ZM3.5 15.5H5V17H3.5V15.5ZM8 15.5H6.5V17H8V15.5ZM9.5 15.5H11V17H9.5V15.5ZM14 15.5H12.5V17H14V15.5ZM15.5 15.5H17V17H15.5V15.5Z" fill="currentColor"/></g>',
});

export type ReltioFilmProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/film" />` after this module is evaluated. */
export function ReltioFilm(props: ReltioFilmProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`reltio/film`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
