/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/generic` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/reltio/generic";
 * Optional component: import { ReltioGeneric } from "@reltio/design/icons/reltio/generic";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { registerReltioIcon } from "../registerReltioIcon";

const ICON_NAME = registerReltioIcon("generic", {
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path d="M10.75 18H9.25V16.5H10.75V18ZM15 15H5V5H15V15ZM6.5 13.5H13.5V6.5H6.5V13.5ZM3.5 10.75H2V9.25H3.5V10.75ZM18 10.75H16.5V9.25H18V10.75ZM10.75 3.5H9.25V2H10.75V3.5Z" fill="currentColor"/></g>',
});

export type ReltioGenericProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/generic" />` after this module is evaluated. */
export function ReltioGeneric(props: ReltioGenericProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`reltio/generic`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
