/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/hcos-facility` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/reltio/hcos-facility";
 * Optional component: import { ReltioHcosFacility } from "@reltio/design/icons/reltio/hcos-facility";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { registerReltioIcon } from "../registerReltioIcon";

const ICON_NAME = registerReltioIcon("hcos-facility", {
	viewBox: "0 0 20 22",
	customTemplateAsString:
		'<g fill="none"><path d="M0.365479 19.6925V3.4425L5.11548 0L9.86523 3.4425V6.1925H19.6345V19.6925H0.365479ZM1.86523 18.1925H4.36548V15.6925H1.86523V18.1925ZM1.86523 14.1925H4.36548V11.6925H1.86523V14.1925ZM1.86523 10.1925H4.36548V7.6925H1.86523V10.1925ZM1.86523 6.1925H4.36548V3.6925H1.86523V6.1925ZM5.86523 6.1925H8.36548V3.6925H5.86523V6.1925ZM5.86523 18.1925H18.1347V7.6925H5.86523V18.1925ZM12.0577 11.6925V10.1925H15.75V11.6925H12.0577ZM12.0577 15.6925V14.1925H15.75V15.6925H12.0577ZM8.36548 11.6925V10.1925H9.86523V11.6925H8.36548ZM8.36548 15.6925V14.1925H9.86523V15.6925H8.36548Z" fill="currentColor"/></g>',
});

export type ReltioHcosFacilityProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/hcos-facility" />` after this module is evaluated. */
export function ReltioHcosFacility(props: ReltioHcosFacilityProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`reltio/hcos-facility`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
