/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/homepage` icon. Tree-shakable single import:
 * import "@reltio/design/icons/reltio/homepage";
 * Optional component: import { ReltioHomepage } from "@reltio/design/icons/reltio/homepage";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { unsafeRegisterIcon } from "@ui5/webcomponents-base/dist/asset-registries/Icons.js";

unsafeRegisterIcon("homepage", {
	collection: "reltio",
	viewBox: "0 0 21 20",
	customTemplateAsString:
		'<g fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M0 9.41925L0.902 10.6152L3 9.03596V18.5002H9.34625V12.558H11.6538V18.5002H18V9.03023L20.1077 10.6152L21.0095 9.41925L17.1152 6.48475V2.5H14.673V4.6365L10.5 1.5L0 9.41925ZM7.84625 17.0002H4.5V8.00021L10.5 3.48096L16.5 8.00021V17.0002H13.1538V11.058H7.84625V17.0002Z" fill="currentColor"/></g>',
});

const ICON_NAME = "reltio/homepage";

export type ReltioHomepageProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/homepage" />` after this module is evaluated. */
export function ReltioHomepage(props: ReltioHomepageProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
