/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/idn-label` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/reltio/idn-label";
 * Optional component: import { ReltioIdnLabel } from "@reltio/design/icons/reltio/idn-label";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { registerReltioIcon } from "../registerReltioIcon";

const ICON_NAME = registerReltioIcon("idn-label", {
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path d="M15.7155 14.32L12.3195 5.80005H13.5915L16.9755 14.32H15.7155ZM12.0675 14.32V5.80005H13.4595V14.32H12.0675ZM16.0635 14.32V5.80005H17.4555V14.32H16.0635Z" fill="currentColor"/> <path d="M9.29691 11.992V8.12805H10.6889V11.992H9.29691ZM7.10091 14.32V13.18H8.16891V14.32H7.10091ZM7.10091 6.92805V5.80005H8.16891V6.92805H7.10091ZM7.10091 6.92805V5.80005H8.16891V6.92805H7.10091ZM10.6889 8.14005H9.29691C9.29691 7.75605 9.19691 7.46005 8.99691 7.25205C8.79691 7.03605 8.52091 6.92805 8.16891 6.92805V5.80005C8.66491 5.80005 9.10091 5.90005 9.47691 6.10005C9.85291 6.30005 10.1489 6.57605 10.3649 6.92805C10.5809 7.28005 10.6889 7.68405 10.6889 8.14005ZM10.6889 11.98C10.6889 12.436 10.5809 12.84 10.3649 13.192C10.1489 13.544 9.85291 13.82 9.47691 14.02C9.10091 14.22 8.66491 14.32 8.16891 14.32V13.18C8.52091 13.18 8.79691 13.076 8.99691 12.868C9.19691 12.652 9.29691 12.356 9.29691 11.98H10.6889ZM6.00891 14.32V5.80005H7.40091V14.32H6.00891Z" fill="currentColor"/> <path d="M3 14.32V5.80005H4.392V14.32H3Z" fill="currentColor"/></g>',
});

export type ReltioIdnLabelProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/idn-label" />` after this module is evaluated. */
export function ReltioIdnLabel(props: ReltioIdnLabelProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`reltio/idn-label`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
