/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/indivudual` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/reltio/indivudual";
 * Optional component: import { ReltioIndivudual } from "@reltio/design/icons/reltio/indivudual";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { registerReltioIcon } from "../registerReltioIcon";

const ICON_NAME = registerReltioIcon("indivudual", {
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path d="M10 9.69226C9.0375 9.69226 8.21358 9.34959 7.52825 8.66426C6.84275 7.97876 6.5 7.15476 6.5 6.19226C6.5 5.22976 6.84275 4.40584 7.52825 3.72051C8.21358 3.03501 9.0375 2.69226 10 2.69226C10.9625 2.69226 11.7864 3.03501 12.4718 3.72051C13.1573 4.40584 13.5 5.22976 13.5 6.19226C13.5 7.15476 13.1573 7.97876 12.4718 8.66426C11.7864 9.34959 10.9625 9.69226 10 9.69226ZM2.5 17.3078V15.0845C2.5 14.5948 2.633 14.1413 2.899 13.724C3.165 13.3067 3.5205 12.9858 3.9655 12.7615C4.95383 12.277 5.95092 11.9136 6.95675 11.6713C7.96258 11.4289 8.977 11.3078 10 11.3078C11.023 11.3078 12.0374 11.4289 13.0433 11.6713C14.0491 11.9136 15.0462 12.277 16.0345 12.7615C16.4795 12.9858 16.835 13.3067 17.101 13.724C17.367 14.1413 17.5 14.5948 17.5 15.0845V17.3078H2.5ZM4 15.8078H16V15.0845C16 14.882 15.9413 14.6945 15.824 14.522C15.7067 14.3497 15.5474 14.209 15.3462 14.1C14.4846 13.6757 13.6061 13.3542 12.7107 13.1355C11.8152 12.917 10.9117 12.8078 10 12.8078C9.08833 12.8078 8.18475 12.917 7.28925 13.1355C6.39392 13.3542 5.51542 13.6757 4.65375 14.1C4.45258 14.209 4.29333 14.3497 4.176 14.522C4.05867 14.6945 4 14.882 4 15.0845V15.8078ZM10 8.19226C10.55 8.19226 11.0208 7.99643 11.4125 7.60476C11.8042 7.21309 12 6.74226 12 6.19226C12 5.64226 11.8042 5.17143 11.4125 4.77976C11.0208 4.38809 10.55 4.19226 10 4.19226C9.45 4.19226 8.97917 4.38809 8.5875 4.77976C8.19583 5.17143 8 5.64226 8 6.19226C8 6.74226 8.19583 7.21309 8.5875 7.60476C8.97917 7.99643 9.45 8.19226 10 8.19226Z" fill="currentColor"/></g>',
});

export type ReltioIndivudualProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/indivudual" />` after this module is evaluated. */
export function ReltioIndivudual(props: ReltioIndivudualProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`reltio/indivudual`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
