/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/line-chart` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/reltio/line-chart";
 * Optional component: import { ReltioLineChart } from "@reltio/design/icons/reltio/line-chart";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { registerReltioIcon } from "../registerReltioIcon";

const ICON_NAME = registerReltioIcon("line-chart", {
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path d="M1.50002 16.1538L0.384766 15.0385L7.53852 7.88477L11.5385 11.8848L18.5808 3.88477L19.6345 4.91927L11.5578 14.1345L7.53852 10.1153L1.50002 16.1538Z" fill="currentColor"/></g>',
});

export type ReltioLineChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/line-chart" />` after this module is evaluated. */
export function ReltioLineChart(props: ReltioLineChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`reltio/line-chart`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
