/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/matching-insights` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/reltio/matching-insights";
 * Optional component: import { ReltioMatchingInsights } from "@reltio/design/icons/reltio/matching-insights";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { registerReltioIcon } from "../registerReltioIcon";

const ICON_NAME = registerReltioIcon("matching-insights", {
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path d="M17.5 16C18.6046 16 19.5 15.1046 19.5 14V2C19.4999 0.895493 18.6045 0 17.5 0H5.5C4.39547 0 3.50007 0.895493 3.5 2V14C3.5 15.1046 4.39543 16 5.5 16H17.5ZM5.5 14.5C5.22386 14.5 5 14.2761 5 14V2C5.00007 1.72392 5.2239 1.5 5.5 1.5H17.5C17.7761 1.5 17.9999 1.72392 18 2V14C18 14.2761 17.7761 14.5 17.5 14.5H5.5ZM13 4.25H7V5.75H13V4.25ZM16 4.25H14.5V5.75H16V4.25ZM14.6924 18H1.80762C1.7307 18 1.66063 17.9674 1.59668 17.9033C1.53263 17.8394 1.50007 17.7693 1.5 17.6924V4.80762H0V17.6924C6.07759e-05 18.1974 0.175496 18.6247 0.525391 18.9746C0.875348 19.3245 1.30254 19.5 1.80762 19.5H14.6924V18ZM13 7.25195H7V8.75195H13V7.25195ZM16 7.25195H14.5V8.75195H16V7.25195ZM13 10.252H7V11.752H13V10.252ZM16 10.252H14.5V11.752H16V10.252Z" fill="currentColor"/></g>',
});

export type ReltioMatchingInsightsProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/matching-insights" />` after this module is evaluated. */
export function ReltioMatchingInsights(props: ReltioMatchingInsightsProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`reltio/matching-insights`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
