/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/organization` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/reltio/organization";
 * Optional component: import { ReltioOrganization } from "@reltio/design/icons/reltio/organization";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { registerReltioIcon } from "../registerReltioIcon";

const ICON_NAME = registerReltioIcon("organization", {
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path d="M0.365479 18.577V1.07703H9.86523V5.07703H19.6345V18.577H0.365479ZM1.86523 17.077H8.36548V14.577H1.86523V17.077ZM1.86523 13.077H8.36548V10.577H1.86523V13.077ZM1.86523 9.07703H8.36548V6.57703H1.86523V9.07703ZM1.86523 5.07703H8.36548V2.57703H1.86523V5.07703ZM9.86523 17.077H18.1347V6.57703H9.86523V17.077ZM12.0577 10.577V9.07703H15.75V10.577H12.0577ZM12.0577 14.577V13.077H15.75V14.577H12.0577Z" fill="currentColor"/></g>',
});

export type ReltioOrganizationProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/organization" />` after this module is evaluated. */
export function ReltioOrganization(props: ReltioOrganizationProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`reltio/organization`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
