/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/product-barcode` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/reltio/product-barcode";
 * Optional component: import { ReltioProductBarcode } from "@reltio/design/icons/reltio/product-barcode";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { registerReltioIcon } from "../registerReltioIcon";

const ICON_NAME = registerReltioIcon("product-barcode", {
	viewBox: "0 0 21 20",
	customTemplateAsString:
		'<g fill="none"><path d="M0 16.6537V3.73071H1.846V16.6537H0ZM2.76925 16.6537V3.73071H4.61525V16.6537H2.76925ZM5.5385 16.6537V3.73071H6.4615V16.6537H5.5385ZM8.3075 16.6537V3.73071H10.1538V16.6537H8.3075ZM11.0767 16.6537V3.73071H13.846V16.6537H11.0767ZM14.769 16.6537V3.73071H15.6923V16.6537H14.769ZM17.5383 16.6537V3.73071H20.3075V16.6537H17.5383Z" fill="currentColor"/></g>',
});

export type ReltioProductBarcodeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/product-barcode" />` after this module is evaluated. */
export function ReltioProductBarcode(props: ReltioProductBarcodeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`reltio/product-barcode`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
