/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/return-to-entity` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/reltio/return-to-entity";
 * Optional component: import { ReltioReturnToEntity } from "@reltio/design/icons/reltio/return-to-entity";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { registerReltioIcon } from "../registerReltioIcon";

const ICON_NAME = registerReltioIcon("return-to-entity", {
	viewBox: "0 0 16 16",
	customTemplateAsString:
		'<g fill="none"><path d="M9.60901 2.22779C9.88235 1.94064 10.3252 1.94053 10.5985 2.22779C10.8716 2.5153 10.8716 2.98205 10.5985 3.26952L10.0764 3.8187H13.25C14.2163 3.81885 14.9999 4.64304 15 5.65948L14.9872 13.1592C14.9871 14.1756 14.2033 14.9996 13.2372 15H2.75L2.57141 14.991C1.68884 14.8969 1.00006 14.1124 1 13.1592V10.9562C1.00017 10.5498 1.31343 10.2201 1.69983 10.2201C2.08623 10.2201 2.39949 10.5498 2.39966 10.9562V13.1592C2.39972 13.3625 2.55674 13.5277 2.75 13.5277H13.2372C13.4301 13.5274 13.5875 13.3623 13.5875 13.1592L13.6003 5.65948C13.6002 5.45635 13.4431 5.29112 13.25 5.29096H9.87476C9.88103 5.29799 9.88703 5.30567 9.89355 5.31253L10.5985 6.05406C10.8716 6.34157 10.8716 6.80742 10.5985 7.09489C10.3252 7.38232 9.88239 7.38215 9.60901 7.09489L7.78979 5.1822C7.5164 4.89452 7.51658 4.42838 7.78979 4.14047L9.60901 2.22779ZM6.61487 1C6.89663 1.00016 7.125 1.23189 7.125 1.51772V8.25347C7.125 8.5393 6.89663 8.77103 6.61487 8.77119H1.51013C1.22837 8.77103 1 8.5393 1 8.25347V1.51772C1 1.23189 1.22837 1.00016 1.51013 1H6.61487ZM2.02112 7.73575H3.55237V6.52773H2.02112V7.73575ZM4.57263 7.73575H6.10388V6.52773H4.57263V7.73575ZM2.02112 5.4869H3.55237V4.27889H2.02112V5.4869ZM4.57263 5.4869H6.10388V4.27889H4.57263V5.4869ZM2.02112 3.24345H3.55237V2.03544H2.02112V3.24345ZM4.57263 3.24345H6.10388V2.03544H4.57263V3.24345Z" fill="currentColor"/></g>',
});

export type ReltioReturnToEntityProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/return-to-entity" />` after this module is evaluated. */
export function ReltioReturnToEntity(props: ReltioReturnToEntityProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`reltio/return-to-entity`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
