/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/segmentation` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/reltio/segmentation";
 * Optional component: import { ReltioSegmentation } from "@reltio/design/icons/reltio/segmentation";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { registerReltioIcon } from "../registerReltioIcon";

const ICON_NAME = registerReltioIcon("segmentation", {
	viewBox: "0 0 16 16",
	customTemplateAsString:
		'<g fill="none"><path d="M3 4C3.55228 4 4 4.44772 4 5V8H7C7.55228 8 8 8.44772 8 9V12H11C11.5523 12 12 12.4477 12 13V16H0V4H3ZM1 15H11V13H7V9H3V5H1V15ZM12.0459 7.55176C12.5501 7.60291 12.9442 8.02918 12.9443 8.54688V10.5469C12.9441 11.0644 12.55 11.4898 12.0459 11.541L11.9443 11.5469H9.94434L9.8418 11.541C9.37104 11.4933 8.99694 11.1192 8.94922 10.6484L8.94434 10.5469V8.5459C8.94471 8.02842 9.33772 7.60289 9.8418 7.55176L9.94434 7.54688H11.9443L12.0459 7.55176ZM9.94434 10.5469H11.9443V8.54688H9.94434V10.5469ZM8.52344 3.14746C9.02743 3.19884 9.42077 3.62505 9.4209 4.14258V6.14258C9.4209 6.69482 8.97312 7.1425 8.4209 7.14258H6.4209C5.86861 7.14258 5.4209 6.69486 5.4209 6.14258V4.14258C5.42103 3.59041 5.8687 3.14258 6.4209 3.14258H8.4209L8.52344 3.14746ZM6.4209 6.14258H8.4209V4.14258H6.4209V6.14258ZM14.0459 1.14746C14.5501 1.19859 14.9442 1.62487 14.9443 2.14258V4.14258L14.9385 4.24512C14.8905 4.71564 14.5165 5.08995 14.0459 5.1377L13.9443 5.14258H11.9443L11.8418 5.1377C11.3712 5.08998 10.9972 4.71567 10.9492 4.24512L10.9443 4.14258V2.14258C10.9445 1.62486 11.3375 1.19858 11.8418 1.14746L11.9443 1.14258H13.9443L14.0459 1.14746ZM11.9443 4.14258H13.9443V2.14258H11.9443V4.14258Z" fill="currentColor"/></g>',
});

export type ReltioSegmentationProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/segmentation" />` after this module is evaluated. */
export function ReltioSegmentation(props: ReltioSegmentationProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`reltio/segmentation`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
