/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/skill` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/reltio/skill";
 * Optional component: import { ReltioSkill } from "@reltio/design/icons/reltio/skill";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { registerReltioIcon } from "../registerReltioIcon";

const ICON_NAME = registerReltioIcon("skill", {
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path d="M9.99995 17.846L3.49995 14.3153V8.89228L0.0384521 7.00003L9.99995 1.57703L19.9615 7.00003V14.1923H18.4615V7.83078L16.5 8.89228V14.3153L9.99995 17.846ZM9.99995 10.7L16.8405 7.00003L9.99995 3.30003L3.15945 7.00003L9.99995 10.7ZM9.99995 16.1385L15 13.4385V9.69228L9.99995 12.4213L4.99995 9.69228V13.4385L9.99995 16.1385Z" fill="currentColor"/></g>',
});

export type ReltioSkillProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/skill" />` after this module is evaluated. */
export function ReltioSkill(props: ReltioSkillProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`reltio/skill`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
