/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/tenant-management` icon. Tree-shakable single import:
 * import "@reltio/design/icons/reltio/tenant-management";
 * Optional component: import { ReltioTenantManagement } from "@reltio/design/icons/reltio/tenant-management";
 */
import { Icon, type IconProps } from "@reltio/design/components";
import { unsafeRegisterIcon } from "@ui5/webcomponents-base/dist/asset-registries/Icons.js";

unsafeRegisterIcon("tenant-management", {
	collection: "reltio",
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path d="M7.46521 9.35352C7.65726 9.52891 7.86259 9.67364 8.08044 9.78711C8.2984 9.90058 8.52939 9.98971 8.77283 10.0537L7.14685 13.75H8.50037V15.25H6.48669L5.13806 18.3154L3.94177 19.4619L3.75037 17.8389L4.88416 15.25H3.67615V13.75H5.54041L7.46521 9.35352ZM14.4594 13.75H16.2631V15.25H15.1166L16.2504 17.8389L16.058 19.4619L14.8617 18.3154L13.5131 15.25H11.2845V16H9.78455V13H11.2845V13.75H12.8529L11.2269 10.0537C11.4704 9.98971 11.7013 9.90061 11.9193 9.78711C12.1372 9.67363 12.3424 9.52896 12.5345 9.35352L14.4594 13.75ZM10.7504 3.39258C11.3015 3.53496 11.7726 3.84242 12.1635 4.31543C12.5545 4.78843 12.7504 5.35 12.7504 6C12.7504 6.76283 12.482 7.4121 11.9467 7.94727C11.4116 8.48231 10.7629 8.74991 10.0004 8.75C9.23762 8.75 8.58823 8.48247 8.0531 7.94727C7.51777 7.4121 7.25037 6.76283 7.25037 6C7.25037 5.35002 7.44533 4.78842 7.8363 4.31543C8.2273 3.84226 8.69903 3.53491 9.25037 3.39258V1H10.7504V3.39258ZM10.0004 4.75C9.65296 4.75 9.35742 4.87139 9.11462 5.11426C8.87162 5.35709 8.75037 5.6525 8.75037 6C8.75037 6.3475 8.87162 6.64291 9.11462 6.88574C9.35742 7.12861 9.65296 7.25 10.0004 7.25C10.3476 7.24991 10.6424 7.12845 10.8851 6.88574C11.1281 6.64291 11.2504 6.3475 11.2504 6C11.2504 5.6525 11.1281 5.35709 10.8851 5.11426C10.6424 4.87155 10.3476 4.75009 10.0004 4.75Z" fill="currentColor"/></g>',
});

const ICON_NAME = "reltio/tenant-management";

export type ReltioTenantManagementProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reltio/tenant-management" />` after this module is evaluated. */
export function ReltioTenantManagement(props: ReltioTenantManagementProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
