/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/compare-action` icon. Tree-shakable single import:
 * import "@reltio/design/icons/compare-action";
 */
import { unsafeRegisterIcon } from "@ui5/webcomponents-base/dist/asset-registries/Icons.js";

unsafeRegisterIcon("compare-action", {
	collection: "reltio",
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path d="M9.75 20H8.25V18H3C2.44772 18 2 17.5523 2 17V3C2 2.44772 2.44772 2 3 2H8.25V0H9.75V20ZM17 2C17.5523 2 18 2.44772 18 3V17C18 17.5523 17.5523 18 17 18H11.75V16.5H16.5V3.5H11.75V2H17ZM15.5 11.5605L14.0303 13.0303L15.5 14.5L14.4395 15.5605L11.9092 13.0303L14.4395 10.5L15.5 11.5605ZM4.5 5.56055L5.96973 7.03027L4.5 8.5L5.56055 9.56055L8.09082 7.03027L5.56055 4.5L4.5 5.56055Z" fill="currentColor"/></g>',
});
