/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/data-lineage` icon. Tree-shakable single import:
 * import "@reltio/design/icons/data-lineage";
 */
import { unsafeRegisterIcon } from "@ui5/webcomponents-base/dist/asset-registries/Icons.js";

unsafeRegisterIcon("data-lineage", {
	collection: "reltio",
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path d="M13.25 18.75V15.75H9.25V10.75H6.75V13.75H0.25V6.25H6.75V9.25H9.25V4.25H13.25V1.25H19.75V8.75H13.25V5.75H10.75V14.25H13.25V11.25H19.75V18.75H13.25ZM14.75 7.25H18.25V2.75H14.75V7.25ZM14.75 17.25H18.25V12.75H14.75V17.25ZM1.75 12.25H5.25V7.75H1.75V12.25Z" fill="currentColor"/></g>',
});
