/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Registers the `reltio/facet-attributes` icon. Tree-shakable single import:
 * import "@reltio/design/icons/facet-attributes";
 */
import { unsafeRegisterIcon } from "@ui5/webcomponents-base/dist/asset-registries/Icons.js";

unsafeRegisterIcon("facet-attributes", {
	collection: "reltio",
	viewBox: "0 0 20 20",
	customTemplateAsString:
		'<g fill="none"><path d="M11.25 7V1.5H18.5V7H11.25ZM1.5 10.5V1.5H8.75V10.5H1.5ZM11.25 18.5V9.5H18.5V18.5H11.25ZM1.5 18.5V13H8.75V18.5H1.5ZM3 9H7.25V3H3V9ZM12.75 17H17V11H12.75V17ZM12.75 5.5H17V3H12.75V5.5ZM3 17H7.25V14.5H3V17Z" fill="currentColor"/></g>',
});
