/**
 * Auto-generated by scripts/build-icons.mjs — do not edit manually.
 * Run: npm run build-icons
 * Source: public/icons/*.svg
 * Gallery of every Reltio icon — rendered in icons.story.mdx (the Overview
 * docs page). A namespace import of the barrel registers the whole set.
 */
import { Icon } from "@ui5/webcomponents-react/Icon";
import * as reltioIcons from "./reltio";

/** Grid of every Reltio icon rendered through the UI5 Icon component. */
export function ReltioIconGallery() {
	return (
		<div
			style={{
				display: "grid",
				gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))",
				gap: "8px",
				fontFamily: "var(--sapFontFamily)",
			}}
		>
			{Object.values(reltioIcons).map((fullName) => (
				<div
					key={fullName}
					style={{
						display: "flex",
						flexDirection: "column",
						alignItems: "center",
						gap: "10px",
						padding: "16px 8px",
						border:
							"1px solid var(--sapTile_BorderColor, var(--sapList_BorderColor))",
						borderRadius: "8px",
						background: "var(--sapTile_Background)",
						color: "var(--sapTextColor)",
						textAlign: "center",
					}}
				>
					<Icon name={fullName} style={{ width: "28px", height: "28px" }} />
					<code
						style={{
							fontSize: "11px",
							color: "var(--sapContent_LabelColor)",
							wordBreak: "break-word",
						}}
					>
						{fullName}
					</code>
				</div>
			))}
		</div>
	);
}
