// Auto-generated by scripts/build-tokens.mjs — do not edit by hand.
// Run: npm run build-tokens
// Source: tokens/sap_horizon.tokens.json, tokens/sap_horizon_dark.tokens.json

import type { Meta, StoryObj } from "@storybook/react-vite";
import { DesignTokens } from "./DesignTokens";
import { brandTokens, semanticTokens, surfaceTokens, interactionTokens, textTokens, typographyTokens, layoutTokens, contentTokens, chartTokens, formControlsTokens, avatarTokens, miscTokens } from "./token-data";

const meta = {
	title: "Design Tokens",
	component: DesignTokens,
	parameters: {
		layout: "padded",
	},
} satisfies Meta<typeof DesignTokens>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Brand: Story = {
	name: "Brand",
	parameters: {
		docs: {
			description: { story: "Brand surface, accent palette, and highlight colors — the primary identity layer of the UI.\n\nKey tokens:\n- `--sapBrandColor` — primary brand identity, main CTAs and primary actions\n- `--sapHighlightColor` — selection and focus highlight\n- `--sapHighlightTextColor` — text on highlighted backgrounds\n- `--sapAccentColor1..10` — 10 distinct accent hues for categorical data (charts, tags, avatars)\n- `--sapAccentBackgroundColor1..10` — lighter tinted backgrounds pairing with each AccentColor\n\nCSS: `color: var(--sapBrandColor)` · `background: var(--sapAccentBackgroundColor1)`" },
		},
	},
	args: { tokens: brandTokens },
};

export const Semantic: Story = {
	name: "Semantic",
	parameters: {
		docs: {
			description: { story: "Status and feedback colors — success, error, warning, information, neutral, plus indication scales.\n\nKey tokens (each semantic state has a Color + Background + BorderColor triplet):\n- `--sapSuccessColor` / `Background` / `BorderColor` — positive outcome\n- `--sapErrorColor` / `Background` / `BorderColor` — error or failure\n- `--sapWarningColor` / `Background` / `BorderColor` — caution\n- `--sapInformationColor` / `Background` / `BorderColor` — informational\n- `--sapNeutralColor` — neutral, non-semantic state\n- `--sapPositiveColor`, `--sapNegativeColor`, `--sapCriticalColor`, `--sapInformativeColor` — state variants with matching `*ElementColor` and `*TextColor`\n- `--sapIndicationColor_1..10` — extended 10-step indication palette, each with `_Background`, `_BorderColor`, `_TextColor`, `_Hover_Background`, `_Active_Background`\n\nCSS: `color: var(--sapErrorColor)` · `background: var(--sapErrorBackground)` · `border-color: var(--sapErrorBorderColor)`" },
		},
	},
	args: { tokens: semanticTokens },
};

export const Surface: Story = {
	name: "Surface",
	parameters: {
		docs: {
			description: { story: "Backgrounds, page surfaces, shells, panels, and structural containers.\n\nKey tokens:\n- `--sapBackgroundColor` — default page background\n- `--sapBaseColor` — base surface for cards and controls\n- `--sapShell_Background` — app shell / header background\n- `--sapPageHeader_Background` / `--sapPageFooter_Background` — page header and footer\n- `--sapGroup_ContentBackground` — content group background\n- `--sapTile_Background` — tile / card surface\n- `--sapObjectHeader_Background` — object page header\n- `--sapToolbar_Background` — toolbar surface\n- `--sapInfobar_Background` — info bar background\n- `--sapBlockLayer_Background` — modal overlay layer\n\nCSS: `background: var(--sapBackgroundColor)` · `background: var(--sapShell_Background)`" },
		},
	},
	args: { tokens: surfaceTokens },
};

export const Interaction: Story = {
	name: "Interaction",
	parameters: {
		docs: {
			description: { story: "Hover, active, and selected interaction-state colors applied across components.\n\nKey tokens:\n- `--sapHoverColor` — universal hover background\n- `--sapActiveColor` — universal active / pressed background\n- `--sapSelectedColor` — universal selected background\n\nThese are base tokens. Component-specific interaction states (e.g. `--sapButton_Hover_Background`, `--sapList_Hover_Background`) are in their respective categories (Form Controls, etc.).\n\nCSS: `background: var(--sapHoverColor)` · `background: var(--sapSelectedColor)`" },
		},
	},
	args: { tokens: interactionTokens },
};

export const Text: Story = {
	name: "Text & Links",
	parameters: {
		docs: {
			description: { story: "Body text, titles, and link colors — including hover/visited states.\n\nKey tokens:\n- `--sapTextColor` — default body text\n- `--sapTitleColor` — headings\n- `--sapLinkColor` — interactive link text\n- `--sapLink_Hover_Color` — link hover\n- `--sapLink_Visited_Color` — visited link\n- `--sapLink_Active_Color` — link pressed state\n- `--sapLink_SubtleColor` — de-emphasized link\n- `--sapLink_InvertedColor` — link on dark backgrounds\n\nCSS: `color: var(--sapTextColor)` · `color: var(--sapLinkColor)`" },
		},
	},
	args: { tokens: textTokens },
};

export const Typography: Story = {
	name: "Typography",
	parameters: {
		docs: {
			description: { story: "Font families, sizes, weights, and the SAP 72 type-scale.\n\nKey tokens:\n- `--sapFontFamily` — default font stack (\"72\", \"72full\", Arial, Helvetica, sans-serif)\n- `--sapFontSize` — base font size (0.875rem)\n- `--sapFontLargeSize` / `--sapFontSmallSize` — large and small text\n- `--sapFontHeader1Size`..`6Size` — heading scale (H1 through H6)\n- `--sapFontBoldWeight` — bold weight value\n- `--sapFontHeaderFamily` — header-specific font family\n- `--sapFontMonoFamily` — monospace font (\"72Mono\")\n\nCSS: `font-family: var(--sapFontFamily)` · `font-size: var(--sapFontHeader1Size)`" },
		},
	},
	args: { tokens: typographyTokens },
};

export const Layout: Story = {
	name: "Layout & Sizing",
	parameters: {
		docs: {
			description: { story: "Element heights, border radii, breakpoints, and scrollbar sizing.\n\nKey tokens:\n- `--sapElement_Height` — default control height (2.75rem / 44px)\n- `--sapElement_Compact_Height` — compact mode height (2rem / 32px)\n- `--sapElement_Condensed_Height` — condensed height (1.5rem / 24px)\n- `--sapElement_BorderCornerRadius` — default border radius (0.75rem / 12px)\n- `--sapElement_BorderWidth` — default border width (0.0625rem / 1px)\n- `--sapBreakpoint_S_Min` / `M_Min` / `L_Min` / `XL_Min` — responsive breakpoints\n- `--sapScrollBar_Dimension` — scrollbar size\n\nCSS: `height: var(--sapElement_Height)` · `border-radius: var(--sapElement_BorderCornerRadius)`" },
		},
	},
	args: { tokens: layoutTokens },
};

export const Content: Story = {
	name: "Content & Icons",
	parameters: {
		docs: {
			description: { story: "Content-area tokens — labels, icons, focus rings, shadows, and foreground details.\n\nKey tokens:\n- `--sapContent_LabelColor` — label / secondary text color\n- `--sapContent_IconColor` — default icon color\n- `--sapContent_FocusColor` — focus ring color\n- `--sapContent_FocusWidth` — focus ring width\n- `--sapContent_FocusStyle` — focus ring style (e.g. dotted, solid)\n- `--sapContent_Shadow0`..`3` — four elevation levels as full `box-shadow` strings\n- `--sapContent_ForegroundColor` — default foreground\n- `--sapContent_BadgeBackground` — badge / counter background\n- `--sapContent_ImagePlaceholderBackground` — image placeholder\n\nCSS: `color: var(--sapContent_LabelColor)` · `box-shadow: var(--sapContent_Shadow1)`" },
		},
	},
	args: { tokens: contentTokens },
};

export const Chart: Story = {
	name: "Charts & Data Viz",
	parameters: {
		docs: {
			description: { story: "Categorical and sequential chart palettes plus legend-marker colors.\n\nKey tokens:\n- `--sapChart_OrderedColor_1..12` — 12-step categorical chart palette\n- `--sapChart_Background` — chart canvas background\n- `--sapChart_ReferenceLineColor` — reference / threshold lines\n- `--sapChart_Good` / `--sapChart_Bad` / `--sapChart_Critical` — semantic chart colors\n- `--sapChart_Sequence_1..12` — sequential palette variants with `_BorderColor`\n- `--sapLegendColor1..20` — legend marker foreground colors\n- `--sapLegendBackgroundColor1..20` — legend marker backgrounds\n\nCSS: `fill: var(--sapChart_OrderedColor_1)` · `background: var(--sapChart_Background)`" },
		},
	},
	args: { tokens: chartTokens },
};

export const FormControls: Story = {
	name: "Form Controls",
	parameters: {
		docs: {
			description: { story: "Component-specific tokens for form fields, buttons, tabs, sliders, and lists.\n\nKey tokens:\n- `--sapField_Background` / `--sapField_BorderColor` — input field surface and border\n- `--sapField_Hover_Background` / `--sapField_Focus_Background` — field interaction states\n- `--sapField_InvalidColor` / `--sapField_WarningColor` / `--sapField_SuccessColor` — validation state colors\n- `--sapButton_Background` / `--sapButton_BorderColor` — default button\n- `--sapButton_Emphasized_Background` — primary / CTA button\n- `--sapButton_Hover_Background` / `--sapButton_Active_Background` — button states\n- `--sapList_Background` / `--sapList_BorderColor` — list surface\n- `--sapList_Hover_Background` / `--sapList_Active_Background` — list item states\n- `--sapTab_Background` / `--sapTab_Selected_Background` — tab bar\n\nCSS: `background: var(--sapField_Background)` · `border-color: var(--sapField_BorderColor)`" },
		},
	},
	args: { tokens: formControlsTokens },
};

export const Avatar: Story = {
	name: "Avatars & Assistant",
	parameters: {
		docs: {
			description: { story: "Avatar palette and AI assistant component-specific tokens.\n\nKey tokens:\n- `--sapAvatar_1..10_Background` / `_BorderColor` / `_TextColor` — 10 avatar color presets\n- `--sapAvatar_1..10_Hover_Background` — avatar hover states\n- `--sapAssistant_Background` — AI assistant surface\n- `--sapAssistant_BorderColor` / `--sapAssistant_TextColor` — assistant styling\n- `--sapAssistant_Hover_Background` / `--sapAssistant_Active_Background` — assistant interaction states\n- `--sapAssistant_Answer_Background` — answer bubble surface\n\nCSS: `background: var(--sapAvatar_1_Background)` · `color: var(--sapAvatar_1_TextColor)`" },
		},
	},
	args: { tokens: avatarTokens },
};

export const Misc: Story = {
	name: "Miscellaneous",
	parameters: {
		docs: {
			description: { story: "Company logo, theme identifier, progress indicators, and other ungrouped tokens.\n\nKey tokens:\n- `--sapCompanyLogo` — company logo reference\n- `--sapSapThemeId` — theme identifier string\n- `--sapProgress_Background` / `--sapProgress_BorderColor` — progress bar base\n- `--sapProgress_PositiveBackground` / `NegativeBackground` / `CriticalBackground` — progress semantic states\n- `--sapProgress_FontSize` / `--sapProgress_TextColor` — progress label styling\n\nCSS: `background: var(--sapProgress_Background)` · `border-color: var(--sapProgress_BorderColor)`" },
		},
	},
	args: { tokens: miscTokens },
};
