/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `accept` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/accept";
 * Optional component: import { Accept } from "@reltio/design/icons/sap/accept";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/accept.js";

export type AcceptProps = Omit<IconProps, "name">;

/** Renders `<Icon name="accept" />` after this module is evaluated. */
export function Accept(props: AcceptProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`accept`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
