/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `accelerated` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/accelerated";
 * Optional component: import { Accelerated } from "@reltio/design/icons/sap/accelerated";
 */
import "@ui5/webcomponents-icons/dist/accelerated.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "accelerated";

export type AcceleratedProps = Omit<IconProps, "name">;

/** Renders `<Icon name="accelerated" />` after this module is evaluated. */
export function Accelerated(props: AcceleratedProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
