/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `accidental-leave` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/accidental-leave";
 * Optional component: import { AccidentalLeave } from "@reltio/design/icons/sap/accidental-leave";
 */
import "@ui5/webcomponents-icons/dist/accidental-leave.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "accidental-leave";

export type AccidentalLeaveProps = Omit<IconProps, "name">;

/** Renders `<Icon name="accidental-leave" />` after this module is evaluated. */
export function AccidentalLeave(props: AccidentalLeaveProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
