/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `activate` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/activate";
 * Optional component: import { Activate } from "@reltio/design/icons/sap/activate";
 */
import "@ui5/webcomponents-icons/dist/activate.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "activate";

export type ActivateProps = Omit<IconProps, "name">;

/** Renders `<Icon name="activate" />` after this module is evaluated. */
export function Activate(props: ActivateProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
