/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `activity-individual` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/activity-individual";
 * Optional component: import { ActivityIndividual } from "@reltio/design/icons/sap/activity-individual";
 */
import "@ui5/webcomponents-icons/dist/activity-individual.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "activity-individual";

export type ActivityIndividualProps = Omit<IconProps, "name">;

/** Renders `<Icon name="activity-individual" />` after this module is evaluated. */
export function ActivityIndividual(props: ActivityIndividualProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
