/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `activities` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/activities";
 * Optional component: import { Activities } from "@reltio/design/icons/sap/activities";
 */
import "@ui5/webcomponents-icons/dist/activities.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "activities";

export type ActivitiesProps = Omit<IconProps, "name">;

/** Renders `<Icon name="activities" />` after this module is evaluated. */
export function Activities(props: ActivitiesProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
