/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `activity-assigned-to-goal` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/activity-assigned-to-goal";
 * Optional component: import { ActivityAssignedToGoal } from "@reltio/design/icons/sap/activity-assigned-to-goal";
 */
import "@ui5/webcomponents-icons/dist/activity-assigned-to-goal.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "activity-assigned-to-goal";

export type ActivityAssignedToGoalProps = Omit<IconProps, "name">;

/** Renders `<Icon name="activity-assigned-to-goal" />` after this module is evaluated. */
export function ActivityAssignedToGoal(props: ActivityAssignedToGoalProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
