/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `add-calendar` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/add-calendar";
 * Optional component: import { AddCalendar } from "@reltio/design/icons/sap/add-calendar";
 */
import "@ui5/webcomponents-icons/dist/add-calendar.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "add-calendar";

export type AddCalendarProps = Omit<IconProps, "name">;

/** Renders `<Icon name="add-calendar" />` after this module is evaluated. */
export function AddCalendar(props: AddCalendarProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
