/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `add-equipment` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/add-equipment";
 * Optional component: import { AddEquipment } from "@reltio/design/icons/sap/add-equipment";
 */
import "@ui5/webcomponents-icons/dist/add-equipment.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "add-equipment";

export type AddEquipmentProps = Omit<IconProps, "name">;

/** Renders `<Icon name="add-equipment" />` after this module is evaluated. */
export function AddEquipment(props: AddEquipmentProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
