/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `add-coursebook` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/add-coursebook";
 * Optional component: import { AddCoursebook } from "@reltio/design/icons/sap/add-coursebook";
 */
import "@ui5/webcomponents-icons/dist/add-coursebook.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "add-coursebook";

export type AddCoursebookProps = Omit<IconProps, "name">;

/** Renders `<Icon name="add-coursebook" />` after this module is evaluated. */
export function AddCoursebook(props: AddCoursebookProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
