/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `add-document` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/add-document";
 * Optional component: import { AddDocument } from "@reltio/design/icons/sap/add-document";
 */
import "@ui5/webcomponents-icons/dist/add-document.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "add-document";

export type AddDocumentProps = Omit<IconProps, "name">;

/** Renders `<Icon name="add-document" />` after this module is evaluated. */
export function AddDocument(props: AddDocumentProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
