/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `add-contact` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/add-contact";
 * Optional component: import { AddContact } from "@reltio/design/icons/sap/add-contact";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/add-contact.js";

export type AddContactProps = Omit<IconProps, "name">;

/** Renders `<Icon name="add-contact" />` after this module is evaluated. */
export function AddContact(props: AddContactProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`add-contact`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
