/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `add-activity` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/add-activity";
 * Optional component: import { AddActivity } from "@reltio/design/icons/sap/add-activity";
 */
import "@ui5/webcomponents-icons/dist/add-activity.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "add-activity";

export type AddActivityProps = Omit<IconProps, "name">;

/** Renders `<Icon name="add-activity" />` after this module is evaluated. */
export function AddActivity(props: AddActivityProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
