/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `addresses` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/addresses";
 * Optional component: import { Addresses } from "@reltio/design/icons/sap/addresses";
 */
import "@ui5/webcomponents-icons/dist/addresses.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "addresses";

export type AddressesProps = Omit<IconProps, "name">;

/** Renders `<Icon name="addresses" />` after this module is evaluated. */
export function Addresses(props: AddressesProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
