/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `address-book` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/address-book";
 * Optional component: import { AddressBook } from "@reltio/design/icons/sap/address-book";
 */
import "@ui5/webcomponents-icons/dist/address-book.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "address-book";

export type AddressBookProps = Omit<IconProps, "name">;

/** Renders `<Icon name="address-book" />` after this module is evaluated. */
export function AddressBook(props: AddressBookProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
