/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `ai` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/ai";
 * Optional component: import { Ai } from "@reltio/design/icons/sap/ai";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/ai.js";

export type AiProps = Omit<IconProps, "name">;

/** Renders `<Icon name="ai" />` after this module is evaluated. */
export function Ai(props: AiProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`ai`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
