/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `appear-offline` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/appear-offline";
 * Optional component: import { AppearOffline } from "@reltio/design/icons/sap/appear-offline";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/appear-offline.js";

export type AppearOfflineProps = Omit<IconProps, "name">;

/** Renders `<Icon name="appear-offline" />` after this module is evaluated. */
export function AppearOffline(props: AppearOfflineProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`appear-offline`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
