/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `appear-offline` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/appear-offline";
 * Optional component: import { AppearOffline } from "@reltio/design/icons/sap/appear-offline";
 */
import "@ui5/webcomponents-icons/dist/appear-offline.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "appear-offline";

export type AppearOfflineProps = Omit<IconProps, "name">;

/** Renders `<Icon name="appear-offline" />` after this module is evaluated. */
export function AppearOffline(props: AppearOfflineProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
