/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `area-chart` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/area-chart";
 * Optional component: import { AreaChart } from "@reltio/design/icons/sap/area-chart";
 */
import "@ui5/webcomponents-icons/dist/area-chart.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "area-chart";

export type AreaChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="area-chart" />` after this module is evaluated. */
export function AreaChart(props: AreaChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
