/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `arrow-left` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/arrow-left";
 * Optional component: import { ArrowLeft } from "@reltio/design/icons/sap/arrow-left";
 */
import "@ui5/webcomponents-icons/dist/arrow-left.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "arrow-left";

export type ArrowLeftProps = Omit<IconProps, "name">;

/** Renders `<Icon name="arrow-left" />` after this module is evaluated. */
export function ArrowLeft(props: ArrowLeftProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
