/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `arrow-top` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/arrow-top";
 * Optional component: import { ArrowTop } from "@reltio/design/icons/sap/arrow-top";
 */
import "@ui5/webcomponents-icons/dist/arrow-top.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "arrow-top";

export type ArrowTopProps = Omit<IconProps, "name">;

/** Renders `<Icon name="arrow-top" />` after this module is evaluated. */
export function ArrowTop(props: ArrowTopProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
