/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `arrow-top` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/arrow-top";
 * Optional component: import { ArrowTop } from "@reltio/design/icons/sap/arrow-top";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/arrow-top.js";

export type ArrowTopProps = Omit<IconProps, "name">;

/** Renders `<Icon name="arrow-top" />` after this module is evaluated. */
export function ArrowTop(props: ArrowTopProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`arrow-top`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
