/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `attachment-photo` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/attachment-photo";
 * Optional component: import { AttachmentPhoto } from "@reltio/design/icons/sap/attachment-photo";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/attachment-photo.js";

export type AttachmentPhotoProps = Omit<IconProps, "name">;

/** Renders `<Icon name="attachment-photo" />` after this module is evaluated. */
export function AttachmentPhoto(props: AttachmentPhotoProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`attachment-photo`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
