/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `attachment-video` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/attachment-video";
 * Optional component: import { AttachmentVideo } from "@reltio/design/icons/sap/attachment-video";
 */
import "@ui5/webcomponents-icons/dist/attachment-video.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "attachment-video";

export type AttachmentVideoProps = Omit<IconProps, "name">;

/** Renders `<Icon name="attachment-video" />` after this module is evaluated. */
export function AttachmentVideo(props: AttachmentVideoProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
