/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `attachment-audio` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/attachment-audio";
 * Optional component: import { AttachmentAudio } from "@reltio/design/icons/sap/attachment-audio";
 */
import "@ui5/webcomponents-icons/dist/attachment-audio.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "attachment-audio";

export type AttachmentAudioProps = Omit<IconProps, "name">;

/** Renders `<Icon name="attachment-audio" />` after this module is evaluated. */
export function AttachmentAudio(props: AttachmentAudioProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
