/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `attachment-html` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/attachment-html";
 * Optional component: import { AttachmentHtml } from "@reltio/design/icons/sap/attachment-html";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/attachment-html.js";

export type AttachmentHtmlProps = Omit<IconProps, "name">;

/** Renders `<Icon name="attachment-html" />` after this module is evaluated. */
export function AttachmentHtml(props: AttachmentHtmlProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`attachment-html`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
