/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `attachment-text-file` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/attachment-text-file";
 * Optional component: import { AttachmentTextFile } from "@reltio/design/icons/sap/attachment-text-file";
 */
import "@ui5/webcomponents-icons/dist/attachment-text-file.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "attachment-text-file";

export type AttachmentTextFileProps = Omit<IconProps, "name">;

/** Renders `<Icon name="attachment-text-file" />` after this module is evaluated. */
export function AttachmentTextFile(props: AttachmentTextFileProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
