/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `attachment-e-pub` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/attachment-e-pub";
 * Optional component: import { AttachmentEPub } from "@reltio/design/icons/sap/attachment-e-pub";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/attachment-e-pub.js";

export type AttachmentEPubProps = Omit<IconProps, "name">;

/** Renders `<Icon name="attachment-e-pub" />` after this module is evaluated. */
export function AttachmentEPub(props: AttachmentEPubProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`attachment-e-pub`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
