/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `attachment-e-pub` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/attachment-e-pub";
 * Optional component: import { AttachmentEPub } from "@reltio/design/icons/sap/attachment-e-pub";
 */
import "@ui5/webcomponents-icons/dist/attachment-e-pub.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "attachment-e-pub";

export type AttachmentEPubProps = Omit<IconProps, "name">;

/** Renders `<Icon name="attachment-e-pub" />` after this module is evaluated. */
export function AttachmentEPub(props: AttachmentEPubProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
