/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `away` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/away";
 * Optional component: import { Away } from "@reltio/design/icons/sap/away";
 */
import "@ui5/webcomponents-icons/dist/away.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "away";

export type AwayProps = Omit<IconProps, "name">;

/** Renders `<Icon name="away" />` after this module is evaluated. */
export function Away(props: AwayProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
