/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `back-to-top` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/back-to-top";
 * Optional component: import { BackToTop } from "@reltio/design/icons/sap/back-to-top";
 */
import "@ui5/webcomponents-icons/dist/back-to-top.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "back-to-top";

export type BackToTopProps = Omit<IconProps, "name">;

/** Renders `<Icon name="back-to-top" />` after this module is evaluated. */
export function BackToTop(props: BackToTopProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
