/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `batch-payments` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/batch-payments";
 * Optional component: import { BatchPayments } from "@reltio/design/icons/sap/batch-payments";
 */
import "@ui5/webcomponents-icons/dist/batch-payments.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "batch-payments";

export type BatchPaymentsProps = Omit<IconProps, "name">;

/** Renders `<Icon name="batch-payments" />` after this module is evaluated. */
export function BatchPayments(props: BatchPaymentsProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
