/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `bbyd-active-sales` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/bbyd-active-sales";
 * Optional component: import { BbydActiveSales } from "@reltio/design/icons/sap/bbyd-active-sales";
 */
import "@ui5/webcomponents-icons/dist/bbyd-active-sales.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "bbyd-active-sales";

export type BbydActiveSalesProps = Omit<IconProps, "name">;

/** Renders `<Icon name="bbyd-active-sales" />` after this module is evaluated. */
export function BbydActiveSales(props: BbydActiveSalesProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
