/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `bed` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/bed";
 * Optional component: import { Bed } from "@reltio/design/icons/sap/bed";
 */
import "@ui5/webcomponents-icons/dist/bed.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "bed";

export type BedProps = Omit<IconProps, "name">;

/** Renders `<Icon name="bed" />` after this module is evaluated. */
export function Bed(props: BedProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
