/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `biometric-face` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/biometric-face";
 * Optional component: import { BiometricFace } from "@reltio/design/icons/sap/biometric-face";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/biometric-face.js";

export type BiometricFaceProps = Omit<IconProps, "name">;

/** Renders `<Icon name="biometric-face" />` after this module is evaluated. */
export function BiometricFace(props: BiometricFaceProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`biometric-face`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
