/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `biometric-face` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/biometric-face";
 * Optional component: import { BiometricFace } from "@reltio/design/icons/sap/biometric-face";
 */
import "@ui5/webcomponents-icons/dist/biometric-face.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "biometric-face";

export type BiometricFaceProps = Omit<IconProps, "name">;

/** Renders `<Icon name="biometric-face" />` after this module is evaluated. */
export function BiometricFace(props: BiometricFaceProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
