/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `blank-tag` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/blank-tag";
 * Optional component: import { BlankTag } from "@reltio/design/icons/sap/blank-tag";
 */
import "@ui5/webcomponents-icons/dist/blank-tag.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "blank-tag";

export type BlankTagProps = Omit<IconProps, "name">;

/** Renders `<Icon name="blank-tag" />` after this module is evaluated. */
export function BlankTag(props: BlankTagProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
