/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `blank-tag-2` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/blank-tag-2";
 * Optional component: import { BlankTag2 } from "@reltio/design/icons/sap/blank-tag-2";
 */
import "@ui5/webcomponents-icons/dist/blank-tag-2.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "blank-tag-2";

export type BlankTag2Props = Omit<IconProps, "name">;

/** Renders `<Icon name="blank-tag-2" />` after this module is evaluated. */
export function BlankTag2(props: BlankTag2Props) {
	return <Icon name={ICON_NAME} {...props} />;
}
