/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `blur` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/blur";
 * Optional component: import { Blur } from "@reltio/design/icons/sap/blur";
 */
import "@ui5/webcomponents-icons/dist/blur.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "blur";

export type BlurProps = Omit<IconProps, "name">;

/** Renders `<Icon name="blur" />` after this module is evaluated. */
export function Blur(props: BlurProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
