/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `bold-text` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/bold-text";
 * Optional component: import { BoldText } from "@reltio/design/icons/sap/bold-text";
 */
import "@ui5/webcomponents-icons/dist/bold-text.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "bold-text";

export type BoldTextProps = Omit<IconProps, "name">;

/** Renders `<Icon name="bold-text" />` after this module is evaluated. */
export function BoldText(props: BoldTextProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
