/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `bookmark` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/bookmark";
 * Optional component: import { Bookmark } from "@reltio/design/icons/sap/bookmark";
 */
import "@ui5/webcomponents-icons/dist/bookmark.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "bookmark";

export type BookmarkProps = Omit<IconProps, "name">;

/** Renders `<Icon name="bookmark" />` after this module is evaluated. */
export function Bookmark(props: BookmarkProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
