/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `border` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/border";
 * Optional component: import { Border } from "@reltio/design/icons/sap/border";
 */
import "@ui5/webcomponents-icons/dist/border.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "border";

export type BorderProps = Omit<IconProps, "name">;

/** Renders `<Icon name="border" />` after this module is evaluated. */
export function Border(props: BorderProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
