/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `broken-link` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/broken-link";
 * Optional component: import { BrokenLink } from "@reltio/design/icons/sap/broken-link";
 */
import "@ui5/webcomponents-icons/dist/broken-link.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "broken-link";

export type BrokenLinkProps = Omit<IconProps, "name">;

/** Renders `<Icon name="broken-link" />` after this module is evaluated. */
export function BrokenLink(props: BrokenLinkProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
