/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `browse-folder` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/browse-folder";
 * Optional component: import { BrowseFolder } from "@reltio/design/icons/sap/browse-folder";
 */
import "@ui5/webcomponents-icons/dist/browse-folder.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "browse-folder";

export type BrowseFolderProps = Omit<IconProps, "name">;

/** Renders `<Icon name="browse-folder" />` after this module is evaluated. */
export function BrowseFolder(props: BrowseFolderProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
