/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `business-by-design` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/business-by-design";
 * Optional component: import { BusinessByDesign } from "@reltio/design/icons/sap/business-by-design";
 */
import "@ui5/webcomponents-icons/dist/business-by-design.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "business-by-design";

export type BusinessByDesignProps = Omit<IconProps, "name">;

/** Renders `<Icon name="business-by-design" />` after this module is evaluated. */
export function BusinessByDesign(props: BusinessByDesignProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
