/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `business-one` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/business-one";
 * Optional component: import { BusinessOne } from "@reltio/design/icons/sap/business-one";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/business-one.js";

export type BusinessOneProps = Omit<IconProps, "name">;

/** Renders `<Icon name="business-one" />` after this module is evaluated. */
export function BusinessOne(props: BusinessOneProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`business-one`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
