/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `business-objects-experience` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/business-objects-experience";
 * Optional component: import { BusinessObjectsExperience } from "@reltio/design/icons/sap/business-objects-experience";
 */
import "@ui5/webcomponents-icons/dist/business-objects-experience.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "business-objects-experience";

export type BusinessObjectsExperienceProps = Omit<IconProps, "name">;

/** Renders `<Icon name="business-objects-experience" />` after this module is evaluated. */
export function BusinessObjectsExperience(
	props: BusinessObjectsExperienceProps,
) {
	return <Icon name={ICON_NAME} {...props} />;
}
