/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `business-card` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/business-card";
 * Optional component: import { BusinessCard } from "@reltio/design/icons/sap/business-card";
 */
import "@ui5/webcomponents-icons/dist/business-card.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "business-card";

export type BusinessCardProps = Omit<IconProps, "name">;

/** Renders `<Icon name="business-card" />` after this module is evaluated. */
export function BusinessCard(props: BusinessCardProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
