/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `busy` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/busy";
 * Optional component: import { Busy } from "@reltio/design/icons/sap/busy";
 */
import "@ui5/webcomponents-icons/dist/busy.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "busy";

export type BusyProps = Omit<IconProps, "name">;

/** Renders `<Icon name="busy" />` after this module is evaluated. */
export function Busy(props: BusyProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
