/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `calendar` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/calendar";
 * Optional component: import { Calendar } from "@reltio/design/icons/sap/calendar";
 */
import "@ui5/webcomponents-icons/dist/calendar.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "calendar";

export type CalendarProps = Omit<IconProps, "name">;

/** Renders `<Icon name="calendar" />` after this module is evaluated. */
export function Calendar(props: CalendarProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
