/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `cancel-maintenance` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/cancel-maintenance";
 * Optional component: import { CancelMaintenance } from "@reltio/design/icons/sap/cancel-maintenance";
 */
import "@ui5/webcomponents-icons/dist/cancel-maintenance.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "cancel-maintenance";

export type CancelMaintenanceProps = Omit<IconProps, "name">;

/** Renders `<Icon name="cancel-maintenance" />` after this module is evaluated. */
export function CancelMaintenance(props: CancelMaintenanceProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
