/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `cancel-share` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/cancel-share";
 * Optional component: import { CancelShare } from "@reltio/design/icons/sap/cancel-share";
 */
import "@ui5/webcomponents-icons/dist/cancel-share.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "cancel-share";

export type CancelShareProps = Omit<IconProps, "name">;

/** Renders `<Icon name="cancel-share" />` after this module is evaluated. */
export function CancelShare(props: CancelShareProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
