/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `capital-projects` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/capital-projects";
 * Optional component: import { CapitalProjects } from "@reltio/design/icons/sap/capital-projects";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/capital-projects.js";

export type CapitalProjectsProps = Omit<IconProps, "name">;

/** Renders `<Icon name="capital-projects" />` after this module is evaluated. */
export function CapitalProjects(props: CapitalProjectsProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`capital-projects`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
