/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `car-rental` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/car-rental";
 * Optional component: import { CarRental } from "@reltio/design/icons/sap/car-rental";
 */
import "@ui5/webcomponents-icons/dist/car-rental.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "car-rental";

export type CarRentalProps = Omit<IconProps, "name">;

/** Renders `<Icon name="car-rental" />` after this module is evaluated. */
export function CarRental(props: CarRentalProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
