/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `cargo-train` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/cargo-train";
 * Optional component: import { CargoTrain } from "@reltio/design/icons/sap/cargo-train";
 */
import "@ui5/webcomponents-icons/dist/cargo-train.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "cargo-train";

export type CargoTrainProps = Omit<IconProps, "name">;

/** Renders `<Icon name="cargo-train" />` after this module is evaluated. */
export function CargoTrain(props: CargoTrainProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
