/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `cart-approval` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/cart-approval";
 * Optional component: import { CartApproval } from "@reltio/design/icons/sap/cart-approval";
 */
import "@ui5/webcomponents-icons/dist/cart-approval.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "cart-approval";

export type CartApprovalProps = Omit<IconProps, "name">;

/** Renders `<Icon name="cart-approval" />` after this module is evaluated. */
export function CartApproval(props: CartApprovalProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
