/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `cart-4` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/cart-4";
 * Optional component: import { Cart4 } from "@reltio/design/icons/sap/cart-4";
 */
import "@ui5/webcomponents-icons/dist/cart-4.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "cart-4";

export type Cart4Props = Omit<IconProps, "name">;

/** Renders `<Icon name="cart-4" />` after this module is evaluated. */
export function Cart4(props: Cart4Props) {
	return <Icon name={ICON_NAME} {...props} />;
}
