/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `cart-3` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/cart-3";
 * Optional component: import { Cart3 } from "@reltio/design/icons/sap/cart-3";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/cart-3.js";

export type Cart3Props = Omit<IconProps, "name">;

/** Renders `<Icon name="cart-3" />` after this module is evaluated. */
export function Cart3(props: Cart3Props) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`cart-3`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
