/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `cart-full` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/cart-full";
 * Optional component: import { CartFull } from "@reltio/design/icons/sap/cart-full";
 */
import "@ui5/webcomponents-icons/dist/cart-full.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "cart-full";

export type CartFullProps = Omit<IconProps, "name">;

/** Renders `<Icon name="cart-full" />` after this module is evaluated. */
export function CartFull(props: CartFullProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
