/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `cause` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/cause";
 * Optional component: import { Cause } from "@reltio/design/icons/sap/cause";
 */
import "@ui5/webcomponents-icons/dist/cause.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "cause";

export type CauseProps = Omit<IconProps, "name">;

/** Renders `<Icon name="cause" />` after this module is evaluated. */
export function Cause(props: CauseProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
