/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `chain-link` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/chain-link";
 * Optional component: import { ChainLink } from "@reltio/design/icons/sap/chain-link";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/chain-link.js";

export type ChainLinkProps = Omit<IconProps, "name">;

/** Renders `<Icon name="chain-link" />` after this module is evaluated. */
export function ChainLink(props: ChainLinkProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`chain-link`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
