/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `chalkboard` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/chalkboard";
 * Optional component: import { Chalkboard } from "@reltio/design/icons/sap/chalkboard";
 */
import "@ui5/webcomponents-icons/dist/chalkboard.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "chalkboard";

export type ChalkboardProps = Omit<IconProps, "name">;

/** Renders `<Icon name="chalkboard" />` after this module is evaluated. */
export function Chalkboard(props: ChalkboardProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
