/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `chart-axis` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/chart-axis";
 * Optional component: import { ChartAxis } from "@reltio/design/icons/sap/chart-axis";
 */
import "@ui5/webcomponents-icons/dist/chart-axis.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "chart-axis";

export type ChartAxisProps = Omit<IconProps, "name">;

/** Renders `<Icon name="chart-axis" />` after this module is evaluated. */
export function ChartAxis(props: ChartAxisProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
