/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `chart-table-view` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/chart-table-view";
 * Optional component: import { ChartTableView } from "@reltio/design/icons/sap/chart-table-view";
 */
import "@ui5/webcomponents-icons/dist/chart-table-view.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "chart-table-view";

export type ChartTableViewProps = Omit<IconProps, "name">;

/** Renders `<Icon name="chart-table-view" />` after this module is evaluated. */
export function ChartTableView(props: ChartTableViewProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
