/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `check-availability` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/check-availability";
 * Optional component: import { CheckAvailability } from "@reltio/design/icons/sap/check-availability";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/check-availability.js";

export type CheckAvailabilityProps = Omit<IconProps, "name">;

/** Renders `<Icon name="check-availability" />` after this module is evaluated. */
export function CheckAvailability(props: CheckAvailabilityProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`check-availability`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
