/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `checklist` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/checklist";
 * Optional component: import { Checklist } from "@reltio/design/icons/sap/checklist";
 */
import "@ui5/webcomponents-icons/dist/checklist.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "checklist";

export type ChecklistProps = Omit<IconProps, "name">;

/** Renders `<Icon name="checklist" />` after this module is evaluated. */
export function Checklist(props: ChecklistProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
