/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `chevron-phase-2` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/chevron-phase-2";
 * Optional component: import { ChevronPhase2 } from "@reltio/design/icons/sap/chevron-phase-2";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/chevron-phase-2.js";

export type ChevronPhase2Props = Omit<IconProps, "name">;

/** Renders `<Icon name="chevron-phase-2" />` after this module is evaluated. */
export function ChevronPhase2(props: ChevronPhase2Props) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`chevron-phase-2`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
