/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `choropleth-chart` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/choropleth-chart";
 * Optional component: import { ChoroplethChart } from "@reltio/design/icons/sap/choropleth-chart";
 */
import "@ui5/webcomponents-icons/dist/choropleth-chart.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "choropleth-chart";

export type ChoroplethChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="choropleth-chart" />` after this module is evaluated. */
export function ChoroplethChart(props: ChoroplethChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
