/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `citizen-connect` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/citizen-connect";
 * Optional component: import { CitizenConnect } from "@reltio/design/icons/sap/citizen-connect";
 */
import "@ui5/webcomponents-icons/dist/citizen-connect.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "citizen-connect";

export type CitizenConnectProps = Omit<IconProps, "name">;

/** Renders `<Icon name="citizen-connect" />` after this module is evaluated. */
export function CitizenConnect(props: CitizenConnectProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
