/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `clear-all` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/clear-all";
 * Optional component: import { ClearAll } from "@reltio/design/icons/sap/clear-all";
 */
import "@ui5/webcomponents-icons/dist/clear-all.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "clear-all";

export type ClearAllProps = Omit<IconProps, "name">;

/** Renders `<Icon name="clear-all" />` after this module is evaluated. */
export function ClearAll(props: ClearAllProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
