/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `clear-filter` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/clear-filter";
 * Optional component: import { ClearFilter } from "@reltio/design/icons/sap/clear-filter";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/clear-filter.js";

export type ClearFilterProps = Omit<IconProps, "name">;

/** Renders `<Icon name="clear-filter" />` after this module is evaluated. */
export function ClearFilter(props: ClearFilterProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`clear-filter`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
