/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `clear-filter` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/clear-filter";
 * Optional component: import { ClearFilter } from "@reltio/design/icons/sap/clear-filter";
 */
import "@ui5/webcomponents-icons/dist/clear-filter.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "clear-filter";

export type ClearFilterProps = Omit<IconProps, "name">;

/** Renders `<Icon name="clear-filter" />` after this module is evaluated. */
export function ClearFilter(props: ClearFilterProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
