/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `clinical-task-tracker` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/clinical-task-tracker";
 * Optional component: import { ClinicalTaskTracker } from "@reltio/design/icons/sap/clinical-task-tracker";
 */
import "@ui5/webcomponents-icons/dist/clinical-task-tracker.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "clinical-task-tracker";

export type ClinicalTaskTrackerProps = Omit<IconProps, "name">;

/** Renders `<Icon name="clinical-task-tracker" />` after this module is evaluated. */
export function ClinicalTaskTracker(props: ClinicalTaskTrackerProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
