/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `clinical-tast-tracker` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/clinical-tast-tracker";
 * Optional component: import { ClinicalTastTracker } from "@reltio/design/icons/sap/clinical-tast-tracker";
 */
import "@ui5/webcomponents-icons/dist/clinical-tast-tracker.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "clinical-tast-tracker";

export type ClinicalTastTrackerProps = Omit<IconProps, "name">;

/** Renders `<Icon name="clinical-tast-tracker" />` after this module is evaluated. */
export function ClinicalTastTracker(props: ClinicalTastTrackerProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
