/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `cloud` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/cloud";
 * Optional component: import { Cloud } from "@reltio/design/icons/sap/cloud";
 */
import "@ui5/webcomponents-icons/dist/cloud.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "cloud";

export type CloudProps = Omit<IconProps, "name">;

/** Renders `<Icon name="cloud" />` after this module is evaluated. */
export function Cloud(props: CloudProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
