/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `cloud-check` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/cloud-check";
 * Optional component: import { CloudCheck } from "@reltio/design/icons/sap/cloud-check";
 */
import "@ui5/webcomponents-icons/dist/cloud-check.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "cloud-check";

export type CloudCheckProps = Omit<IconProps, "name">;

/** Renders `<Icon name="cloud-check" />` after this module is evaluated. */
export function CloudCheck(props: CloudCheckProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
