/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `collaborate` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/collaborate";
 * Optional component: import { Collaborate } from "@reltio/design/icons/sap/collaborate";
 */
import "@ui5/webcomponents-icons/dist/collaborate.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "collaborate";

export type CollaborateProps = Omit<IconProps, "name">;

/** Renders `<Icon name="collaborate" />` after this module is evaluated. */
export function Collaborate(props: CollaborateProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
