/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `collapse-all` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/collapse-all";
 * Optional component: import { CollapseAll } from "@reltio/design/icons/sap/collapse-all";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/collapse-all.js";

export type CollapseAllProps = Omit<IconProps, "name">;

/** Renders `<Icon name="collapse-all" />` after this module is evaluated. */
export function CollapseAll(props: CollapseAllProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`collapse-all`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
