/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `collapse-group` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/collapse-group";
 * Optional component: import { CollapseGroup } from "@reltio/design/icons/sap/collapse-group";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/collapse-group.js";

export type CollapseGroupProps = Omit<IconProps, "name">;

/** Renders `<Icon name="collapse-group" />` after this module is evaluated. */
export function CollapseGroup(props: CollapseGroupProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`collapse-group`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
