/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `collections-insight` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/collections-insight";
 * Optional component: import { CollectionsInsight } from "@reltio/design/icons/sap/collections-insight";
 */
import "@ui5/webcomponents-icons/dist/collections-insight.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "collections-insight";

export type CollectionsInsightProps = Omit<IconProps, "name">;

/** Renders `<Icon name="collections-insight" />` after this module is evaluated. */
export function CollectionsInsight(props: CollectionsInsightProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
