/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `color-fill` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/color-fill";
 * Optional component: import { ColorFill } from "@reltio/design/icons/sap/color-fill";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/color-fill.js";

export type ColorFillProps = Omit<IconProps, "name">;

/** Renders `<Icon name="color-fill" />` after this module is evaluated. */
export function ColorFill(props: ColorFillProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`color-fill`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
