/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `color-fill` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/color-fill";
 * Optional component: import { ColorFill } from "@reltio/design/icons/sap/color-fill";
 */
import "@ui5/webcomponents-icons/dist/color-fill.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "color-fill";

export type ColorFillProps = Omit<IconProps, "name">;

/** Renders `<Icon name="color-fill" />` after this module is evaluated. */
export function ColorFill(props: ColorFillProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
