/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `column-chart-dual-axis` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/column-chart-dual-axis";
 * Optional component: import { ColumnChartDualAxis } from "@reltio/design/icons/sap/column-chart-dual-axis";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/column-chart-dual-axis.js";

export type ColumnChartDualAxisProps = Omit<IconProps, "name">;

/** Renders `<Icon name="column-chart-dual-axis" />` after this module is evaluated. */
export function ColumnChartDualAxis(props: ColumnChartDualAxisProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`column-chart-dual-axis`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
