/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `comment` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/comment";
 * Optional component: import { Comment } from "@reltio/design/icons/sap/comment";
 */
import "@ui5/webcomponents-icons/dist/comment.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "comment";

export type CommentProps = Omit<IconProps, "name">;

/** Renders `<Icon name="comment" />` after this module is evaluated. */
export function Comment(props: CommentProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
