/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `command-line-interfaces` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/command-line-interfaces";
 * Optional component: import { CommandLineInterfaces } from "@reltio/design/icons/sap/command-line-interfaces";
 */
import "@ui5/webcomponents-icons/dist/command-line-interfaces.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "command-line-interfaces";

export type CommandLineInterfacesProps = Omit<IconProps, "name">;

/** Renders `<Icon name="command-line-interfaces" />` after this module is evaluated. */
export function CommandLineInterfaces(props: CommandLineInterfacesProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
