/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `complete` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/complete";
 * Optional component: import { Complete } from "@reltio/design/icons/sap/complete";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/complete.js";

export type CompleteProps = Omit<IconProps, "name">;

/** Renders `<Icon name="complete" />` after this module is evaluated. */
export function Complete(props: CompleteProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`complete`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
