/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `compare` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/compare";
 * Optional component: import { Compare } from "@reltio/design/icons/sap/compare";
 */
import "@ui5/webcomponents-icons/dist/compare.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "compare";

export type CompareProps = Omit<IconProps, "name">;

/** Renders `<Icon name="compare" />` after this module is evaluated. */
export function Compare(props: CompareProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
