/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `company-view` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/company-view";
 * Optional component: import { CompanyView } from "@reltio/design/icons/sap/company-view";
 */
import "@ui5/webcomponents-icons/dist/company-view.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "company-view";

export type CompanyViewProps = Omit<IconProps, "name">;

/** Renders `<Icon name="company-view" />` after this module is evaluated. */
export function CompanyView(props: CompanyViewProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
