/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `connected` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/connected";
 * Optional component: import { Connected } from "@reltio/design/icons/sap/connected";
 */
import "@ui5/webcomponents-icons/dist/connected.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "connected";

export type ConnectedProps = Omit<IconProps, "name">;

/** Renders `<Icon name="connected" />` after this module is evaluated. */
export function Connected(props: ConnectedProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
