/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `contacts` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/contacts";
 * Optional component: import { Contacts } from "@reltio/design/icons/sap/contacts";
 */
import "@ui5/webcomponents-icons/dist/contacts.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "contacts";

export type ContactsProps = Omit<IconProps, "name">;

/** Renders `<Icon name="contacts" />` after this module is evaluated. */
export function Contacts(props: ContactsProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
