/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `copy` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/copy";
 * Optional component: import { Copy } from "@reltio/design/icons/sap/copy";
 */
import "@ui5/webcomponents-icons/dist/copy.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "copy";

export type CopyProps = Omit<IconProps, "name">;

/** Renders `<Icon name="copy" />` after this module is evaluated. */
export function Copy(props: CopyProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
