/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `course-book` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/course-book";
 * Optional component: import { CourseBook } from "@reltio/design/icons/sap/course-book";
 */
import "@ui5/webcomponents-icons/dist/course-book.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "course-book";

export type CourseBookProps = Omit<IconProps, "name">;

/** Renders `<Icon name="course-book" />` after this module is evaluated. */
export function CourseBook(props: CourseBookProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
