/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `crm-service-manager` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/crm-service-manager";
 * Optional component: import { CrmServiceManager } from "@reltio/design/icons/sap/crm-service-manager";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/crm-service-manager.js";

export type CrmServiceManagerProps = Omit<IconProps, "name">;

/** Renders `<Icon name="crm-service-manager" />` after this module is evaluated. */
export function CrmServiceManager(props: CrmServiceManagerProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`crm-service-manager`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
