/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `crossed-line-chart` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/crossed-line-chart";
 * Optional component: import { CrossedLineChart } from "@reltio/design/icons/sap/crossed-line-chart";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/crossed-line-chart.js";

export type CrossedLineChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="crossed-line-chart" />` after this module is evaluated. */
export function CrossedLineChart(props: CrossedLineChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`crossed-line-chart`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
