/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `curriculum` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/curriculum";
 * Optional component: import { Curriculum } from "@reltio/design/icons/sap/curriculum";
 */
import "@ui5/webcomponents-icons/dist/curriculum.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "curriculum";

export type CurriculumProps = Omit<IconProps, "name">;

/** Renders `<Icon name="curriculum" />` after this module is evaluated. */
export function Curriculum(props: CurriculumProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
