/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `cursor-arrow` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/cursor-arrow";
 * Optional component: import { CursorArrow } from "@reltio/design/icons/sap/cursor-arrow";
 */
import "@ui5/webcomponents-icons/dist/cursor-arrow.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "cursor-arrow";

export type CursorArrowProps = Omit<IconProps, "name">;

/** Renders `<Icon name="cursor-arrow" />` after this module is evaluated. */
export function CursorArrow(props: CursorArrowProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
