/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `customize` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/customize";
 * Optional component: import { Customize } from "@reltio/design/icons/sap/customize";
 */
import "@ui5/webcomponents-icons/dist/customize.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "customize";

export type CustomizeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="customize" />` after this module is evaluated. */
export function Customize(props: CustomizeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
