/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `customer-history` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/customer-history";
 * Optional component: import { CustomerHistory } from "@reltio/design/icons/sap/customer-history";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/customer-history.js";

export type CustomerHistoryProps = Omit<IconProps, "name">;

/** Renders `<Icon name="customer-history" />` after this module is evaluated. */
export function CustomerHistory(props: CustomerHistoryProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`customer-history`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
