/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `customer-view` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/customer-view";
 * Optional component: import { CustomerView } from "@reltio/design/icons/sap/customer-view";
 */
import "@ui5/webcomponents-icons/dist/customer-view.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "customer-view";

export type CustomerViewProps = Omit<IconProps, "name">;

/** Renders `<Icon name="customer-view" />` after this module is evaluated. */
export function CustomerView(props: CustomerViewProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
