/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `customer-and-supplier` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/customer-and-supplier";
 * Optional component: import { CustomerAndSupplier } from "@reltio/design/icons/sap/customer-and-supplier";
 */
import "@ui5/webcomponents-icons/dist/customer-and-supplier.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "customer-and-supplier";

export type CustomerAndSupplierProps = Omit<IconProps, "name">;

/** Renders `<Icon name="customer-and-supplier" />` after this module is evaluated. */
export function CustomerAndSupplier(props: CustomerAndSupplierProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
