/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `customer-briefing` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/customer-briefing";
 * Optional component: import { CustomerBriefing } from "@reltio/design/icons/sap/customer-briefing";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/customer-briefing.js";

export type CustomerBriefingProps = Omit<IconProps, "name">;

/** Renders `<Icon name="customer-briefing" />` after this module is evaluated. */
export function CustomerBriefing(props: CustomerBriefingProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`customer-briefing`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
