/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `da` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/da";
 * Optional component: import { Da } from "@reltio/design/icons/sap/da";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/da.js";

export type DaProps = Omit<IconProps, "name">;

/** Renders `<Icon name="da" />` after this module is evaluated. */
export function Da(props: DaProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`da`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
