/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `dark-mode` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/dark-mode";
 * Optional component: import { DarkMode } from "@reltio/design/icons/sap/dark-mode";
 */
import "@ui5/webcomponents-icons/dist/dark-mode.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "dark-mode";

export type DarkModeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="dark-mode" />` after this module is evaluated. */
export function DarkMode(props: DarkModeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
