/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `database` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/database";
 * Optional component: import { Database } from "@reltio/design/icons/sap/database";
 */
import "@ui5/webcomponents-icons/dist/database.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "database";

export type DatabaseProps = Omit<IconProps, "name">;

/** Renders `<Icon name="database" />` after this module is evaluated. */
export function Database(props: DatabaseProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
