/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `decision` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/decision";
 * Optional component: import { Decision } from "@reltio/design/icons/sap/decision";
 */
import "@ui5/webcomponents-icons/dist/decision.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "decision";

export type DecisionProps = Omit<IconProps, "name">;

/** Renders `<Icon name="decision" />` after this module is evaluated. */
export function Decision(props: DecisionProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
