/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `desktop-mobile` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/desktop-mobile";
 * Optional component: import { DesktopMobile } from "@reltio/design/icons/sap/desktop-mobile";
 */
import "@ui5/webcomponents-icons/dist/desktop-mobile.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "desktop-mobile";

export type DesktopMobileProps = Omit<IconProps, "name">;

/** Renders `<Icon name="desktop-mobile" />` after this module is evaluated. */
export function DesktopMobile(props: DesktopMobileProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
