/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `detail-more` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/detail-more";
 * Optional component: import { DetailMore } from "@reltio/design/icons/sap/detail-more";
 */
import "@ui5/webcomponents-icons/dist/detail-more.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "detail-more";

export type DetailMoreProps = Omit<IconProps, "name">;

/** Renders `<Icon name="detail-more" />` after this module is evaluated. */
export function DetailMore(props: DetailMoreProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
