/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `detail-less` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/detail-less";
 * Optional component: import { DetailLess } from "@reltio/design/icons/sap/detail-less";
 */
import "@ui5/webcomponents-icons/dist/detail-less.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "detail-less";

export type DetailLessProps = Omit<IconProps, "name">;

/** Renders `<Icon name="detail-less" />` after this module is evaluated. */
export function DetailLess(props: DetailLessProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
