/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `developer-settings` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/developer-settings";
 * Optional component: import { DeveloperSettings } from "@reltio/design/icons/sap/developer-settings";
 */
import "@ui5/webcomponents-icons/dist/developer-settings.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "developer-settings";

export type DeveloperSettingsProps = Omit<IconProps, "name">;

/** Renders `<Icon name="developer-settings" />` after this module is evaluated. */
export function DeveloperSettings(props: DeveloperSettingsProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
