/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `display` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/display";
 * Optional component: import { Display } from "@reltio/design/icons/sap/display";
 */
import "@ui5/webcomponents-icons/dist/display.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "display";

export type DisplayProps = Omit<IconProps, "name">;

/** Renders `<Icon name="display" />` after this module is evaluated. */
export function Display(props: DisplayProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
