/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `display-more` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/display-more";
 * Optional component: import { DisplayMore } from "@reltio/design/icons/sap/display-more";
 */
import "@ui5/webcomponents-icons/dist/display-more.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "display-more";

export type DisplayMoreProps = Omit<IconProps, "name">;

/** Renders `<Icon name="display-more" />` after this module is evaluated. */
export function DisplayMore(props: DisplayMoreProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
