/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `doc-attachment` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/doc-attachment";
 * Optional component: import { DocAttachment } from "@reltio/design/icons/sap/doc-attachment";
 */
import "@ui5/webcomponents-icons/dist/doc-attachment.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "doc-attachment";

export type DocAttachmentProps = Omit<IconProps, "name">;

/** Renders `<Icon name="doc-attachment" />` after this module is evaluated. */
export function DocAttachment(props: DocAttachmentProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
