/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `document-text` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/document-text";
 * Optional component: import { DocumentText } from "@reltio/design/icons/sap/document-text";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/document-text.js";

export type DocumentTextProps = Omit<IconProps, "name">;

/** Renders `<Icon name="document-text" />` after this module is evaluated. */
export function DocumentText(props: DocumentTextProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`document-text`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
