/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `documents` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/documents";
 * Optional component: import { Documents } from "@reltio/design/icons/sap/documents";
 */
import "@ui5/webcomponents-icons/dist/documents.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "documents";

export type DocumentsProps = Omit<IconProps, "name">;

/** Renders `<Icon name="documents" />` after this module is evaluated. */
export function Documents(props: DocumentsProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
