/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `document` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/document";
 * Optional component: import { Document } from "@reltio/design/icons/sap/document";
 */
import "@ui5/webcomponents-icons/dist/document.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "document";

export type DocumentProps = Omit<IconProps, "name">;

/** Renders `<Icon name="document" />` after this module is evaluated. */
export function Document(props: DocumentProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
