/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `down` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/down";
 * Optional component: import { Down } from "@reltio/design/icons/sap/down";
 */
import "@ui5/webcomponents-icons/dist/down.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "down";

export type DownProps = Omit<IconProps, "name">;

/** Renders `<Icon name="down" />` after this module is evaluated. */
export function Down(props: DownProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
