/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `drop-down-list` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/drop-down-list";
 * Optional component: import { DropDownList } from "@reltio/design/icons/sap/drop-down-list";
 */
import "@ui5/webcomponents-icons/dist/drop-down-list.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "drop-down-list";

export type DropDownListProps = Omit<IconProps, "name">;

/** Renders `<Icon name="drop-down-list" />` after this module is evaluated. */
export function DropDownList(props: DropDownListProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
