/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `dropdown` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/dropdown";
 * Optional component: import { Dropdown } from "@reltio/design/icons/sap/dropdown";
 */
import "@ui5/webcomponents-icons/dist/dropdown.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "dropdown";

export type DropdownProps = Omit<IconProps, "name">;

/** Renders `<Icon name="dropdown" />` after this module is evaluated. */
export function Dropdown(props: DropdownProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
