/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `dropdown` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/dropdown";
 * Optional component: import { Dropdown } from "@reltio/design/icons/sap/dropdown";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/dropdown.js";

export type DropdownProps = Omit<IconProps, "name">;

/** Renders `<Icon name="dropdown" />` after this module is evaluated. */
export function Dropdown(props: DropdownProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`dropdown`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
