/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `duplicate` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/duplicate";
 * Optional component: import { Duplicate } from "@reltio/design/icons/sap/duplicate";
 */
import "@ui5/webcomponents-icons/dist/duplicate.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "duplicate";

export type DuplicateProps = Omit<IconProps, "name">;

/** Renders `<Icon name="duplicate" />` after this module is evaluated. */
export function Duplicate(props: DuplicateProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
