/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `e-care` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/e-care";
 * Optional component: import { ECare } from "@reltio/design/icons/sap/e-care";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/e-care.js";

export type ECareProps = Omit<IconProps, "name">;

/** Renders `<Icon name="e-care" />` after this module is evaluated. */
export function ECare(props: ECareProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`e-care`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
