/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `e-learning` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/e-learning";
 * Optional component: import { ELearning } from "@reltio/design/icons/sap/e-learning";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/e-learning.js";

export type ELearningProps = Omit<IconProps, "name">;

/** Renders `<Icon name="e-learning" />` after this module is evaluated. */
export function ELearning(props: ELearningProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`e-learning`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
