/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `edit-outside` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/edit-outside";
 * Optional component: import { EditOutside } from "@reltio/design/icons/sap/edit-outside";
 */
import "@ui5/webcomponents-icons/dist/edit-outside.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "edit-outside";

export type EditOutsideProps = Omit<IconProps, "name">;

/** Renders `<Icon name="edit-outside" />` after this module is evaluated. */
export function EditOutside(props: EditOutsideProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
