/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `electronic-medical-record` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/electronic-medical-record";
 * Optional component: import { ElectronicMedicalRecord } from "@reltio/design/icons/sap/electronic-medical-record";
 */
import "@ui5/webcomponents-icons/dist/electronic-medical-record.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "electronic-medical-record";

export type ElectronicMedicalRecordProps = Omit<IconProps, "name">;

/** Renders `<Icon name="electronic-medical-record" />` after this module is evaluated. */
export function ElectronicMedicalRecord(props: ElectronicMedicalRecordProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
