/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `email-read` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/email-read";
 * Optional component: import { EmailRead } from "@reltio/design/icons/sap/email-read";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/email-read.js";

export type EmailReadProps = Omit<IconProps, "name">;

/** Renders `<Icon name="email-read" />` after this module is evaluated. */
export function EmailRead(props: EmailReadProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`email-read`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
