/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `email` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/email";
 * Optional component: import { Email } from "@reltio/design/icons/sap/email";
 */
import "@ui5/webcomponents-icons/dist/email.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "email";

export type EmailProps = Omit<IconProps, "name">;

/** Renders `<Icon name="email" />` after this module is evaluated. */
export function Email(props: EmailProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
