/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `email-read` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/email-read";
 * Optional component: import { EmailRead } from "@reltio/design/icons/sap/email-read";
 */
import "@ui5/webcomponents-icons/dist/email-read.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "email-read";

export type EmailReadProps = Omit<IconProps, "name">;

/** Renders `<Icon name="email-read" />` after this module is evaluated. */
export function EmailRead(props: EmailReadProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
