/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `employee-pane` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/employee-pane";
 * Optional component: import { EmployeePane } from "@reltio/design/icons/sap/employee-pane";
 */
import "@ui5/webcomponents-icons/dist/employee-pane.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "employee-pane";

export type EmployeePaneProps = Omit<IconProps, "name">;

/** Renders `<Icon name="employee-pane" />` after this module is evaluated. */
export function EmployeePane(props: EmployeePaneProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
