/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `employee-approvals` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/employee-approvals";
 * Optional component: import { EmployeeApprovals } from "@reltio/design/icons/sap/employee-approvals";
 */
import "@ui5/webcomponents-icons/dist/employee-approvals.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "employee-approvals";

export type EmployeeApprovalsProps = Omit<IconProps, "name">;

/** Renders `<Icon name="employee-approvals" />` after this module is evaluated. */
export function EmployeeApprovals(props: EmployeeApprovalsProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
