/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `employee-rejections` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/employee-rejections";
 * Optional component: import { EmployeeRejections } from "@reltio/design/icons/sap/employee-rejections";
 */
import "@ui5/webcomponents-icons/dist/employee-rejections.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "employee-rejections";

export type EmployeeRejectionsProps = Omit<IconProps, "name">;

/** Renders `<Icon name="employee-rejections" />` after this module is evaluated. */
export function EmployeeRejections(props: EmployeeRejectionsProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
