/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `employee-lookup` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/employee-lookup";
 * Optional component: import { EmployeeLookup } from "@reltio/design/icons/sap/employee-lookup";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/employee-lookup.js";

export type EmployeeLookupProps = Omit<IconProps, "name">;

/** Renders `<Icon name="employee-lookup" />` after this module is evaluated. */
export function EmployeeLookup(props: EmployeeLookupProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`employee-lookup`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
