/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `employee-lookup` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/employee-lookup";
 * Optional component: import { EmployeeLookup } from "@reltio/design/icons/sap/employee-lookup";
 */
import "@ui5/webcomponents-icons/dist/employee-lookup.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "employee-lookup";

export type EmployeeLookupProps = Omit<IconProps, "name">;

/** Renders `<Icon name="employee-lookup" />` after this module is evaluated. */
export function EmployeeLookup(props: EmployeeLookupProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
