/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `enablement` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/enablement";
 * Optional component: import { Enablement } from "@reltio/design/icons/sap/enablement";
 */
import "@ui5/webcomponents-icons/dist/enablement.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "enablement";

export type EnablementProps = Omit<IconProps, "name">;

/** Renders `<Icon name="enablement" />` after this module is evaluated. */
export function Enablement(props: EnablementProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
