/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `endoscopy` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/endoscopy";
 * Optional component: import { Endoscopy } from "@reltio/design/icons/sap/endoscopy";
 */
import "@ui5/webcomponents-icons/dist/endoscopy.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "endoscopy";

export type EndoscopyProps = Omit<IconProps, "name">;

/** Renders `<Icon name="endoscopy" />` after this module is evaluated. */
export function Endoscopy(props: EndoscopyProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
