/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `enter-more` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/enter-more";
 * Optional component: import { EnterMore } from "@reltio/design/icons/sap/enter-more";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/enter-more.js";

export type EnterMoreProps = Omit<IconProps, "name">;

/** Renders `<Icon name="enter-more" />` after this module is evaluated. */
export function EnterMore(props: EnterMoreProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`enter-more`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
