/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `exit-full-screen` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/exit-full-screen";
 * Optional component: import { ExitFullScreen } from "@reltio/design/icons/sap/exit-full-screen";
 */
import "@ui5/webcomponents-icons/dist/exit-full-screen.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "exit-full-screen";

export type ExitFullScreenProps = Omit<IconProps, "name">;

/** Renders `<Icon name="exit-full-screen" />` after this module is evaluated. */
export function ExitFullScreen(props: ExitFullScreenProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
