/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `expand` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/expand";
 * Optional component: import { Expand } from "@reltio/design/icons/sap/expand";
 */
import "@ui5/webcomponents-icons/dist/expand.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "expand";

export type ExpandProps = Omit<IconProps, "name">;

/** Renders `<Icon name="expand" />` after this module is evaluated. */
export function Expand(props: ExpandProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
