/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `expand-group` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/expand-group";
 * Optional component: import { ExpandGroup } from "@reltio/design/icons/sap/expand-group";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/expand-group.js";

export type ExpandGroupProps = Omit<IconProps, "name">;

/** Renders `<Icon name="expand-group" />` after this module is evaluated. */
export function ExpandGroup(props: ExpandGroupProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`expand-group`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
