/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `expand-group` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/expand-group";
 * Optional component: import { ExpandGroup } from "@reltio/design/icons/sap/expand-group";
 */
import "@ui5/webcomponents-icons/dist/expand-group.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "expand-group";

export type ExpandGroupProps = Omit<IconProps, "name">;

/** Renders `<Icon name="expand-group" />` after this module is evaluated. */
export function ExpandGroup(props: ExpandGroupProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
