/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `expand-all` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/expand-all";
 * Optional component: import { ExpandAll } from "@reltio/design/icons/sap/expand-all";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/expand-all.js";

export type ExpandAllProps = Omit<IconProps, "name">;

/** Renders `<Icon name="expand-all" />` after this module is evaluated. */
export function ExpandAll(props: ExpandAllProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`expand-all`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
