/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `expand-all` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/expand-all";
 * Optional component: import { ExpandAll } from "@reltio/design/icons/sap/expand-all";
 */
import "@ui5/webcomponents-icons/dist/expand-all.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "expand-all";

export type ExpandAllProps = Omit<IconProps, "name">;

/** Renders `<Icon name="expand-all" />` after this module is evaluated. */
export function ExpandAll(props: ExpandAllProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
