/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `expense-report` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/expense-report";
 * Optional component: import { ExpenseReport } from "@reltio/design/icons/sap/expense-report";
 */
import "@ui5/webcomponents-icons/dist/expense-report.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "expense-report";

export type ExpenseReportProps = Omit<IconProps, "name">;

/** Renders `<Icon name="expense-report" />` after this module is evaluated. */
export function ExpenseReport(props: ExpenseReportProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
