/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `factory` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/factory";
 * Optional component: import { Factory } from "@reltio/design/icons/sap/factory";
 */
import "@ui5/webcomponents-icons/dist/factory.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "factory";

export type FactoryProps = Omit<IconProps, "name">;

/** Renders `<Icon name="factory" />` after this module is evaluated. */
export function Factory(props: FactoryProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
