/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `fallback` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/fallback";
 * Optional component: import { Fallback } from "@reltio/design/icons/sap/fallback";
 */
import "@ui5/webcomponents-icons/dist/fallback.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "fallback";

export type FallbackProps = Omit<IconProps, "name">;

/** Renders `<Icon name="fallback" />` after this module is evaluated. */
export function Fallback(props: FallbackProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
