/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `favorite` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/favorite";
 * Optional component: import { Favorite } from "@reltio/design/icons/sap/favorite";
 */
import "@ui5/webcomponents-icons/dist/favorite.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "favorite";

export type FavoriteProps = Omit<IconProps, "name">;

/** Renders `<Icon name="favorite" />` after this module is evaluated. */
export function Favorite(props: FavoriteProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
