/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `feed` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/feed";
 * Optional component: import { Feed } from "@reltio/design/icons/sap/feed";
 */
import "@ui5/webcomponents-icons/dist/feed.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "feed";

export type FeedProps = Omit<IconProps, "name">;

/** Renders `<Icon name="feed" />` after this module is evaluated. */
export function Feed(props: FeedProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
