/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `feeder-arrow` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/feeder-arrow";
 * Optional component: import { FeederArrow } from "@reltio/design/icons/sap/feeder-arrow";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/feeder-arrow.js";

export type FeederArrowProps = Omit<IconProps, "name">;

/** Renders `<Icon name="feeder-arrow" />` after this module is evaluated. */
export function FeederArrow(props: FeederArrowProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`feeder-arrow`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
