/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `flag` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/flag";
 * Optional component: import { Flag } from "@reltio/design/icons/sap/flag";
 */
import "@ui5/webcomponents-icons/dist/flag.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "flag";

export type FlagProps = Omit<IconProps, "name">;

/** Renders `<Icon name="flag" />` after this module is evaluated. */
export function Flag(props: FlagProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
