/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `flag` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/flag";
 * Optional component: import { Flag } from "@reltio/design/icons/sap/flag";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/flag.js";

export type FlagProps = Omit<IconProps, "name">;

/** Renders `<Icon name="flag" />` after this module is evaluated. */
export function Flag(props: FlagProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`flag`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
