/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `folder-2` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/folder-2";
 * Optional component: import { Folder2 } from "@reltio/design/icons/sap/folder-2";
 */
import "@ui5/webcomponents-icons/dist/folder-2.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "folder-2";

export type Folder2Props = Omit<IconProps, "name">;

/** Renders `<Icon name="folder-2" />` after this module is evaluated. */
export function Folder2(props: Folder2Props) {
	return <Icon name={ICON_NAME} {...props} />;
}
