/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `folder-blank` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/folder-blank";
 * Optional component: import { FolderBlank } from "@reltio/design/icons/sap/folder-blank";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/folder-blank.js";

export type FolderBlankProps = Omit<IconProps, "name">;

/** Renders `<Icon name="folder-blank" />` after this module is evaluated. */
export function FolderBlank(props: FolderBlankProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`folder-blank`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
