/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `form` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/form";
 * Optional component: import { Form } from "@reltio/design/icons/sap/form";
 */
import "@ui5/webcomponents-icons/dist/form.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "form";

export type FormProps = Omit<IconProps, "name">;

/** Renders `<Icon name="form" />` after this module is evaluated. */
export function Form(props: FormProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
