/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `forward` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/forward";
 * Optional component: import { Forward } from "@reltio/design/icons/sap/forward";
 */
import "@ui5/webcomponents-icons/dist/forward.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "forward";

export type ForwardProps = Omit<IconProps, "name">;

/** Renders `<Icon name="forward" />` after this module is evaluated. */
export function Forward(props: ForwardProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
