/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `fridge` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/fridge";
 * Optional component: import { Fridge } from "@reltio/design/icons/sap/fridge";
 */
import "@ui5/webcomponents-icons/dist/fridge.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "fridge";

export type FridgeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="fridge" />` after this module is evaluated. */
export function Fridge(props: FridgeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
