/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `full-stacked-column-chart` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/full-stacked-column-chart";
 * Optional component: import { FullStackedColumnChart } from "@reltio/design/icons/sap/full-stacked-column-chart";
 */
import "@ui5/webcomponents-icons/dist/full-stacked-column-chart.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "full-stacked-column-chart";

export type FullStackedColumnChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="full-stacked-column-chart" />` after this module is evaluated. */
export function FullStackedColumnChart(props: FullStackedColumnChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
