/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `functional-location` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/functional-location";
 * Optional component: import { FunctionalLocation } from "@reltio/design/icons/sap/functional-location";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/functional-location.js";

export type FunctionalLocationProps = Omit<IconProps, "name">;

/** Renders `<Icon name="functional-location" />` after this module is evaluated. */
export function FunctionalLocation(props: FunctionalLocationProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`functional-location`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
