/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `future` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/future";
 * Optional component: import { Future } from "@reltio/design/icons/sap/future";
 */
import "@ui5/webcomponents-icons/dist/future.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "future";

export type FutureProps = Omit<IconProps, "name">;

/** Renders `<Icon name="future" />` after this module is evaluated. */
export function Future(props: FutureProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
