/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `gantt-bars` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/gantt-bars";
 * Optional component: import { GanttBars } from "@reltio/design/icons/sap/gantt-bars";
 */
import "@ui5/webcomponents-icons/dist/gantt-bars.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "gantt-bars";

export type GanttBarsProps = Omit<IconProps, "name">;

/** Renders `<Icon name="gantt-bars" />` after this module is evaluated. */
export function GanttBars(props: GanttBarsProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
