/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `gender-male-and-female` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/gender-male-and-female";
 * Optional component: import { GenderMaleAndFemale } from "@reltio/design/icons/sap/gender-male-and-female";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/gender-male-and-female.js";

export type GenderMaleAndFemaleProps = Omit<IconProps, "name">;

/** Renders `<Icon name="gender-male-and-female" />` after this module is evaluated. */
export function GenderMaleAndFemale(props: GenderMaleAndFemaleProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`gender-male-and-female`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
