/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `general-leave-request` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/general-leave-request";
 * Optional component: import { GeneralLeaveRequest } from "@reltio/design/icons/sap/general-leave-request";
 */
import "@ui5/webcomponents-icons/dist/general-leave-request.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "general-leave-request";

export type GeneralLeaveRequestProps = Omit<IconProps, "name">;

/** Renders `<Icon name="general-leave-request" />` after this module is evaluated. */
export function GeneralLeaveRequest(props: GeneralLeaveRequestProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
