/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `general-leave-request` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/general-leave-request";
 * Optional component: import { GeneralLeaveRequest } from "@reltio/design/icons/sap/general-leave-request";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/general-leave-request.js";

export type GeneralLeaveRequestProps = Omit<IconProps, "name">;

/** Renders `<Icon name="general-leave-request" />` after this module is evaluated. */
export function GeneralLeaveRequest(props: GeneralLeaveRequestProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`general-leave-request`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
