/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `goalseek` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/goalseek";
 * Optional component: import { Goalseek } from "@reltio/design/icons/sap/goalseek";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/goalseek.js";

export type GoalseekProps = Omit<IconProps, "name">;

/** Renders `<Icon name="goalseek" />` after this module is evaluated. */
export function Goalseek(props: GoalseekProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`goalseek`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
