/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `group-2` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/group-2";
 * Optional component: import { Group2 } from "@reltio/design/icons/sap/group-2";
 */
import "@ui5/webcomponents-icons/dist/group-2.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "group-2";

export type Group2Props = Omit<IconProps, "name">;

/** Renders `<Icon name="group-2" />` after this module is evaluated. */
export function Group2(props: Group2Props) {
	return <Icon name={ICON_NAME} {...props} />;
}
