/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `heading1` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/heading1";
 * Optional component: import { Heading1 } from "@reltio/design/icons/sap/heading1";
 */
import "@ui5/webcomponents-icons/dist/heading1.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "heading1";

export type Heading1Props = Omit<IconProps, "name">;

/** Renders `<Icon name="heading1" />` after this module is evaluated. */
export function Heading1(props: Heading1Props) {
	return <Icon name={ICON_NAME} {...props} />;
}
