/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `heading2` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/heading2";
 * Optional component: import { Heading2 } from "@reltio/design/icons/sap/heading2";
 */
import "@ui5/webcomponents-icons/dist/heading2.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "heading2";

export type Heading2Props = Omit<IconProps, "name">;

/** Renders `<Icon name="heading2" />` after this module is evaluated. */
export function Heading2(props: Heading2Props) {
	return <Icon name={ICON_NAME} {...props} />;
}
