/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `heart-2` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/heart-2";
 * Optional component: import { Heart2 } from "@reltio/design/icons/sap/heart-2";
 */
import "@ui5/webcomponents-icons/dist/heart-2.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "heart-2";

export type Heart2Props = Omit<IconProps, "name">;

/** Renders `<Icon name="heart-2" />` after this module is evaluated. */
export function Heart2(props: Heart2Props) {
	return <Icon name={ICON_NAME} {...props} />;
}
