/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `hide` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/hide";
 * Optional component: import { Hide } from "@reltio/design/icons/sap/hide";
 */
import "@ui5/webcomponents-icons/dist/hide.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "hide";

export type HideProps = Omit<IconProps, "name">;

/** Renders `<Icon name="hide" />` after this module is evaluated. */
export function Hide(props: HideProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
