/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `hint` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/hint";
 * Optional component: import { Hint } from "@reltio/design/icons/sap/hint";
 */
import "@ui5/webcomponents-icons/dist/hint.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "hint";

export type HintProps = Omit<IconProps, "name">;

/** Renders `<Icon name="hint" />` after this module is evaluated. */
export function Hint(props: HintProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
