/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `home` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/home";
 * Optional component: import { Home } from "@reltio/design/icons/sap/home";
 */
import "@ui5/webcomponents-icons/dist/home.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "home";

export type HomeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="home" />` after this module is evaluated. */
export function Home(props: HomeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
