/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `horizontal-waterfall-chart` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/horizontal-waterfall-chart";
 * Optional component: import { HorizontalWaterfallChart } from "@reltio/design/icons/sap/horizontal-waterfall-chart";
 */
import "@ui5/webcomponents-icons/dist/horizontal-waterfall-chart.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "horizontal-waterfall-chart";

export type HorizontalWaterfallChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="horizontal-waterfall-chart" />` after this module is evaluated. */
export function HorizontalWaterfallChart(props: HorizontalWaterfallChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
