/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `horizontal-stacked-chart` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/horizontal-stacked-chart";
 * Optional component: import { HorizontalStackedChart } from "@reltio/design/icons/sap/horizontal-stacked-chart";
 */
import "@ui5/webcomponents-icons/dist/horizontal-stacked-chart.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "horizontal-stacked-chart";

export type HorizontalStackedChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="horizontal-stacked-chart" />` after this module is evaluated. */
export function HorizontalStackedChart(props: HorizontalStackedChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
