/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `horizontal-combination-chart` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/horizontal-combination-chart";
 * Optional component: import { HorizontalCombinationChart } from "@reltio/design/icons/sap/horizontal-combination-chart";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/horizontal-combination-chart.js";

export type HorizontalCombinationChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="horizontal-combination-chart" />` after this module is evaluated. */
export function HorizontalCombinationChart(
	props: HorizontalCombinationChartProps,
) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`horizontal-combination-chart`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
