/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `horizontal-grip` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/horizontal-grip";
 * Optional component: import { HorizontalGrip } from "@reltio/design/icons/sap/horizontal-grip";
 */
import "@ui5/webcomponents-icons/dist/horizontal-grip.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "horizontal-grip";

export type HorizontalGripProps = Omit<IconProps, "name">;

/** Renders `<Icon name="horizontal-grip" />` after this module is evaluated. */
export function HorizontalGrip(props: HorizontalGripProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
