/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `hr-approval` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/hr-approval";
 * Optional component: import { HrApproval } from "@reltio/design/icons/sap/hr-approval";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/hr-approval.js";

export type HrApprovalProps = Omit<IconProps, "name">;

/** Renders `<Icon name="hr-approval" />` after this module is evaluated. */
export function HrApproval(props: HrApprovalProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`hr-approval`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
