/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `idea-wall` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/idea-wall";
 * Optional component: import { IdeaWall } from "@reltio/design/icons/sap/idea-wall";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/idea-wall.js";

export type IdeaWallProps = Omit<IconProps, "name">;

/** Renders `<Icon name="idea-wall" />` after this module is evaluated. */
export function IdeaWall(props: IdeaWallProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`idea-wall`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
