/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `image-viewer` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/image-viewer";
 * Optional component: import { ImageViewer } from "@reltio/design/icons/sap/image-viewer";
 */
import "@ui5/webcomponents-icons/dist/image-viewer.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "image-viewer";

export type ImageViewerProps = Omit<IconProps, "name">;

/** Renders `<Icon name="image-viewer" />` after this module is evaluated. */
export function ImageViewer(props: ImageViewerProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
