/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `in-progress-2` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/in-progress-2";
 * Optional component: import { InProgress2 } from "@reltio/design/icons/sap/in-progress-2";
 */
import "@ui5/webcomponents-icons/dist/in-progress-2.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "in-progress-2";

export type InProgress2Props = Omit<IconProps, "name">;

/** Renders `<Icon name="in-progress-2" />` after this module is evaluated. */
export function InProgress2(props: InProgress2Props) {
	return <Icon name={ICON_NAME} {...props} />;
}
