/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `incident` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/incident";
 * Optional component: import { Incident } from "@reltio/design/icons/sap/incident";
 */
import "@ui5/webcomponents-icons/dist/incident.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "incident";

export type IncidentProps = Omit<IconProps, "name">;

/** Renders `<Icon name="incident" />` after this module is evaluated. */
export function Incident(props: IncidentProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
