/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `incoming-call` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/incoming-call";
 * Optional component: import { IncomingCall } from "@reltio/design/icons/sap/incoming-call";
 */
import "@ui5/webcomponents-icons/dist/incoming-call.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "incoming-call";

export type IncomingCallProps = Omit<IconProps, "name">;

/** Renders `<Icon name="incoming-call" />` after this module is evaluated. */
export function IncomingCall(props: IncomingCallProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
