/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `indent` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/indent";
 * Optional component: import { Indent } from "@reltio/design/icons/sap/indent";
 */
import "@ui5/webcomponents-icons/dist/indent.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "indent";

export type IndentProps = Omit<IconProps, "name">;

/** Renders `<Icon name="indent" />` after this module is evaluated. */
export function Indent(props: IndentProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
