/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `inspection` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/inspection";
 * Optional component: import { Inspection } from "@reltio/design/icons/sap/inspection";
 */
import "@ui5/webcomponents-icons/dist/inspection.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "inspection";

export type InspectionProps = Omit<IconProps, "name">;

/** Renders `<Icon name="inspection" />` after this module is evaluated. */
export function Inspection(props: InspectionProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
