/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `inspect` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/inspect";
 * Optional component: import { Inspect } from "@reltio/design/icons/sap/inspect";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/inspect.js";

export type InspectProps = Omit<IconProps, "name">;

/** Renders `<Icon name="inspect" />` after this module is evaluated. */
export function Inspect(props: InspectProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`inspect`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
