/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `insurance-life` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/insurance-life";
 * Optional component: import { InsuranceLife } from "@reltio/design/icons/sap/insurance-life";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/insurance-life.js";

export type InsuranceLifeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="insurance-life" />` after this module is evaluated. */
export function InsuranceLife(props: InsuranceLifeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`insurance-life`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
