/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `insurance-life` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/insurance-life";
 * Optional component: import { InsuranceLife } from "@reltio/design/icons/sap/insurance-life";
 */
import "@ui5/webcomponents-icons/dist/insurance-life.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "insurance-life";

export type InsuranceLifeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="insurance-life" />` after this module is evaluated. */
export function InsuranceLife(props: InsuranceLifeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
