/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `inventory` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/inventory";
 * Optional component: import { Inventory } from "@reltio/design/icons/sap/inventory";
 */
import "@ui5/webcomponents-icons/dist/inventory.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "inventory";

export type InventoryProps = Omit<IconProps, "name">;

/** Renders `<Icon name="inventory" />` after this module is evaluated. */
export function Inventory(props: InventoryProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
