/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `iphone-2` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/iphone-2";
 * Optional component: import { Iphone2 } from "@reltio/design/icons/sap/iphone-2";
 */
import "@ui5/webcomponents-icons/dist/iphone-2.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "iphone-2";

export type Iphone2Props = Omit<IconProps, "name">;

/** Renders `<Icon name="iphone-2" />` after this module is evaluated. */
export function Iphone2(props: Iphone2Props) {
	return <Icon name={ICON_NAME} {...props} />;
}
