/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `it-host` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/it-host";
 * Optional component: import { ItHost } from "@reltio/design/icons/sap/it-host";
 */
import "@ui5/webcomponents-icons/dist/it-host.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "it-host";

export type ItHostProps = Omit<IconProps, "name">;

/** Renders `<Icon name="it-host" />` after this module is evaluated. */
export function ItHost(props: ItHostProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
