/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `italic-text` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/italic-text";
 * Optional component: import { ItalicText } from "@reltio/design/icons/sap/italic-text";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/italic-text.js";

export type ItalicTextProps = Omit<IconProps, "name">;

/** Renders `<Icon name="italic-text" />` after this module is evaluated. */
export function ItalicText(props: ItalicTextProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`italic-text`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
