/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `journey-depart` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/journey-depart";
 * Optional component: import { JourneyDepart } from "@reltio/design/icons/sap/journey-depart";
 */
import "@ui5/webcomponents-icons/dist/journey-depart.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "journey-depart";

export type JourneyDepartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="journey-depart" />` after this module is evaluated. */
export function JourneyDepart(props: JourneyDepartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
