/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `journey-change` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/journey-change";
 * Optional component: import { JourneyChange } from "@reltio/design/icons/sap/journey-change";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/journey-change.js";

export type JourneyChangeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="journey-change" />` after this module is evaluated. */
export function JourneyChange(props: JourneyChangeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`journey-change`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
