/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `key-user-settings` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/key-user-settings";
 * Optional component: import { KeyUserSettings } from "@reltio/design/icons/sap/key-user-settings";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/key-user-settings.js";

export type KeyUserSettingsProps = Omit<IconProps, "name">;

/** Renders `<Icon name="key-user-settings" />` after this module is evaluated. */
export function KeyUserSettings(props: KeyUserSettingsProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`key-user-settings`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
