/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `key-user-settings` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/key-user-settings";
 * Optional component: import { KeyUserSettings } from "@reltio/design/icons/sap/key-user-settings";
 */
import "@ui5/webcomponents-icons/dist/key-user-settings.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "key-user-settings";

export type KeyUserSettingsProps = Omit<IconProps, "name">;

/** Renders `<Icon name="key-user-settings" />` after this module is evaluated. */
export function KeyUserSettings(props: KeyUserSettingsProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
