/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `key` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/key";
 * Optional component: import { Key } from "@reltio/design/icons/sap/key";
 */
import "@ui5/webcomponents-icons/dist/key.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "key";

export type KeyProps = Omit<IconProps, "name">;

/** Renders `<Icon name="key" />` after this module is evaluated. */
export function Key(props: KeyProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
