/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `keyboard-and-mouse` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/keyboard-and-mouse";
 * Optional component: import { KeyboardAndMouse } from "@reltio/design/icons/sap/keyboard-and-mouse";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/keyboard-and-mouse.js";

export type KeyboardAndMouseProps = Omit<IconProps, "name">;

/** Renders `<Icon name="keyboard-and-mouse" />` after this module is evaluated. */
export function KeyboardAndMouse(props: KeyboardAndMouseProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`keyboard-and-mouse`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
