/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `kpi-corporate-performance` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/kpi-corporate-performance";
 * Optional component: import { KpiCorporatePerformance } from "@reltio/design/icons/sap/kpi-corporate-performance";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/kpi-corporate-performance.js";

export type KpiCorporatePerformanceProps = Omit<IconProps, "name">;

/** Renders `<Icon name="kpi-corporate-performance" />` after this module is evaluated. */
export function KpiCorporatePerformance(props: KpiCorporatePerformanceProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`kpi-corporate-performance`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
