/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `lab` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/lab";
 * Optional component: import { Lab } from "@reltio/design/icons/sap/lab";
 */
import "@ui5/webcomponents-icons/dist/lab.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "lab";

export type LabProps = Omit<IconProps, "name">;

/** Renders `<Icon name="lab" />` after this module is evaluated. */
export function Lab(props: LabProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
