/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `lateness` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/lateness";
 * Optional component: import { Lateness } from "@reltio/design/icons/sap/lateness";
 */
import "@ui5/webcomponents-icons/dist/lateness.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "lateness";

export type LatenessProps = Omit<IconProps, "name">;

/** Renders `<Icon name="lateness" />` after this module is evaluated. */
export function Lateness(props: LatenessProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
