/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `leads` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/leads";
 * Optional component: import { Leads } from "@reltio/design/icons/sap/leads";
 */
import "@ui5/webcomponents-icons/dist/leads.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "leads";

export type LeadsProps = Omit<IconProps, "name">;

/** Renders `<Icon name="leads" />` after this module is evaluated. */
export function Leads(props: LeadsProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
