/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `learning-assistant` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/learning-assistant";
 * Optional component: import { LearningAssistant } from "@reltio/design/icons/sap/learning-assistant";
 */
import "@ui5/webcomponents-icons/dist/learning-assistant.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "learning-assistant";

export type LearningAssistantProps = Omit<IconProps, "name">;

/** Renders `<Icon name="learning-assistant" />` after this module is evaluated. */
export function LearningAssistant(props: LearningAssistantProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
