/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `less` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/less";
 * Optional component: import { Less } from "@reltio/design/icons/sap/less";
 */
import "@ui5/webcomponents-icons/dist/less.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "less";

export type LessProps = Omit<IconProps, "name">;

/** Renders `<Icon name="less" />` after this module is evaluated. */
export function Less(props: LessProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
