/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `letter` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/letter";
 * Optional component: import { Letter } from "@reltio/design/icons/sap/letter";
 */
import "@ui5/webcomponents-icons/dist/letter.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "letter";

export type LetterProps = Omit<IconProps, "name">;

/** Renders `<Icon name="letter" />` after this module is evaluated. */
export function Letter(props: LetterProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
