/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `light-mode` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/light-mode";
 * Optional component: import { LightMode } from "@reltio/design/icons/sap/light-mode";
 */
import "@ui5/webcomponents-icons/dist/light-mode.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "light-mode";

export type LightModeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="light-mode" />` after this module is evaluated. */
export function LightMode(props: LightModeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
