/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `line-chart-time-axis` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/line-chart-time-axis";
 * Optional component: import { LineChartTimeAxis } from "@reltio/design/icons/sap/line-chart-time-axis";
 */
import "@ui5/webcomponents-icons/dist/line-chart-time-axis.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "line-chart-time-axis";

export type LineChartTimeAxisProps = Omit<IconProps, "name">;

/** Renders `<Icon name="line-chart-time-axis" />` after this module is evaluated. */
export function LineChartTimeAxis(props: LineChartTimeAxisProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
