/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `line-charts` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/line-charts";
 * Optional component: import { LineCharts } from "@reltio/design/icons/sap/line-charts";
 */
import "@ui5/webcomponents-icons/dist/line-charts.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "line-charts";

export type LineChartsProps = Omit<IconProps, "name">;

/** Renders `<Icon name="line-charts" />` after this module is evaluated. */
export function LineCharts(props: LineChartsProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
