/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `line-charts` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/line-charts";
 * Optional component: import { LineCharts } from "@reltio/design/icons/sap/line-charts";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/line-charts.js";

export type LineChartsProps = Omit<IconProps, "name">;

/** Renders `<Icon name="line-charts" />` after this module is evaluated. */
export function LineCharts(props: LineChartsProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`line-charts`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
