/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `locked` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/locked";
 * Optional component: import { Locked } from "@reltio/design/icons/sap/locked";
 */
import "@ui5/webcomponents-icons/dist/locked.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "locked";

export type LockedProps = Omit<IconProps, "name">;

/** Renders `<Icon name="locked" />` after this module is evaluated. */
export function Locked(props: LockedProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
