/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `log` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/log";
 * Optional component: import { Log } from "@reltio/design/icons/sap/log";
 */
import "@ui5/webcomponents-icons/dist/log.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "log";

export type LogProps = Omit<IconProps, "name">;

/** Renders `<Icon name="log" />` after this module is evaluated. */
export function Log(props: LogProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
