/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `machine` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/machine";
 * Optional component: import { Machine } from "@reltio/design/icons/sap/machine";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/machine.js";

export type MachineProps = Omit<IconProps, "name">;

/** Renders `<Icon name="machine" />` after this module is evaluated. */
export function Machine(props: MachineProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`machine`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
