/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `manager` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/manager";
 * Optional component: import { Manager } from "@reltio/design/icons/sap/manager";
 */
import "@ui5/webcomponents-icons/dist/manager.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "manager";

export type ManagerProps = Omit<IconProps, "name">;

/** Renders `<Icon name="manager" />` after this module is evaluated. */
export function Manager(props: ManagerProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
