/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `manager-insight` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/manager-insight";
 * Optional component: import { ManagerInsight } from "@reltio/design/icons/sap/manager-insight";
 */
import "@ui5/webcomponents-icons/dist/manager-insight.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "manager-insight";

export type ManagerInsightProps = Omit<IconProps, "name">;

/** Renders `<Icon name="manager-insight" />` after this module is evaluated. */
export function ManagerInsight(props: ManagerInsightProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
