/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `map-2` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/map-2";
 * Optional component: import { Map2 } from "@reltio/design/icons/sap/map-2";
 */
import "@ui5/webcomponents-icons/dist/map-2.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "map-2";

export type Map2Props = Omit<IconProps, "name">;

/** Renders `<Icon name="map-2" />` after this module is evaluated. */
export function Map2(props: Map2Props) {
	return <Icon name={ICON_NAME} {...props} />;
}
