/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `map-fill` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/map-fill";
 * Optional component: import { MapFill } from "@reltio/design/icons/sap/map-fill";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/map-fill.js";

export type MapFillProps = Omit<IconProps, "name">;

/** Renders `<Icon name="map-fill" />` after this module is evaluated. */
export function MapFill(props: MapFillProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`map-fill`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
