/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `marketing-campaign` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/marketing-campaign";
 * Optional component: import { MarketingCampaign } from "@reltio/design/icons/sap/marketing-campaign";
 */
import "@ui5/webcomponents-icons/dist/marketing-campaign.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "marketing-campaign";

export type MarketingCampaignProps = Omit<IconProps, "name">;

/** Renders `<Icon name="marketing-campaign" />` after this module is evaluated. */
export function MarketingCampaign(props: MarketingCampaignProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
