/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `master-task-triangle` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/master-task-triangle";
 * Optional component: import { MasterTaskTriangle } from "@reltio/design/icons/sap/master-task-triangle";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/master-task-triangle.js";

export type MasterTaskTriangleProps = Omit<IconProps, "name">;

/** Renders `<Icon name="master-task-triangle" />` after this module is evaluated. */
export function MasterTaskTriangle(props: MasterTaskTriangleProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`master-task-triangle`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
