/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `master-task-triangle` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/master-task-triangle";
 * Optional component: import { MasterTaskTriangle } from "@reltio/design/icons/sap/master-task-triangle";
 */
import "@ui5/webcomponents-icons/dist/master-task-triangle.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "master-task-triangle";

export type MasterTaskTriangleProps = Omit<IconProps, "name">;

/** Renders `<Icon name="master-task-triangle" />` after this module is evaluated. */
export function MasterTaskTriangle(props: MasterTaskTriangleProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
