/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `measurement-document` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/measurement-document";
 * Optional component: import { MeasurementDocument } from "@reltio/design/icons/sap/measurement-document";
 */
import "@ui5/webcomponents-icons/dist/measurement-document.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "measurement-document";

export type MeasurementDocumentProps = Omit<IconProps, "name">;

/** Renders `<Icon name="measurement-document" />` after this module is evaluated. */
export function MeasurementDocument(props: MeasurementDocumentProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
