/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `measure` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/measure";
 * Optional component: import { Measure } from "@reltio/design/icons/sap/measure";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/measure.js";

export type MeasureProps = Omit<IconProps, "name">;

/** Renders `<Icon name="measure" />` after this module is evaluated. */
export function Measure(props: MeasureProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`measure`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
