/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `measure` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/measure";
 * Optional component: import { Measure } from "@reltio/design/icons/sap/measure";
 */
import "@ui5/webcomponents-icons/dist/measure.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "measure";

export type MeasureProps = Omit<IconProps, "name">;

/** Renders `<Icon name="measure" />` after this module is evaluated. */
export function Measure(props: MeasureProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
