/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `media-reverse` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/media-reverse";
 * Optional component: import { MediaReverse } from "@reltio/design/icons/sap/media-reverse";
 */
import "@ui5/webcomponents-icons/dist/media-reverse.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "media-reverse";

export type MediaReverseProps = Omit<IconProps, "name">;

/** Renders `<Icon name="media-reverse" />` after this module is evaluated. */
export function MediaReverse(props: MediaReverseProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
