/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `media-reverse` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/media-reverse";
 * Optional component: import { MediaReverse } from "@reltio/design/icons/sap/media-reverse";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/media-reverse.js";

export type MediaReverseProps = Omit<IconProps, "name">;

/** Renders `<Icon name="media-reverse" />` after this module is evaluated. */
export function MediaReverse(props: MediaReverseProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`media-reverse`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
