/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `media-rewind` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/media-rewind";
 * Optional component: import { MediaRewind } from "@reltio/design/icons/sap/media-rewind";
 */
import "@ui5/webcomponents-icons/dist/media-rewind.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "media-rewind";

export type MediaRewindProps = Omit<IconProps, "name">;

/** Renders `<Icon name="media-rewind" />` after this module is evaluated. */
export function MediaRewind(props: MediaRewindProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
