/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `media-play` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/media-play";
 * Optional component: import { MediaPlay } from "@reltio/design/icons/sap/media-play";
 */
import "@ui5/webcomponents-icons/dist/media-play.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "media-play";

export type MediaPlayProps = Omit<IconProps, "name">;

/** Renders `<Icon name="media-play" />` after this module is evaluated. */
export function MediaPlay(props: MediaPlayProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
