/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `media-play` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/media-play";
 * Optional component: import { MediaPlay } from "@reltio/design/icons/sap/media-play";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/media-play.js";

export type MediaPlayProps = Omit<IconProps, "name">;

/** Renders `<Icon name="media-play" />` after this module is evaluated. */
export function MediaPlay(props: MediaPlayProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`media-play`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
