/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `menu2` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/menu2";
 * Optional component: import { Menu2 } from "@reltio/design/icons/sap/menu2";
 */
import "@ui5/webcomponents-icons/dist/menu2.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "menu2";

export type Menu2Props = Omit<IconProps, "name">;

/** Renders `<Icon name="menu2" />` after this module is evaluated. */
export function Menu2(props: Menu2Props) {
	return <Icon name={ICON_NAME} {...props} />;
}
