/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `message-information` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/message-information";
 * Optional component: import { MessageInformation } from "@reltio/design/icons/sap/message-information";
 */
import "@ui5/webcomponents-icons/dist/message-information.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "message-information";

export type MessageInformationProps = Omit<IconProps, "name">;

/** Renders `<Icon name="message-information" />` after this module is evaluated. */
export function MessageInformation(props: MessageInformationProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
