/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `message-success` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/message-success";
 * Optional component: import { MessageSuccess } from "@reltio/design/icons/sap/message-success";
 */
import "@ui5/webcomponents-icons/dist/message-success.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "message-success";

export type MessageSuccessProps = Omit<IconProps, "name">;

/** Renders `<Icon name="message-success" />` after this module is evaluated. */
export function MessageSuccess(props: MessageSuccessProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
