/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `message-popup` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/message-popup";
 * Optional component: import { MessagePopup } from "@reltio/design/icons/sap/message-popup";
 */
import "@ui5/webcomponents-icons/dist/message-popup.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "message-popup";

export type MessagePopupProps = Omit<IconProps, "name">;

/** Renders `<Icon name="message-popup" />` after this module is evaluated. */
export function MessagePopup(props: MessagePopupProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
