/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `mileage` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/mileage";
 * Optional component: import { Mileage } from "@reltio/design/icons/sap/mileage";
 */
import "@ui5/webcomponents-icons/dist/mileage.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "mileage";

export type MileageProps = Omit<IconProps, "name">;

/** Renders `<Icon name="mileage" />` after this module is evaluated. */
export function Mileage(props: MileageProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
