/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `minimize` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/minimize";
 * Optional component: import { Minimize } from "@reltio/design/icons/sap/minimize";
 */
import "@ui5/webcomponents-icons/dist/minimize.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "minimize";

export type MinimizeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="minimize" />` after this module is evaluated. */
export function Minimize(props: MinimizeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
