/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `minimize` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/minimize";
 * Optional component: import { Minimize } from "@reltio/design/icons/sap/minimize";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/minimize.js";

export type MinimizeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="minimize" />` after this module is evaluated. */
export function Minimize(props: MinimizeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`minimize`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
