/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `monitor-payments` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/monitor-payments";
 * Optional component: import { MonitorPayments } from "@reltio/design/icons/sap/monitor-payments";
 */
import "@ui5/webcomponents-icons/dist/monitor-payments.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "monitor-payments";

export type MonitorPaymentsProps = Omit<IconProps, "name">;

/** Renders `<Icon name="monitor-payments" />` after this module is evaluated. */
export function MonitorPayments(props: MonitorPaymentsProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
