/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `mri-scan` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/mri-scan";
 * Optional component: import { MriScan } from "@reltio/design/icons/sap/mri-scan";
 */
import "@ui5/webcomponents-icons/dist/mri-scan.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "mri-scan";

export type MriScanProps = Omit<IconProps, "name">;

/** Renders `<Icon name="mri-scan" />` after this module is evaluated. */
export function MriScan(props: MriScanProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
