/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `multiple-radar-chart` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/multiple-radar-chart";
 * Optional component: import { MultipleRadarChart } from "@reltio/design/icons/sap/multiple-radar-chart";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/multiple-radar-chart.js";

export type MultipleRadarChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="multiple-radar-chart" />` after this module is evaluated. */
export function MultipleRadarChart(props: MultipleRadarChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`multiple-radar-chart`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
