/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `multiple-line-chart` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/multiple-line-chart";
 * Optional component: import { MultipleLineChart } from "@reltio/design/icons/sap/multiple-line-chart";
 */
import "@ui5/webcomponents-icons/dist/multiple-line-chart.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "multiple-line-chart";

export type MultipleLineChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="multiple-line-chart" />` after this module is evaluated. */
export function MultipleLineChart(props: MultipleLineChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
