/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `multiselect-none` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/multiselect-none";
 * Optional component: import { MultiselectNone } from "@reltio/design/icons/sap/multiselect-none";
 */
import "@ui5/webcomponents-icons/dist/multiselect-none.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "multiselect-none";

export type MultiselectNoneProps = Omit<IconProps, "name">;

/** Renders `<Icon name="multiselect-none" />` after this module is evaluated. */
export function MultiselectNone(props: MultiselectNoneProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
