/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `multi-select` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/multi-select";
 * Optional component: import { MultiSelect } from "@reltio/design/icons/sap/multi-select";
 */
import "@ui5/webcomponents-icons/dist/multi-select.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "multi-select";

export type MultiSelectProps = Omit<IconProps, "name">;

/** Renders `<Icon name="multi-select" />` after this module is evaluated. */
export function MultiSelect(props: MultiSelectProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
