/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `multiple-bar-chart` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/multiple-bar-chart";
 * Optional component: import { MultipleBarChart } from "@reltio/design/icons/sap/multiple-bar-chart";
 */
import "@ui5/webcomponents-icons/dist/multiple-bar-chart.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "multiple-bar-chart";

export type MultipleBarChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="multiple-bar-chart" />` after this module is evaluated. */
export function MultipleBarChart(props: MultipleBarChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
