/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `multiple-radar-chart` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/multiple-radar-chart";
 * Optional component: import { MultipleRadarChart } from "@reltio/design/icons/sap/multiple-radar-chart";
 */
import "@ui5/webcomponents-icons/dist/multiple-radar-chart.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "multiple-radar-chart";

export type MultipleRadarChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="multiple-radar-chart" />` after this module is evaluated. */
export function MultipleRadarChart(props: MultipleRadarChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
