/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `multiple-pie-chart` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/multiple-pie-chart";
 * Optional component: import { MultiplePieChart } from "@reltio/design/icons/sap/multiple-pie-chart";
 */
import "@ui5/webcomponents-icons/dist/multiple-pie-chart.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "multiple-pie-chart";

export type MultiplePieChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="multiple-pie-chart" />` after this module is evaluated. */
export function MultiplePieChart(props: MultiplePieChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
