/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `multiselect-all` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/multiselect-all";
 * Optional component: import { MultiselectAll } from "@reltio/design/icons/sap/multiselect-all";
 */
import "@ui5/webcomponents-icons/dist/multiselect-all.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "multiselect-all";

export type MultiselectAllProps = Omit<IconProps, "name">;

/** Renders `<Icon name="multiselect-all" />` after this module is evaluated. */
export function MultiselectAll(props: MultiselectAllProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
