/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `my-sales-order` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/my-sales-order";
 * Optional component: import { MySalesOrder } from "@reltio/design/icons/sap/my-sales-order";
 */
import "@ui5/webcomponents-icons/dist/my-sales-order.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "my-sales-order";

export type MySalesOrderProps = Omit<IconProps, "name">;

/** Renders `<Icon name="my-sales-order" />` after this module is evaluated. */
export function MySalesOrder(props: MySalesOrderProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
