/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `navigation-up-arrow` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/navigation-up-arrow";
 * Optional component: import { NavigationUpArrow } from "@reltio/design/icons/sap/navigation-up-arrow";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/navigation-up-arrow.js";

export type NavigationUpArrowProps = Omit<IconProps, "name">;

/** Renders `<Icon name="navigation-up-arrow" />` after this module is evaluated. */
export function NavigationUpArrow(props: NavigationUpArrowProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`navigation-up-arrow`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
