/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `navigation-up-arrow` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/navigation-up-arrow";
 * Optional component: import { NavigationUpArrow } from "@reltio/design/icons/sap/navigation-up-arrow";
 */
import "@ui5/webcomponents-icons/dist/navigation-up-arrow.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "navigation-up-arrow";

export type NavigationUpArrowProps = Omit<IconProps, "name">;

/** Renders `<Icon name="navigation-up-arrow" />` after this module is evaluated. */
export function NavigationUpArrow(props: NavigationUpArrowProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
