/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `navigation-right-arrow` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/navigation-right-arrow";
 * Optional component: import { NavigationRightArrow } from "@reltio/design/icons/sap/navigation-right-arrow";
 */
import "@ui5/webcomponents-icons/dist/navigation-right-arrow.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "navigation-right-arrow";

export type NavigationRightArrowProps = Omit<IconProps, "name">;

/** Renders `<Icon name="navigation-right-arrow" />` after this module is evaluated. */
export function NavigationRightArrow(props: NavigationRightArrowProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
