/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `negative` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/negative";
 * Optional component: import { Negative } from "@reltio/design/icons/sap/negative";
 */
import "@ui5/webcomponents-icons/dist/negative.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "negative";

export type NegativeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="negative" />` after this module is evaluated. */
export function Negative(props: NegativeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
