/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `non-binary` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/non-binary";
 * Optional component: import { NonBinary } from "@reltio/design/icons/sap/non-binary";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/non-binary.js";

export type NonBinaryProps = Omit<IconProps, "name">;

/** Renders `<Icon name="non-binary" />` after this module is evaluated. */
export function NonBinary(props: NonBinaryProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`non-binary`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
