/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `number-sign` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/number-sign";
 * Optional component: import { NumberSign } from "@reltio/design/icons/sap/number-sign";
 */
import "@ui5/webcomponents-icons/dist/number-sign.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "number-sign";

export type NumberSignProps = Omit<IconProps, "name">;

/** Renders `<Icon name="number-sign" />` after this module is evaluated. */
export function NumberSign(props: NumberSignProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
