/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `offsite-work` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/offsite-work";
 * Optional component: import { OffsiteWork } from "@reltio/design/icons/sap/offsite-work";
 */
import "@ui5/webcomponents-icons/dist/offsite-work.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "offsite-work";

export type OffsiteWorkProps = Omit<IconProps, "name">;

/** Renders `<Icon name="offsite-work" />` after this module is evaluated. */
export function OffsiteWork(props: OffsiteWorkProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
