/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `offsite-work` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/offsite-work";
 * Optional component: import { OffsiteWork } from "@reltio/design/icons/sap/offsite-work";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/offsite-work.js";

export type OffsiteWorkProps = Omit<IconProps, "name">;

/** Renders `<Icon name="offsite-work" />` after this module is evaluated. */
export function OffsiteWork(props: OffsiteWorkProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`offsite-work`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
