/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `open-command-field` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/open-command-field";
 * Optional component: import { OpenCommandField } from "@reltio/design/icons/sap/open-command-field";
 */
import "@ui5/webcomponents-icons/dist/open-command-field.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "open-command-field";

export type OpenCommandFieldProps = Omit<IconProps, "name">;

/** Renders `<Icon name="open-command-field" />` after this module is evaluated. */
export function OpenCommandField(props: OpenCommandFieldProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
