/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `org-chart` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/org-chart";
 * Optional component: import { OrgChart } from "@reltio/design/icons/sap/org-chart";
 */
import "@ui5/webcomponents-icons/dist/org-chart.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "org-chart";

export type OrgChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="org-chart" />` after this module is evaluated. */
export function OrgChart(props: OrgChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
