/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `outbox` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/outbox";
 * Optional component: import { Outbox } from "@reltio/design/icons/sap/outbox";
 */
import "@ui5/webcomponents-icons/dist/outbox.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "outbox";

export type OutboxProps = Omit<IconProps, "name">;

/** Renders `<Icon name="outbox" />` after this module is evaluated. */
export function Outbox(props: OutboxProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
