/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `outdent` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/outdent";
 * Optional component: import { Outdent } from "@reltio/design/icons/sap/outdent";
 */
import "@ui5/webcomponents-icons/dist/outdent.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "outdent";

export type OutdentProps = Omit<IconProps, "name">;

/** Renders `<Icon name="outdent" />` after this module is evaluated. */
export function Outdent(props: OutdentProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
