/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `overlay` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/overlay";
 * Optional component: import { Overlay } from "@reltio/design/icons/sap/overlay";
 */
import "@ui5/webcomponents-icons/dist/overlay.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "overlay";

export type OverlayProps = Omit<IconProps, "name">;

/** Renders `<Icon name="overlay" />` after this module is evaluated. */
export function Overlay(props: OverlayProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
