/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `paid-leave` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/paid-leave";
 * Optional component: import { PaidLeave } from "@reltio/design/icons/sap/paid-leave";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/paid-leave.js";

export type PaidLeaveProps = Omit<IconProps, "name">;

/** Renders `<Icon name="paid-leave" />` after this module is evaluated. */
export function PaidLeave(props: PaidLeaveProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`paid-leave`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
