/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `palette` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/palette";
 * Optional component: import { Palette } from "@reltio/design/icons/sap/palette";
 */
import "@ui5/webcomponents-icons/dist/palette.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "palette";

export type PaletteProps = Omit<IconProps, "name">;

/** Renders `<Icon name="palette" />` after this module is evaluated. */
export function Palette(props: PaletteProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
