/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `past` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/past";
 * Optional component: import { Past } from "@reltio/design/icons/sap/past";
 */
import "@ui5/webcomponents-icons/dist/past.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "past";

export type PastProps = Omit<IconProps, "name">;

/** Renders `<Icon name="past" />` after this module is evaluated. */
export function Past(props: PastProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
