/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `payment-approval` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/payment-approval";
 * Optional component: import { PaymentApproval } from "@reltio/design/icons/sap/payment-approval";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/payment-approval.js";

export type PaymentApprovalProps = Omit<IconProps, "name">;

/** Renders `<Icon name="payment-approval" />` after this module is evaluated. */
export function PaymentApproval(props: PaymentApprovalProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`payment-approval`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
