/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `pdf-reader` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/pdf-reader";
 * Optional component: import { PdfReader } from "@reltio/design/icons/sap/pdf-reader";
 */
import "@ui5/webcomponents-icons/dist/pdf-reader.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "pdf-reader";

export type PdfReaderProps = Omit<IconProps, "name">;

/** Renders `<Icon name="pdf-reader" />` after this module is evaluated. */
export function PdfReader(props: PdfReaderProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
