/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `pdf-attachment` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/pdf-attachment";
 * Optional component: import { PdfAttachment } from "@reltio/design/icons/sap/pdf-attachment";
 */
import "@ui5/webcomponents-icons/dist/pdf-attachment.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "pdf-attachment";

export type PdfAttachmentProps = Omit<IconProps, "name">;

/** Renders `<Icon name="pdf-attachment" />` after this module is evaluated. */
export function PdfAttachment(props: PdfAttachmentProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
