/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `pending` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/pending";
 * Optional component: import { Pending } from "@reltio/design/icons/sap/pending";
 */
import "@ui5/webcomponents-icons/dist/pending.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "pending";

export type PendingProps = Omit<IconProps, "name">;

/** Renders `<Icon name="pending" />` after this module is evaluated. */
export function Pending(props: PendingProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
