/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `people-connected` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/people-connected";
 * Optional component: import { PeopleConnected } from "@reltio/design/icons/sap/people-connected";
 */
import "@ui5/webcomponents-icons/dist/people-connected.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "people-connected";

export type PeopleConnectedProps = Omit<IconProps, "name">;

/** Renders `<Icon name="people-connected" />` after this module is evaluated. */
export function PeopleConnected(props: PeopleConnectedProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
