/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `performance` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/performance";
 * Optional component: import { Performance } from "@reltio/design/icons/sap/performance";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/performance.js";

export type PerformanceProps = Omit<IconProps, "name">;

/** Renders `<Icon name="performance" />` after this module is evaluated. */
export function Performance(props: PerformanceProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`performance`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
