/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `permission` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/permission";
 * Optional component: import { Permission } from "@reltio/design/icons/sap/permission";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/permission.js";

export type PermissionProps = Omit<IconProps, "name">;

/** Renders `<Icon name="permission" />` after this module is evaluated. */
export function Permission(props: PermissionProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`permission`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
