/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `person-placeholder` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/person-placeholder";
 * Optional component: import { PersonPlaceholder } from "@reltio/design/icons/sap/person-placeholder";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/person-placeholder.js";

export type PersonPlaceholderProps = Omit<IconProps, "name">;

/** Renders `<Icon name="person-placeholder" />` after this module is evaluated. */
export function PersonPlaceholder(props: PersonPlaceholderProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`person-placeholder`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
