/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `pharmacy` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/pharmacy";
 * Optional component: import { Pharmacy } from "@reltio/design/icons/sap/pharmacy";
 */
import "@ui5/webcomponents-icons/dist/pharmacy.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "pharmacy";

export type PharmacyProps = Omit<IconProps, "name">;

/** Renders `<Icon name="pharmacy" />` after this module is evaluated. */
export function Pharmacy(props: PharmacyProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
