/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `phone` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/phone";
 * Optional component: import { Phone } from "@reltio/design/icons/sap/phone";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/phone.js";

export type PhoneProps = Omit<IconProps, "name">;

/** Renders `<Icon name="phone" />` after this module is evaluated. */
export function Phone(props: PhoneProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`phone`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
