/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `photo-voltaic` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/photo-voltaic";
 * Optional component: import { PhotoVoltaic } from "@reltio/design/icons/sap/photo-voltaic";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/photo-voltaic.js";

export type PhotoVoltaicProps = Omit<IconProps, "name">;

/** Renders `<Icon name="photo-voltaic" />` after this module is evaluated. */
export function PhotoVoltaic(props: PhotoVoltaicProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`photo-voltaic`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
