/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `physical-activity` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/physical-activity";
 * Optional component: import { PhysicalActivity } from "@reltio/design/icons/sap/physical-activity";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/physical-activity.js";

export type PhysicalActivityProps = Omit<IconProps, "name">;

/** Renders `<Icon name="physical-activity" />` after this module is evaluated. */
export function PhysicalActivity(props: PhysicalActivityProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`physical-activity`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
