/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `picture` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/picture";
 * Optional component: import { Picture } from "@reltio/design/icons/sap/picture";
 */
import "@ui5/webcomponents-icons/dist/picture.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "picture";

export type PictureProps = Omit<IconProps, "name">;

/** Renders `<Icon name="picture" />` after this module is evaluated. */
export function Picture(props: PictureProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
