/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `pie-chart` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/pie-chart";
 * Optional component: import { PieChart } from "@reltio/design/icons/sap/pie-chart";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/pie-chart.js";

export type PieChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="pie-chart" />` after this module is evaluated. */
export function PieChart(props: PieChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`pie-chart`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
