/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `pixelate` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/pixelate";
 * Optional component: import { Pixelate } from "@reltio/design/icons/sap/pixelate";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/pixelate.js";

export type PixelateProps = Omit<IconProps, "name">;

/** Renders `<Icon name="pixelate" />` after this module is evaluated. */
export function Pixelate(props: PixelateProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`pixelate`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
