/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `pool` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/pool";
 * Optional component: import { Pool } from "@reltio/design/icons/sap/pool";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/pool.js";

export type PoolProps = Omit<IconProps, "name">;

/** Renders `<Icon name="pool" />` after this module is evaluated. */
export function Pool(props: PoolProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`pool`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
