/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `popup-window` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/popup-window";
 * Optional component: import { PopupWindow } from "@reltio/design/icons/sap/popup-window";
 */
import "@ui5/webcomponents-icons/dist/popup-window.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "popup-window";

export type PopupWindowProps = Omit<IconProps, "name">;

/** Renders `<Icon name="popup-window" />` after this module is evaluated. */
export function PopupWindow(props: PopupWindowProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
