/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `positive` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/positive";
 * Optional component: import { Positive } from "@reltio/design/icons/sap/positive";
 */
import "@ui5/webcomponents-icons/dist/positive.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "positive";

export type PositiveProps = Omit<IconProps, "name">;

/** Renders `<Icon name="positive" />` after this module is evaluated. */
export function Positive(props: PositiveProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
