/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `post` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/post";
 * Optional component: import { Post } from "@reltio/design/icons/sap/post";
 */
import "@ui5/webcomponents-icons/dist/post.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "post";

export type PostProps = Omit<IconProps, "name">;

/** Renders `<Icon name="post" />` after this module is evaluated. */
export function Post(props: PostProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
