/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `present` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/present";
 * Optional component: import { Present } from "@reltio/design/icons/sap/present";
 */
import "@ui5/webcomponents-icons/dist/present.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "present";

export type PresentProps = Omit<IconProps, "name">;

/** Renders `<Icon name="present" />` after this module is evaluated. */
export function Present(props: PresentProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
