/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `primary-key` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/primary-key";
 * Optional component: import { PrimaryKey } from "@reltio/design/icons/sap/primary-key";
 */
import "@ui5/webcomponents-icons/dist/primary-key.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "primary-key";

export type PrimaryKeyProps = Omit<IconProps, "name">;

/** Renders `<Icon name="primary-key" />` after this module is evaluated. */
export function PrimaryKey(props: PrimaryKeyProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
