/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `private` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/private";
 * Optional component: import { Private } from "@reltio/design/icons/sap/private";
 */
import "@ui5/webcomponents-icons/dist/private.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "private";

export type PrivateProps = Omit<IconProps, "name">;

/** Renders `<Icon name="private" />` after this module is evaluated. */
export function Private(props: PrivateProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
