/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `program-triangles` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/program-triangles";
 * Optional component: import { ProgramTriangles } from "@reltio/design/icons/sap/program-triangles";
 */
import "@ui5/webcomponents-icons/dist/program-triangles.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "program-triangles";

export type ProgramTrianglesProps = Omit<IconProps, "name">;

/** Renders `<Icon name="program-triangles" />` after this module is evaluated. */
export function ProgramTriangles(props: ProgramTrianglesProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
