/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `program-triangles` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/program-triangles";
 * Optional component: import { ProgramTriangles } from "@reltio/design/icons/sap/program-triangles";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/program-triangles.js";

export type ProgramTrianglesProps = Omit<IconProps, "name">;

/** Renders `<Icon name="program-triangles" />` after this module is evaluated. */
export function ProgramTriangles(props: ProgramTrianglesProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`program-triangles`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
