/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `pull-down` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/pull-down";
 * Optional component: import { PullDown } from "@reltio/design/icons/sap/pull-down";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/pull-down.js";

export type PullDownProps = Omit<IconProps, "name">;

/** Renders `<Icon name="pull-down" />` after this module is evaluated. */
export function PullDown(props: PullDownProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`pull-down`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
