/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `pushpin-off` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/pushpin-off";
 * Optional component: import { PushpinOff } from "@reltio/design/icons/sap/pushpin-off";
 */
import "@ui5/webcomponents-icons/dist/pushpin-off.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "pushpin-off";

export type PushpinOffProps = Omit<IconProps, "name">;

/** Renders `<Icon name="pushpin-off" />` after this module is evaluated. */
export function PushpinOff(props: PushpinOffProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
