/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `puzzle` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/puzzle";
 * Optional component: import { Puzzle } from "@reltio/design/icons/sap/puzzle";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/puzzle.js";

export type PuzzleProps = Omit<IconProps, "name">;

/** Renders `<Icon name="puzzle" />` after this module is evaluated. */
export function Puzzle(props: PuzzleProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`puzzle`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
