/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `puzzle` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/puzzle";
 * Optional component: import { Puzzle } from "@reltio/design/icons/sap/puzzle";
 */
import "@ui5/webcomponents-icons/dist/puzzle.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "puzzle";

export type PuzzleProps = Omit<IconProps, "name">;

/** Renders `<Icon name="puzzle" />` after this module is evaluated. */
export function Puzzle(props: PuzzleProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
