/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `record` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/record";
 * Optional component: import { Record } from "@reltio/design/icons/sap/record";
 */
import "@ui5/webcomponents-icons/dist/record.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "record";

export type RecordProps = Omit<IconProps, "name">;

/** Renders `<Icon name="record" />` after this module is evaluated. */
export function Record(props: RecordProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
