/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `redo` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/redo";
 * Optional component: import { Redo } from "@reltio/design/icons/sap/redo";
 */
import "@ui5/webcomponents-icons/dist/redo.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "redo";

export type RedoProps = Omit<IconProps, "name">;

/** Renders `<Icon name="redo" />` after this module is evaluated. */
export function Redo(props: RedoProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
