/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `reset` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/reset";
 * Optional component: import { Reset } from "@reltio/design/icons/sap/reset";
 */
import "@ui5/webcomponents-icons/dist/reset.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "reset";

export type ResetProps = Omit<IconProps, "name">;

/** Renders `<Icon name="reset" />` after this module is evaluated. */
export function Reset(props: ResetProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
