/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `resize` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/resize";
 * Optional component: import { Resize } from "@reltio/design/icons/sap/resize";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/resize.js";

export type ResizeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="resize" />` after this module is evaluated. */
export function Resize(props: ResizeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`resize`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
