/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `resize` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/resize";
 * Optional component: import { Resize } from "@reltio/design/icons/sap/resize";
 */
import "@ui5/webcomponents-icons/dist/resize.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "resize";

export type ResizeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="resize" />` after this module is evaluated. */
export function Resize(props: ResizeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
