/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `resize-vertical` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/resize-vertical";
 * Optional component: import { ResizeVertical } from "@reltio/design/icons/sap/resize-vertical";
 */
import "@ui5/webcomponents-icons/dist/resize-vertical.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "resize-vertical";

export type ResizeVerticalProps = Omit<IconProps, "name">;

/** Renders `<Icon name="resize-vertical" />` after this module is evaluated. */
export function ResizeVertical(props: ResizeVerticalProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
