/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `resize-horizontal` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/resize-horizontal";
 * Optional component: import { ResizeHorizontal } from "@reltio/design/icons/sap/resize-horizontal";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/resize-horizontal.js";

export type ResizeHorizontalProps = Omit<IconProps, "name">;

/** Renders `<Icon name="resize-horizontal" />` after this module is evaluated. */
export function ResizeHorizontal(props: ResizeHorizontalProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`resize-horizontal`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
