/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `resize-vertical` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/resize-vertical";
 * Optional component: import { ResizeVertical } from "@reltio/design/icons/sap/resize-vertical";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/resize-vertical.js";

export type ResizeVerticalProps = Omit<IconProps, "name">;

/** Renders `<Icon name="resize-vertical" />` after this module is evaluated. */
export function ResizeVertical(props: ResizeVerticalProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`resize-vertical`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
