/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `resize-corner` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/resize-corner";
 * Optional component: import { ResizeCorner } from "@reltio/design/icons/sap/resize-corner";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/resize-corner.js";

export type ResizeCornerProps = Omit<IconProps, "name">;

/** Renders `<Icon name="resize-corner" />` after this module is evaluated. */
export function ResizeCorner(props: ResizeCornerProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`resize-corner`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
