/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `s4hana` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/s4hana";
 * Optional component: import { S4hana } from "@reltio/design/icons/sap/s4hana";
 */
import "@ui5/webcomponents-icons/dist/s4hana.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "s4hana";

export type S4hanaProps = Omit<IconProps, "name">;

/** Renders `<Icon name="s4hana" />` after this module is evaluated. */
export function S4hana(props: S4hanaProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
