/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `s4hana` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/s4hana";
 * Optional component: import { S4hana } from "@reltio/design/icons/sap/s4hana";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/s4hana.js";

export type S4hanaProps = Omit<IconProps, "name">;

/** Renders `<Icon name="s4hana" />` after this module is evaluated. */
export function S4hana(props: S4hanaProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`s4hana`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
