/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sales-quote` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/sales-quote";
 * Optional component: import { SalesQuote } from "@reltio/design/icons/sap/sales-quote";
 */
import "@ui5/webcomponents-icons/dist/sales-quote.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "sales-quote";

export type SalesQuoteProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sales-quote" />` after this module is evaluated. */
export function SalesQuote(props: SalesQuoteProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
