/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sales-notification` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/sales-notification";
 * Optional component: import { SalesNotification } from "@reltio/design/icons/sap/sales-notification";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/sales-notification.js";

export type SalesNotificationProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sales-notification" />` after this module is evaluated. */
export function SalesNotification(props: SalesNotificationProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`sales-notification`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
