/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sales-document` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/sales-document";
 * Optional component: import { SalesDocument } from "@reltio/design/icons/sap/sales-document";
 */
import "@ui5/webcomponents-icons/dist/sales-document.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "sales-document";

export type SalesDocumentProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sales-document" />` after this module is evaluated. */
export function SalesDocument(props: SalesDocumentProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
