/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sap-logo-shape` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/sap-logo-shape";
 * Optional component: import { SapLogoShape } from "@reltio/design/icons/sap/sap-logo-shape";
 */
import "@ui5/webcomponents-icons/dist/sap-logo-shape.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "sap-logo-shape";

export type SapLogoShapeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sap-logo-shape" />` after this module is evaluated. */
export function SapLogoShape(props: SapLogoShapeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
