/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `save` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/save";
 * Optional component: import { Save } from "@reltio/design/icons/sap/save";
 */
import "@ui5/webcomponents-icons/dist/save.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "save";

export type SaveProps = Omit<IconProps, "name">;

/** Renders `<Icon name="save" />` after this module is evaluated. */
export function Save(props: SaveProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
