/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `scatter-chart` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/scatter-chart";
 * Optional component: import { ScatterChart } from "@reltio/design/icons/sap/scatter-chart";
 */
import "@ui5/webcomponents-icons/dist/scatter-chart.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "scatter-chart";

export type ScatterChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="scatter-chart" />` after this module is evaluated. */
export function ScatterChart(props: ScatterChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
