/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `screen-split-one` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/screen-split-one";
 * Optional component: import { ScreenSplitOne } from "@reltio/design/icons/sap/screen-split-one";
 */
import "@ui5/webcomponents-icons/dist/screen-split-one.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "screen-split-one";

export type ScreenSplitOneProps = Omit<IconProps, "name">;

/** Renders `<Icon name="screen-split-one" />` after this module is evaluated. */
export function ScreenSplitOne(props: ScreenSplitOneProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
