/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `screen-split-two` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/screen-split-two";
 * Optional component: import { ScreenSplitTwo } from "@reltio/design/icons/sap/screen-split-two";
 */
import "@ui5/webcomponents-icons/dist/screen-split-two.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "screen-split-two";

export type ScreenSplitTwoProps = Omit<IconProps, "name">;

/** Renders `<Icon name="screen-split-two" />` after this module is evaluated. */
export function ScreenSplitTwo(props: ScreenSplitTwoProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
