/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `settings` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/settings";
 * Optional component: import { Settings } from "@reltio/design/icons/sap/settings";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/settings.js";

export type SettingsProps = Omit<IconProps, "name">;

/** Renders `<Icon name="settings" />` after this module is evaluated. */
export function Settings(props: SettingsProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`settings`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
