/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `share` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/share";
 * Optional component: import { Share } from "@reltio/design/icons/sap/share";
 */
import "@ui5/webcomponents-icons/dist/share.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "share";

export type ShareProps = Omit<IconProps, "name">;

/** Renders `<Icon name="share" />` after this module is evaluated. */
export function Share(props: ShareProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
