/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `share-2` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/share-2";
 * Optional component: import { Share2 } from "@reltio/design/icons/sap/share-2";
 */
import "@ui5/webcomponents-icons/dist/share-2.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "share-2";

export type Share2Props = Omit<IconProps, "name">;

/** Renders `<Icon name="share-2" />` after this module is evaluated. */
export function Share2(props: Share2Props) {
	return <Icon name={ICON_NAME} {...props} />;
}
