/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `share` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/share";
 * Optional component: import { Share } from "@reltio/design/icons/sap/share";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/share.js";

export type ShareProps = Omit<IconProps, "name">;

/** Renders `<Icon name="share" />` after this module is evaluated. */
export function Share(props: ShareProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`share`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
