/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `share-2` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/share-2";
 * Optional component: import { Share2 } from "@reltio/design/icons/sap/share-2";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/share-2.js";

export type Share2Props = Omit<IconProps, "name">;

/** Renders `<Icon name="share-2" />` after this module is evaluated. */
export function Share2(props: Share2Props) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`share-2`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
