/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `shelf` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/shelf";
 * Optional component: import { Shelf } from "@reltio/design/icons/sap/shelf";
 */
import "@ui5/webcomponents-icons/dist/shelf.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "shelf";

export type ShelfProps = Omit<IconProps, "name">;

/** Renders `<Icon name="shelf" />` after this module is evaluated. */
export function Shelf(props: ShelfProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
