/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `show` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/show";
 * Optional component: import { Show } from "@reltio/design/icons/sap/show";
 */
import "@ui5/webcomponents-icons/dist/show.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "show";

export type ShowProps = Omit<IconProps, "name">;

/** Renders `<Icon name="show" />` after this module is evaluated. */
export function Show(props: ShowProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
