/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `slim-arrow-left` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/slim-arrow-left";
 * Optional component: import { SlimArrowLeft } from "@reltio/design/icons/sap/slim-arrow-left";
 */
import "@ui5/webcomponents-icons/dist/slim-arrow-left.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "slim-arrow-left";

export type SlimArrowLeftProps = Omit<IconProps, "name">;

/** Renders `<Icon name="slim-arrow-left" />` after this module is evaluated. */
export function SlimArrowLeft(props: SlimArrowLeftProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
