/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `slim-arrow-right` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/slim-arrow-right";
 * Optional component: import { SlimArrowRight } from "@reltio/design/icons/sap/slim-arrow-right";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/slim-arrow-right.js";

export type SlimArrowRightProps = Omit<IconProps, "name">;

/** Renders `<Icon name="slim-arrow-right" />` after this module is evaluated. */
export function SlimArrowRight(props: SlimArrowRightProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`slim-arrow-right`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
