/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sort` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/sort";
 * Optional component: import { Sort } from "@reltio/design/icons/sap/sort";
 */
import "@ui5/webcomponents-icons/dist/sort.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "sort";

export type SortProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sort" />` after this module is evaluated. */
export function Sort(props: SortProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
