/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sorting-ranking` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/sorting-ranking";
 * Optional component: import { SortingRanking } from "@reltio/design/icons/sap/sorting-ranking";
 */
import "@ui5/webcomponents-icons/dist/sorting-ranking.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "sorting-ranking";

export type SortingRankingProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sorting-ranking" />` after this module is evaluated. */
export function SortingRanking(props: SortingRankingProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
