/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sort-descending` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/sort-descending";
 * Optional component: import { SortDescending } from "@reltio/design/icons/sap/sort-descending";
 */
import "@ui5/webcomponents-icons/dist/sort-descending.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "sort-descending";

export type SortDescendingProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sort-descending" />` after this module is evaluated. */
export function SortDescending(props: SortDescendingProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
