/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sound` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/sound";
 * Optional component: import { Sound } from "@reltio/design/icons/sap/sound";
 */
import "@ui5/webcomponents-icons/dist/sound.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "sound";

export type SoundProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sound" />` after this module is evaluated. */
export function Sound(props: SoundProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
