/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sound-off` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/sound-off";
 * Optional component: import { SoundOff } from "@reltio/design/icons/sap/sound-off";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/sound-off.js";

export type SoundOffProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sound-off" />` after this module is evaluated. */
export function SoundOff(props: SoundOffProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`sound-off`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
