/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sound-loud` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/sound-loud";
 * Optional component: import { SoundLoud } from "@reltio/design/icons/sap/sound-loud";
 */
import "@ui5/webcomponents-icons/dist/sound-loud.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "sound-loud";

export type SoundLoudProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sound-loud" />` after this module is evaluated. */
export function SoundLoud(props: SoundLoudProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
