/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `space-navigation` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/space-navigation";
 * Optional component: import { SpaceNavigation } from "@reltio/design/icons/sap/space-navigation";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/space-navigation.js";

export type SpaceNavigationProps = Omit<IconProps, "name">;

/** Renders `<Icon name="space-navigation" />` after this module is evaluated. */
export function SpaceNavigation(props: SpaceNavigationProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`space-navigation`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
