/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `status-positive` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/status-positive";
 * Optional component: import { StatusPositive } from "@reltio/design/icons/sap/status-positive";
 */
import "@ui5/webcomponents-icons/dist/status-positive.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "status-positive";

export type StatusPositiveProps = Omit<IconProps, "name">;

/** Renders `<Icon name="status-positive" />` after this module is evaluated. */
export function StatusPositive(props: StatusPositiveProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
