/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `status-positive` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/status-positive";
 * Optional component: import { StatusPositive } from "@reltio/design/icons/sap/status-positive";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/status-positive.js";

export type StatusPositiveProps = Omit<IconProps, "name">;

/** Renders `<Icon name="status-positive" />` after this module is evaluated. */
export function StatusPositive(props: StatusPositiveProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`status-positive`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
