/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `status-critical` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/status-critical";
 * Optional component: import { StatusCritical } from "@reltio/design/icons/sap/status-critical";
 */
import "@ui5/webcomponents-icons/dist/status-critical.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "status-critical";

export type StatusCriticalProps = Omit<IconProps, "name">;

/** Renders `<Icon name="status-critical" />` after this module is evaluated. */
export function StatusCritical(props: StatusCriticalProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
