/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `status-in-process` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/status-in-process";
 * Optional component: import { StatusInProcess } from "@reltio/design/icons/sap/status-in-process";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/status-in-process.js";

export type StatusInProcessProps = Omit<IconProps, "name">;

/** Renders `<Icon name="status-in-process" />` after this module is evaluated. */
export function StatusInProcess(props: StatusInProcessProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`status-in-process`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
