/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `step` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/step";
 * Optional component: import { Step } from "@reltio/design/icons/sap/step";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/step.js";

export type StepProps = Omit<IconProps, "name">;

/** Renders `<Icon name="step" />` after this module is evaluated. */
export function Step(props: StepProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`step`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
