/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `stethoscope` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/stethoscope";
 * Optional component: import { Stethoscope } from "@reltio/design/icons/sap/stethoscope";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/stethoscope.js";

export type StethoscopeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="stethoscope" />` after this module is evaluated. */
export function Stethoscope(props: StethoscopeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`stethoscope`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
