/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `study-leave` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/study-leave";
 * Optional component: import { StudyLeave } from "@reltio/design/icons/sap/study-leave";
 */
import "@ui5/webcomponents-icons/dist/study-leave.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "study-leave";

export type StudyLeaveProps = Omit<IconProps, "name">;

/** Renders `<Icon name="study-leave" />` after this module is evaluated. */
export function StudyLeave(props: StudyLeaveProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
