/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `subway-train` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/subway-train";
 * Optional component: import { SubwayTrain } from "@reltio/design/icons/sap/subway-train";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/subway-train.js";

export type SubwayTrainProps = Omit<IconProps, "name">;

/** Renders `<Icon name="subway-train" />` after this module is evaluated. */
export function SubwayTrain(props: SubwayTrainProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`subway-train`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
