/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `suitcase` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/suitcase";
 * Optional component: import { Suitcase } from "@reltio/design/icons/sap/suitcase";
 */
import "@ui5/webcomponents-icons/dist/suitcase.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "suitcase";

export type SuitcaseProps = Omit<IconProps, "name">;

/** Renders `<Icon name="suitcase" />` after this module is evaluated. */
export function Suitcase(props: SuitcaseProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
