/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sum` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/sum";
 * Optional component: import { Sum } from "@reltio/design/icons/sap/sum";
 */
import "@ui5/webcomponents-icons/dist/sum.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "sum";

export type SumProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sum" />` after this module is evaluated. */
export function Sum(props: SumProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
