/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `survey` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/survey";
 * Optional component: import { Survey } from "@reltio/design/icons/sap/survey";
 */
import "@ui5/webcomponents-icons/dist/survey.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "survey";

export type SurveyProps = Omit<IconProps, "name">;

/** Renders `<Icon name="survey" />` after this module is evaluated. */
export function Survey(props: SurveyProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
