/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `synchronize` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/synchronize";
 * Optional component: import { Synchronize } from "@reltio/design/icons/sap/synchronize";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/synchronize.js";

export type SynchronizeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="synchronize" />` after this module is evaluated. */
export function Synchronize(props: SynchronizeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`synchronize`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
