/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `syntax` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/syntax";
 * Optional component: import { Syntax } from "@reltio/design/icons/sap/syntax";
 */
import "@ui5/webcomponents-icons/dist/syntax.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "syntax";

export type SyntaxProps = Omit<IconProps, "name">;

/** Renders `<Icon name="syntax" />` after this module is evaluated. */
export function Syntax(props: SyntaxProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
