/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `syringe` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/syringe";
 * Optional component: import { Syringe } from "@reltio/design/icons/sap/syringe";
 */
import "@ui5/webcomponents-icons/dist/syringe.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "syringe";

export type SyringeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="syringe" />` after this module is evaluated. */
export function Syringe(props: SyringeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
