/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sys-next-page` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/sys-next-page";
 * Optional component: import { SysNextPage } from "@reltio/design/icons/sap/sys-next-page";
 */
import "@ui5/webcomponents-icons/dist/sys-next-page.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "sys-next-page";

export type SysNextPageProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sys-next-page" />` after this module is evaluated. */
export function SysNextPage(props: SysNextPageProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
