/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sys-first-page` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/sys-first-page";
 * Optional component: import { SysFirstPage } from "@reltio/design/icons/sap/sys-first-page";
 */
import "@ui5/webcomponents-icons/dist/sys-first-page.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "sys-first-page";

export type SysFirstPageProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sys-first-page" />` after this module is evaluated. */
export function SysFirstPage(props: SysFirstPageProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
