/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sys-last-page` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/sys-last-page";
 * Optional component: import { SysLastPage } from "@reltio/design/icons/sap/sys-last-page";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/sys-last-page.js";

export type SysLastPageProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sys-last-page" />` after this module is evaluated. */
export function SysLastPage(props: SysLastPageProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`sys-last-page`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
