/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sys-minus` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/sys-minus";
 * Optional component: import { SysMinus } from "@reltio/design/icons/sap/sys-minus";
 */
import "@ui5/webcomponents-icons/dist/sys-minus.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "sys-minus";

export type SysMinusProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sys-minus" />` after this module is evaluated. */
export function SysMinus(props: SysMinusProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
