/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sys-help` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/sys-help";
 * Optional component: import { SysHelp } from "@reltio/design/icons/sap/sys-help";
 */
import "@ui5/webcomponents-icons/dist/sys-help.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "sys-help";

export type SysHelpProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sys-help" />` after this module is evaluated. */
export function SysHelp(props: SysHelpProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
