/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sys-prev-page` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/sys-prev-page";
 * Optional component: import { SysPrevPage } from "@reltio/design/icons/sap/sys-prev-page";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/sys-prev-page.js";

export type SysPrevPageProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sys-prev-page" />` after this module is evaluated. */
export function SysPrevPage(props: SysPrevPageProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`sys-prev-page`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
