/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sys-back` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/sys-back";
 * Optional component: import { SysBack } from "@reltio/design/icons/sap/sys-back";
 */
import "@ui5/webcomponents-icons/dist/sys-back.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "sys-back";

export type SysBackProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sys-back" />` after this module is evaluated. */
export function SysBack(props: SysBackProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
