/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sys-find` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/sys-find";
 * Optional component: import { SysFind } from "@reltio/design/icons/sap/sys-find";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/sys-find.js";

export type SysFindProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sys-find" />` after this module is evaluated. */
export function SysFind(props: SysFindProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`sys-find`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
