/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sys-cancel` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/sys-cancel";
 * Optional component: import { SysCancel } from "@reltio/design/icons/sap/sys-cancel";
 */
import "@ui5/webcomponents-icons/dist/sys-cancel.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "sys-cancel";

export type SysCancelProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sys-cancel" />` after this module is evaluated. */
export function SysCancel(props: SysCancelProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
