/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sys-monitor` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/sys-monitor";
 * Optional component: import { SysMonitor } from "@reltio/design/icons/sap/sys-monitor";
 */
import "@ui5/webcomponents-icons/dist/sys-monitor.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "sys-monitor";

export type SysMonitorProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sys-monitor" />` after this module is evaluated. */
export function SysMonitor(props: SysMonitorProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
