/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sys-back` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/sys-back";
 * Optional component: import { SysBack } from "@reltio/design/icons/sap/sys-back";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/sys-back.js";

export type SysBackProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sys-back" />` after this module is evaluated. */
export function SysBack(props: SysBackProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`sys-back`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
