/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `sys-prev-page` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/sys-prev-page";
 * Optional component: import { SysPrevPage } from "@reltio/design/icons/sap/sys-prev-page";
 */
import "@ui5/webcomponents-icons/dist/sys-prev-page.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "sys-prev-page";

export type SysPrevPageProps = Omit<IconProps, "name">;

/** Renders `<Icon name="sys-prev-page" />` after this module is evaluated. */
export function SysPrevPage(props: SysPrevPageProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
