/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `table-view` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/table-view";
 * Optional component: import { TableView } from "@reltio/design/icons/sap/table-view";
 */
import "@ui5/webcomponents-icons/dist/table-view.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "table-view";

export type TableViewProps = Omit<IconProps, "name">;

/** Renders `<Icon name="table-view" />` after this module is evaluated. */
export function TableView(props: TableViewProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
