/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `table-chart` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/table-chart";
 * Optional component: import { TableChart } from "@reltio/design/icons/sap/table-chart";
 */
import "@ui5/webcomponents-icons/dist/table-chart.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "table-chart";

export type TableChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="table-chart" />` after this module is evaluated. */
export function TableChart(props: TableChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
