/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `table-chart` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/table-chart";
 * Optional component: import { TableChart } from "@reltio/design/icons/sap/table-chart";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/table-chart.js";

export type TableChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="table-chart" />` after this module is evaluated. */
export function TableChart(props: TableChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`table-chart`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
