/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `tag` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/tag";
 * Optional component: import { Tag } from "@reltio/design/icons/sap/tag";
 */
import "@ui5/webcomponents-icons/dist/tag.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "tag";

export type TagProps = Omit<IconProps, "name">;

/** Renders `<Icon name="tag" />` after this module is evaluated. */
export function Tag(props: TagProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
