/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `target-group` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/target-group";
 * Optional component: import { TargetGroup } from "@reltio/design/icons/sap/target-group";
 */
import "@ui5/webcomponents-icons/dist/target-group.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "target-group";

export type TargetGroupProps = Omit<IconProps, "name">;

/** Renders `<Icon name="target-group" />` after this module is evaluated. */
export function TargetGroup(props: TargetGroupProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
