/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `task` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/task";
 * Optional component: import { Task } from "@reltio/design/icons/sap/task";
 */
import "@ui5/webcomponents-icons/dist/task.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "task";

export type TaskProps = Omit<IconProps, "name">;

/** Renders `<Icon name="task" />` after this module is evaluated. */
export function Task(props: TaskProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
