/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `technical-object` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/technical-object";
 * Optional component: import { TechnicalObject } from "@reltio/design/icons/sap/technical-object";
 */
import "@ui5/webcomponents-icons/dist/technical-object.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "technical-object";

export type TechnicalObjectProps = Omit<IconProps, "name">;

/** Renders `<Icon name="technical-object" />` after this module is evaluated. */
export function TechnicalObject(props: TechnicalObjectProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
