/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `technical-object` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/technical-object";
 * Optional component: import { TechnicalObject } from "@reltio/design/icons/sap/technical-object";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/technical-object.js";

export type TechnicalObjectProps = Omit<IconProps, "name">;

/** Renders `<Icon name="technical-object" />` after this module is evaluated. */
export function TechnicalObject(props: TechnicalObjectProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`technical-object`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
