/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `text-align-left` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/text-align-left";
 * Optional component: import { TextAlignLeft } from "@reltio/design/icons/sap/text-align-left";
 */
import "@ui5/webcomponents-icons/dist/text-align-left.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "text-align-left";

export type TextAlignLeftProps = Omit<IconProps, "name">;

/** Renders `<Icon name="text-align-left" />` after this module is evaluated. */
export function TextAlignLeft(props: TextAlignLeftProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
