/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `text-align-right` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/text-align-right";
 * Optional component: import { TextAlignRight } from "@reltio/design/icons/sap/text-align-right";
 */
import "@ui5/webcomponents-icons/dist/text-align-right.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "text-align-right";

export type TextAlignRightProps = Omit<IconProps, "name">;

/** Renders `<Icon name="text-align-right" />` after this module is evaluated. */
export function TextAlignRight(props: TextAlignRightProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
