/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `thing-type` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/thing-type";
 * Optional component: import { ThingType } from "@reltio/design/icons/sap/thing-type";
 */
import "@ui5/webcomponents-icons/dist/thing-type.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "thing-type";

export type ThingTypeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="thing-type" />` after this module is evaluated. */
export function ThingType(props: ThingTypeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
