/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `thumb-down` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/thumb-down";
 * Optional component: import { ThumbDown } from "@reltio/design/icons/sap/thumb-down";
 */
import "@ui5/webcomponents-icons/dist/thumb-down.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "thumb-down";

export type ThumbDownProps = Omit<IconProps, "name">;

/** Renders `<Icon name="thumb-down" />` after this module is evaluated. */
export function ThumbDown(props: ThumbDownProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
