/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `thumb-up` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/thumb-up";
 * Optional component: import { ThumbUp } from "@reltio/design/icons/sap/thumb-up";
 */
import "@ui5/webcomponents-icons/dist/thumb-up.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "thumb-up";

export type ThumbUpProps = Omit<IconProps, "name">;

/** Renders `<Icon name="thumb-up" />` after this module is evaluated. */
export function ThumbUp(props: ThumbUpProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
