/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `time-off` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/time-off";
 * Optional component: import { TimeOff } from "@reltio/design/icons/sap/time-off";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/time-off.js";

export type TimeOffProps = Omit<IconProps, "name">;

/** Renders `<Icon name="time-off" />` after this module is evaluated. */
export function TimeOff(props: TimeOffProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`time-off`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
