/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `timesheet` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/timesheet";
 * Optional component: import { Timesheet } from "@reltio/design/icons/sap/timesheet";
 */
import "@ui5/webcomponents-icons/dist/timesheet.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "timesheet";

export type TimesheetProps = Omit<IconProps, "name">;

/** Renders `<Icon name="timesheet" />` after this module is evaluated. */
export function Timesheet(props: TimesheetProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
