/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `time-entry-request` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/time-entry-request";
 * Optional component: import { TimeEntryRequest } from "@reltio/design/icons/sap/time-entry-request";
 */
import "@ui5/webcomponents-icons/dist/time-entry-request.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "time-entry-request";

export type TimeEntryRequestProps = Omit<IconProps, "name">;

/** Renders `<Icon name="time-entry-request" />` after this module is evaluated. */
export function TimeEntryRequest(props: TimeEntryRequestProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
