/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `time-off` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/time-off";
 * Optional component: import { TimeOff } from "@reltio/design/icons/sap/time-off";
 */
import "@ui5/webcomponents-icons/dist/time-off.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "time-off";

export type TimeOffProps = Omit<IconProps, "name">;

/** Renders `<Icon name="time-off" />` after this module is evaluated. */
export function TimeOff(props: TimeOffProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
