/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `to-be-reviewed` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/to-be-reviewed";
 * Optional component: import { ToBeReviewed } from "@reltio/design/icons/sap/to-be-reviewed";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/to-be-reviewed.js";

export type ToBeReviewedProps = Omit<IconProps, "name">;

/** Renders `<Icon name="to-be-reviewed" />` after this module is evaluated. */
export function ToBeReviewed(props: ToBeReviewedProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`to-be-reviewed`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
