/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `toaster-up` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/toaster-up";
 * Optional component: import { ToasterUp } from "@reltio/design/icons/sap/toaster-up";
 */
import "@ui5/webcomponents-icons/dist/toaster-up.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "toaster-up";

export type ToasterUpProps = Omit<IconProps, "name">;

/** Renders `<Icon name="toaster-up" />` after this module is evaluated. */
export function ToasterUp(props: ToasterUpProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
