/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `tools-opportunity` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/tools-opportunity";
 * Optional component: import { ToolsOpportunity } from "@reltio/design/icons/sap/tools-opportunity";
 */
import "@ui5/webcomponents-icons/dist/tools-opportunity.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "tools-opportunity";

export type ToolsOpportunityProps = Omit<IconProps, "name">;

/** Renders `<Icon name="tools-opportunity" />` after this module is evaluated. */
export function ToolsOpportunity(props: ToolsOpportunityProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
