/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `touch` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/touch";
 * Optional component: import { Touch } from "@reltio/design/icons/sap/touch";
 */
import "@ui5/webcomponents-icons/dist/touch.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "touch";

export type TouchProps = Omit<IconProps, "name">;

/** Renders `<Icon name="touch" />` after this module is evaluated. */
export function Touch(props: TouchProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
