/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `translate` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/translate";
 * Optional component: import { Translate } from "@reltio/design/icons/sap/translate";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/translate.js";

export type TranslateProps = Omit<IconProps, "name">;

/** Renders `<Icon name="translate" />` after this module is evaluated. */
export function Translate(props: TranslateProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`translate`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
