/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `travel-request` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/travel-request";
 * Optional component: import { TravelRequest } from "@reltio/design/icons/sap/travel-request";
 */
import "@ui5/webcomponents-icons/dist/travel-request.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "travel-request";

export type TravelRequestProps = Omit<IconProps, "name">;

/** Renders `<Icon name="travel-request" />` after this module is evaluated. */
export function TravelRequest(props: TravelRequestProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
