/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `travel-expense` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/travel-expense";
 * Optional component: import { TravelExpense } from "@reltio/design/icons/sap/travel-expense";
 */
import "@ui5/webcomponents-icons/dist/travel-expense.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "travel-expense";

export type TravelExpenseProps = Omit<IconProps, "name">;

/** Renders `<Icon name="travel-expense" />` after this module is evaluated. */
export function TravelExpense(props: TravelExpenseProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
