/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `tree` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/tree";
 * Optional component: import { Tree } from "@reltio/design/icons/sap/tree";
 */
import "@ui5/webcomponents-icons/dist/tree.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "tree";

export type TreeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="tree" />` after this module is evaluated. */
export function Tree(props: TreeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
