/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `trend-up` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/trend-up";
 * Optional component: import { TrendUp } from "@reltio/design/icons/sap/trend-up";
 */
import "@ui5/webcomponents-icons/dist/trend-up.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "trend-up";

export type TrendUpProps = Omit<IconProps, "name">;

/** Renders `<Icon name="trend-up" />` after this module is evaluated. */
export function TrendUp(props: TrendUpProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
