/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `trend-down` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/trend-down";
 * Optional component: import { TrendDown } from "@reltio/design/icons/sap/trend-down";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/trend-down.js";

export type TrendDownProps = Omit<IconProps, "name">;

/** Renders `<Icon name="trend-down" />` after this module is evaluated. */
export function TrendDown(props: TrendDownProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`trend-down`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
