/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `tri-state` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/tri-state";
 * Optional component: import { TriState } from "@reltio/design/icons/sap/tri-state";
 */
import "@ui5/webcomponents-icons/dist/tri-state.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "tri-state";

export type TriStateProps = Omit<IconProps, "name">;

/** Renders `<Icon name="tri-state" />` after this module is evaluated. */
export function TriState(props: TriStateProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
