/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `trip-report` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/trip-report";
 * Optional component: import { TripReport } from "@reltio/design/icons/sap/trip-report";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/trip-report.js";

export type TripReportProps = Omit<IconProps, "name">;

/** Renders `<Icon name="trip-report" />` after this module is evaluated. */
export function TripReport(props: TripReportProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`trip-report`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
