/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `two-keys` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/two-keys";
 * Optional component: import { TwoKeys } from "@reltio/design/icons/sap/two-keys";
 */
import "@ui5/webcomponents-icons/dist/two-keys.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "two-keys";

export type TwoKeysProps = Omit<IconProps, "name">;

/** Renders `<Icon name="two-keys" />` after this module is evaluated. */
export function TwoKeys(props: TwoKeysProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
