/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `upload-to-cloud` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/upload-to-cloud";
 * Optional component: import { UploadToCloud } from "@reltio/design/icons/sap/upload-to-cloud";
 */
import "@ui5/webcomponents-icons/dist/upload-to-cloud.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "upload-to-cloud";

export type UploadToCloudProps = Omit<IconProps, "name">;

/** Renders `<Icon name="upload-to-cloud" />` after this module is evaluated. */
export function UploadToCloud(props: UploadToCloudProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
