/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `validate` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/validate";
 * Optional component: import { Validate } from "@reltio/design/icons/sap/validate";
 */
import "@ui5/webcomponents-icons/dist/validate.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "validate";

export type ValidateProps = Omit<IconProps, "name">;

/** Renders `<Icon name="validate" />` after this module is evaluated. */
export function Validate(props: ValidateProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
