/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `vds-file` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/vds-file";
 * Optional component: import { VdsFile } from "@reltio/design/icons/sap/vds-file";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/vds-file.js";

export type VdsFileProps = Omit<IconProps, "name">;

/** Renders `<Icon name="vds-file" />` after this module is evaluated. */
export function VdsFile(props: VdsFileProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`vds-file`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
