/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `vertical-stacked-chart` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/vertical-stacked-chart";
 * Optional component: import { VerticalStackedChart } from "@reltio/design/icons/sap/vertical-stacked-chart";
 */
import "@ui5/webcomponents-icons/dist/vertical-stacked-chart.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "vertical-stacked-chart";

export type VerticalStackedChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="vertical-stacked-chart" />` after this module is evaluated. */
export function VerticalStackedChart(props: VerticalStackedChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
