/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `vertical-bullet-chart` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/vertical-bullet-chart";
 * Optional component: import { VerticalBulletChart } from "@reltio/design/icons/sap/vertical-bullet-chart";
 */
import "@ui5/webcomponents-icons/dist/vertical-bullet-chart.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "vertical-bullet-chart";

export type VerticalBulletChartProps = Omit<IconProps, "name">;

/** Renders `<Icon name="vertical-bullet-chart" />` after this module is evaluated. */
export function VerticalBulletChart(props: VerticalBulletChartProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
