/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `vertical-bar-chart-2` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/vertical-bar-chart-2";
 * Optional component: import { VerticalBarChart2 } from "@reltio/design/icons/sap/vertical-bar-chart-2";
 */
import "@ui5/webcomponents-icons/dist/vertical-bar-chart-2.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "vertical-bar-chart-2";

export type VerticalBarChart2Props = Omit<IconProps, "name">;

/** Renders `<Icon name="vertical-bar-chart-2" />` after this module is evaluated. */
export function VerticalBarChart2(props: VerticalBarChart2Props) {
	return <Icon name={ICON_NAME} {...props} />;
}
