/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `waiver` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/waiver";
 * Optional component: import { Waiver } from "@reltio/design/icons/sap/waiver";
 */
import "@ui5/webcomponents-icons/dist/waiver.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "waiver";

export type WaiverProps = Omit<IconProps, "name">;

/** Renders `<Icon name="waiver" />` after this module is evaluated. */
export function Waiver(props: WaiverProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
