/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `waiver` icon and default-exports its name.
 * Icon name (default export): import name from "@reltio/design/icons/sap/waiver";
 * Optional component: import { Waiver } from "@reltio/design/icons/sap/waiver";
 */

import { Icon, type IconProps } from "@reltio/design/components";
import ICON_NAME from "@ui5/webcomponents-icons/dist/waiver.js";

export type WaiverProps = Omit<IconProps, "name">;

/** Renders `<Icon name="waiver" />` after this module is evaluated. */
export function Waiver(props: WaiverProps) {
	return <Icon name={ICON_NAME} {...props} />;
}

/** The icon's registry name (`waiver`). Consuming this default binding pulls
 * in — and keeps — the icon-registration side effect above, so it never gets
 * tree-shaken away when the icon is actually used. */
export default ICON_NAME;
