/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `walk-me` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/walk-me";
 * Optional component: import { WalkMe } from "@reltio/design/icons/sap/walk-me";
 */
import "@ui5/webcomponents-icons/dist/walk-me.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "walk-me";

export type WalkMeProps = Omit<IconProps, "name">;

/** Renders `<Icon name="walk-me" />` after this module is evaluated. */
export function WalkMe(props: WalkMeProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
