/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `wallet` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/wallet";
 * Optional component: import { Wallet } from "@reltio/design/icons/sap/wallet";
 */
import "@ui5/webcomponents-icons/dist/wallet.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "wallet";

export type WalletProps = Omit<IconProps, "name">;

/** Renders `<Icon name="wallet" />` after this module is evaluated. */
export function Wallet(props: WalletProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
