/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `washing-machine` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/washing-machine";
 * Optional component: import { WashingMachine } from "@reltio/design/icons/sap/washing-machine";
 */
import "@ui5/webcomponents-icons/dist/washing-machine.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "washing-machine";

export type WashingMachineProps = Omit<IconProps, "name">;

/** Renders `<Icon name="washing-machine" />` after this module is evaluated. */
export function WashingMachine(props: WashingMachineProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
