/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `weather-proofing` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/weather-proofing";
 * Optional component: import { WeatherProofing } from "@reltio/design/icons/sap/weather-proofing";
 */
import "@ui5/webcomponents-icons/dist/weather-proofing.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "weather-proofing";

export type WeatherProofingProps = Omit<IconProps, "name">;

/** Renders `<Icon name="weather-proofing" />` after this module is evaluated. */
export function WeatherProofing(props: WeatherProofingProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
