/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `world` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/world";
 * Optional component: import { World } from "@reltio/design/icons/sap/world";
 */
import "@ui5/webcomponents-icons/dist/world.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "world";

export type WorldProps = Omit<IconProps, "name">;

/** Renders `<Icon name="world" />` after this module is evaluated. */
export function World(props: WorldProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
