/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `wrench` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/wrench";
 * Optional component: import { Wrench } from "@reltio/design/icons/sap/wrench";
 */
import "@ui5/webcomponents-icons/dist/wrench.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "wrench";

export type WrenchProps = Omit<IconProps, "name">;

/** Renders `<Icon name="wrench" />` after this module is evaluated. */
export function Wrench(props: WrenchProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
