/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `write-new-document` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/write-new-document";
 * Optional component: import { WriteNewDocument } from "@reltio/design/icons/sap/write-new-document";
 */
import "@ui5/webcomponents-icons/dist/write-new-document.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "write-new-document";

export type WriteNewDocumentProps = Omit<IconProps, "name">;

/** Renders `<Icon name="write-new-document" />` after this module is evaluated. */
export function WriteNewDocument(props: WriteNewDocumentProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
