/**
 * Auto-generated by scripts/build-sap-icons.mjs — do not edit manually.
 * Run: npm run build-sap-icons
 * Source: @ui5/webcomponents-icons/dist/*.js
 * Registers the SAP Fiori `write-new` icon. Tree-shakable single import:
 * import "@reltio/design/icons/sap/write-new";
 * Optional component: import { WriteNew } from "@reltio/design/icons/sap/write-new";
 */
import "@ui5/webcomponents-icons/dist/write-new.js";
import { Icon, type IconProps } from "@reltio/design/components";

const ICON_NAME = "write-new";

export type WriteNewProps = Omit<IconProps, "name">;

/** Renders `<Icon name="write-new" />` after this module is evaluated. */
export function WriteNew(props: WriteNewProps) {
	return <Icon name={ICON_NAME} {...props} />;
}
