#!/usr/bin/env node
/**
 * Reltio Design Platform — design-token CSS generator.
 *
 * Reads SAP Horizon design tokens from the repo-local token files
 * (`utils/sap_horizon.tokens.json`, `utils/sap_horizon_dark.tokens.json`)
 * and emits `public/variables.css` (deduplicated: :root + [data-theme] overrides).
 *
 * The token files mirror SAP Horizon's key surface 1:1 (every `--sap*` key from
 * the upstream `sap_horizon` / `sap_horizon_dark` themes is present, in the same
 * order); only the values of selected tokens are customised for Reltio. No
 * filtering, no value transformation — every key becomes `--<key>: <value>;`.
 *
 * Fonts (`public/fonts.css` + the vendored `public/fonts/*.woff2`) are generated
 * separately — see `scripts/build-fonts.mjs` (`npm run build-fonts`).
 *
 * To customise tokens: edit the `utils/*.tokens.json` files, then re-run this
 * script and commit the regenerated `public/variables.css`.
 */

import { readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

// ── Paths ────────────────────────────────────────────────────────────────

const ROOT = resolve(import.meta.dirname, "..");
const PUBLIC_DIR = join(ROOT, "public");

const LIGHT_JSON = join(ROOT, "utils/sap_horizon.tokens.json");
const DARK_JSON = join(ROOT, "utils/sap_horizon_dark.tokens.json");

const LIGHT_REL = "utils/sap_horizon.tokens.json";
const DARK_REL = "utils/sap_horizon_dark.tokens.json";

// ── Utilities ────────────────────────────────────────────────────────────

function autoGeneratedHeader(sources) {
	return [
		"/**",
		" * Auto-generated by scripts/build-tokens.mjs — do not edit manually.",
		" * Run: npm run build-tokens",
		` * Source: ${sources.join(", ")}`,
		" */",
		"",
	].join("\n");
}

async function readTokensJson(absPath, relLabel) {
	try {
		return JSON.parse(await readFile(absPath, "utf8"));
	} catch (err) {
		if (err && err.code === "ENOENT") {
			throw new Error(
				`Cannot read ${relLabel} — file not found at ${absPath}.`,
			);
		}
		throw err;
	}
}

// ── CSS generator ────────────────────────────────────────────────────────

function generateVariablesCss(lightTokens, darkTokens) {
	const allKeys = Object.keys(lightTokens);

	// All tokens on :root with light values as default
	const rootVars = allKeys.map((key) => `\t--${key}: ${lightTokens[key]};`);

	// Only tokens that differ between light and dark
	const diffKeys = allKeys.filter(
		(key) => lightTokens[key] !== darkTokens[key],
	);
	const lightDiffVars = diffKeys.map(
		(key) => `\t--${key}: ${lightTokens[key]};`,
	);
	const darkDiffVars = diffKeys.map((key) => `\t--${key}: ${darkTokens[key]};`);

	const sections = [
		`:root {\n${rootVars.join("\n")}\n}`,
		`[data-theme="horizon-light"] {\n${lightDiffVars.join("\n")}\n}`,
		`[data-theme="horizon-dark"] {\n${darkDiffVars.join("\n")}\n}`,
	];

	return `${autoGeneratedHeader([LIGHT_REL, DARK_REL])}\n${sections.join("\n\n")}\n`;
}

// ── Main ─────────────────────────────────────────────────────────────────

async function main() {
	const lightTokens = (await readTokensJson(LIGHT_JSON, LIGHT_REL)).root;
	const darkTokens = (await readTokensJson(DARK_JSON, DARK_REL)).root;

	const variablesCss = generateVariablesCss(lightTokens, darkTokens);

	await writeFile(join(PUBLIC_DIR, "variables.css"), variablesCss);

	const totalCount = Object.keys(lightTokens).length;
	const diffCount = Object.keys(lightTokens).filter(
		(key) => lightTokens[key] !== darkTokens[key],
	).length;

	console.log(
		`Generated:\n  public/variables.css (${totalCount} tokens on :root, ${diffCount} theme-specific overrides)`,
	);
}

main().catch((err) => {
	console.error(err.message ?? err);
	process.exit(1);
});
