#!/usr/bin/env node
/**
 * Reltio Design Platform — token & font generator.
 *
 * Reads SAP Horizon assets directly from the `@sap-theming/theming-base-content`
 * npm package (resolved via its exported `resourcePath` helper) and emits:
 *   - public/variables.css   (deduplicated: :root + [data-theme] overrides)
 *   - public/fonts.css       (20 @font-face rules)
 *   - public/fonts/*.woff2   (20 font binaries copied from the package)
 *
 * No filtering, no value transformation. Every key from the SAP JSON becomes a
 * CSS custom property `--<key>: <value>;`.
 *
 * Sync upstream: `npm update @sap-theming/theming-base-content` (or bump the
 * version in package.json and run `npm install`), then re-run this script and
 * commit the regenerated artefacts together with the lockfile bump.
 */

import { copyFile, mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { resourcePath } from "@sap-theming/theming-base-content";

// ── Paths ────────────────────────────────────────────────────────────────

const ROOT = resolve(import.meta.dirname, "..");
const PUBLIC_DIR = join(ROOT, "public");
const PUBLIC_FONTS_DIR = join(PUBLIC_DIR, "fonts");

const PKG_NAME = "@sap-theming/theming-base-content";
const PKG_LIGHT_JSON = join(
	resourcePath,
	"Base/baseLib/sap_horizon/variables.json",
);
const PKG_DARK_JSON = join(
	resourcePath,
	"Base/baseLib/sap_horizon_dark/variables.json",
);
const PKG_FONTS_DIR = join(resourcePath, "Base/baseLib/baseTheme/fonts");

const PKG_LIGHT_REL = `${PKG_NAME}/content/Base/baseLib/sap_horizon/variables.json`;
const PKG_DARK_REL = `${PKG_NAME}/content/Base/baseLib/sap_horizon_dark/variables.json`;
const PKG_FONTS_REL = `${PKG_NAME}/content/Base/baseLib/baseTheme/fonts`;

// ── Font configuration ───────────────────────────────────────────────────

const FONT_CDN_BASE = "https://reltio.design/fonts";

// [font-family, font-weight, font-style, file basename]
// Two @font-face rules per row (Latin subset + extended -full subset) → 20 rules.
const FONT_FACES = [
	["72", 300, "normal", "72-Light"],
	["72", 400, "normal", "72-Regular"],
	["72", 400, "italic", "72-Italic"],
	["72", 600, "normal", "72-Semibold"],
	["72-SemiboldDuplex", 400, "normal", "72-SemiboldDuplex"],
	["72", 700, "normal", "72-Bold"],
	["72", 700, "italic", "72-BoldItalic"],
	["72", 900, "normal", "72-Black"],
	["72 Mono", 400, "normal", "72Mono-Regular"],
	["72 Mono", 700, "normal", "72Mono-Bold"],
];

const LATIN_RANGE =
	"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+20AC, U+2122, U+2212, U+2215, U+FEFF, U+FFFD";
const FULL_RANGE = "U+0100-FFFF";

// ── Utilities ────────────────────────────────────────────────────────────

function autoGeneratedHeader(sources) {
	return [
		"/**",
		" * Auto-generated by scripts/build-tokens.mjs — do not edit manually.",
		" * Run: npm run build-tokens",
		` * Source: ${sources.join(", ")}`,
		" */",
		"",
	].join("\n");
}

async function readPackageJson(absPath, relLabel) {
	try {
		return JSON.parse(await readFile(absPath, "utf8"));
	} catch (err) {
		if (err && (err.code === "ENOENT" || err.code === "MODULE_NOT_FOUND")) {
			throw new Error(
				`Cannot read ${relLabel} — is ${PKG_NAME} installed? Run \`npm install\` and retry.`,
			);
		}
		throw err;
	}
}

// ── CSS generators ───────────────────────────────────────────────────────

function generateVariablesCss(lightTokens, darkTokens) {
	const allKeys = Object.keys(lightTokens);

	// All tokens on :root with light values as default
	const rootVars = allKeys.map((key) => `\t--${key}: ${lightTokens[key]};`);

	// Only tokens that differ between light and dark
	const diffKeys = allKeys.filter(
		(key) => lightTokens[key] !== darkTokens[key],
	);
	const lightDiffVars = diffKeys.map(
		(key) => `\t--${key}: ${lightTokens[key]};`,
	);
	const darkDiffVars = diffKeys.map((key) => `\t--${key}: ${darkTokens[key]};`);

	const sections = [
		`:root {\n${rootVars.join("\n")}\n}`,
		`[data-theme="horizon-light"] {\n${lightDiffVars.join("\n")}\n}`,
		`[data-theme="horizon-dark"] {\n${darkDiffVars.join("\n")}\n}`,
	];

	return `${autoGeneratedHeader([PKG_LIGHT_REL, PKG_DARK_REL])}\n${sections.join("\n\n")}\n`;
}

function generateFontsCss() {
	const subsets = [
		{ suffix: "", range: LATIN_RANGE },
		{ suffix: "-full", range: FULL_RANGE },
	];

	const rules = [];
	for (const [family, weight, style, basename] of FONT_FACES) {
		for (const { suffix, range } of subsets) {
			const file = `${basename}${suffix}.woff2`;
			rules.push(
				[
					"@font-face {",
					`\tfont-family: "${family}";`,
					`\tfont-style: ${style};`,
					`\tfont-weight: ${weight};`,
					"\tfont-display: swap;",
					`\tsrc: url("${FONT_CDN_BASE}/${file}") format("woff2");`,
					`\tunicode-range: ${range};`,
					"}",
				].join("\n"),
			);
		}
	}

	return `${autoGeneratedHeader(["FONT_FACES table in scripts/build-tokens.mjs"])}\n${rules.join("\n\n")}\n`;
}

// ── Font copy ────────────────────────────────────────────────────────────

function expectedFontFiles() {
	const files = [];
	for (const [, , , basename] of FONT_FACES) {
		for (const suffix of ["", "-full"]) {
			files.push(`${basename}${suffix}.woff2`);
		}
	}
	return files;
}

async function copyFonts() {
	const expected = expectedFontFiles();

	for (const file of expected) {
		const src = join(PKG_FONTS_DIR, file);
		try {
			await stat(src);
		} catch (err) {
			if (err && err.code === "ENOENT") {
				throw new Error(
					`Expected font file ${file} not found in ${PKG_FONTS_REL}. ` +
						`Either ${PKG_NAME} is uninstalled (run \`npm install\`) or the package no longer ships this asset.`,
				);
			}
			throw err;
		}
	}

	await mkdir(PUBLIC_FONTS_DIR, { recursive: true });
	for (const file of expected) {
		await copyFile(join(PKG_FONTS_DIR, file), join(PUBLIC_FONTS_DIR, file));
	}

	return expected.length;
}

// ── Main ─────────────────────────────────────────────────────────────────

async function main() {
	const lightTokens = (await readPackageJson(PKG_LIGHT_JSON, PKG_LIGHT_REL))
		.root;
	const darkTokens = (await readPackageJson(PKG_DARK_JSON, PKG_DARK_REL)).root;

	const variablesCss = generateVariablesCss(lightTokens, darkTokens);
	const fontsCss = generateFontsCss();

	await Promise.all([
		writeFile(join(PUBLIC_DIR, "variables.css"), variablesCss),
		writeFile(join(PUBLIC_DIR, "fonts.css"), fontsCss),
	]);

	const fontsCopied = await copyFonts();

	const totalCount = Object.keys(lightTokens).length;
	const diffCount = Object.keys(lightTokens).filter(
		(key) => lightTokens[key] !== darkTokens[key],
	).length;
	const faceCount = (fontsCss.match(/@font-face/g) || []).length;

	console.log(
		`Generated:\n  public/variables.css (${totalCount} tokens on :root, ${diffCount} theme-specific overrides)\n  public/fonts.css (${faceCount} @font-face rules)\n  public/fonts/ (${fontsCopied} .woff2 binaries copied from ${PKG_NAME})`,
	);
}

main().catch((err) => {
	console.error(err.message ?? err);
	process.exit(1);
});
