#!/usr/bin/env node
/**
 * Reltio Design Platform — token generator.
 *
 * Reads the verbatim SAP Horizon source files committed in tokens/ and emits:
 *   - public/variables.css   (deduplicated: :root + [data-theme] overrides)
 *   - public/fonts.css       (20 @font-face rules)
 *
 * No filtering, no value transformation. Every key from the SAP JSON becomes a
 * CSS custom property `--<key>: <value>;`.
 *
 * Sync upstream: see tokens/README.md.
 */

import { readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

// ── Paths ────────────────────────────────────────────────────────────────

const ROOT = resolve(import.meta.dirname, "..");
const TOKENS_DIR = join(ROOT, "tokens");
const PUBLIC_DIR = join(ROOT, "public");

// ── Font configuration ───────────────────────────────────────────────────

const FONT_CDN_BASE = "https://reltio.design/fonts";

// [font-family, font-weight, font-style, file basename]
// Two @font-face rules per row (Latin subset + extended -full subset) → 20 rules.
const FONT_FACES = [
	["72", 300, "normal", "72-Light"],
	["72", 400, "normal", "72-Regular"],
	["72", 400, "italic", "72-Italic"],
	["72", 600, "normal", "72-Semibold"],
	["72-SemiboldDuplex", 400, "normal", "72-SemiboldDuplex"],
	["72", 700, "normal", "72-Bold"],
	["72", 700, "italic", "72-BoldItalic"],
	["72", 900, "normal", "72-Black"],
	["72 Mono", 400, "normal", "72Mono-Regular"],
	["72 Mono", 700, "normal", "72Mono-Bold"],
];

const LATIN_RANGE =
	"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+20AC, U+2122, U+2212, U+2215, U+FEFF, U+FFFD";
const FULL_RANGE = "U+0100-FFFF";

// ── Utilities ────────────────────────────────────────────────────────────

function autoGeneratedHeader(sources) {
	return [
		"/**",
		" * Auto-generated by scripts/build-tokens.mjs — do not edit manually.",
		" * Run: npm run build-tokens",
		` * Source: ${sources.join(", ")}`,
		" */",
		"",
	].join("\n");
}

// ── CSS generators ───────────────────────────────────────────────────────

function generateVariablesCss(lightTokens, darkTokens) {
	const allKeys = Object.keys(lightTokens);

	// All tokens on :root with light values as default
	const rootVars = allKeys.map((key) => `\t--${key}: ${lightTokens[key]};`);

	// Only tokens that differ between light and dark
	const diffKeys = allKeys.filter(
		(key) => lightTokens[key] !== darkTokens[key],
	);
	const lightDiffVars = diffKeys.map(
		(key) => `\t--${key}: ${lightTokens[key]};`,
	);
	const darkDiffVars = diffKeys.map((key) => `\t--${key}: ${darkTokens[key]};`);

	const sections = [
		`:root {\n${rootVars.join("\n")}\n}`,
		`[data-theme="horizon-light"] {\n${lightDiffVars.join("\n")}\n}`,
		`[data-theme="horizon-dark"] {\n${darkDiffVars.join("\n")}\n}`,
	];

	return `${autoGeneratedHeader(["tokens/sap_horizon.tokens.json", "tokens/sap_horizon_dark.tokens.json"])}\n${sections.join("\n\n")}\n`;
}

function generateFontsCss() {
	const subsets = [
		{ suffix: "", range: LATIN_RANGE },
		{ suffix: "-full", range: FULL_RANGE },
	];

	const rules = [];
	for (const [family, weight, style, basename] of FONT_FACES) {
		for (const { suffix, range } of subsets) {
			const file = `${basename}${suffix}.woff2`;
			rules.push(
				[
					"@font-face {",
					`\tfont-family: "${family}";`,
					`\tfont-style: ${style};`,
					`\tfont-weight: ${weight};`,
					"\tfont-display: swap;",
					`\tsrc: url("${FONT_CDN_BASE}/${file}") format("woff2");`,
					`\tunicode-range: ${range};`,
					"}",
				].join("\n"),
			);
		}
	}

	return `${autoGeneratedHeader(["FONT_FACES table in scripts/build-tokens.mjs"])}\n${rules.join("\n\n")}\n`;
}

// ── Main ─────────────────────────────────────────────────────────────────

async function main() {
	const lightTokens = JSON.parse(
		await readFile(join(TOKENS_DIR, "sap_horizon.tokens.json"), "utf8"),
	).root;
	const darkTokens = JSON.parse(
		await readFile(join(TOKENS_DIR, "sap_horizon_dark.tokens.json"), "utf8"),
	).root;

	const variablesCss = generateVariablesCss(lightTokens, darkTokens);
	const fontsCss = generateFontsCss();

	await Promise.all([
		writeFile(join(PUBLIC_DIR, "variables.css"), variablesCss),
		writeFile(join(PUBLIC_DIR, "fonts.css"), fontsCss),
	]);

	const totalCount = Object.keys(lightTokens).length;
	const diffCount = Object.keys(lightTokens).filter(
		(key) => lightTokens[key] !== darkTokens[key],
	).length;
	const faceCount = (fontsCss.match(/@font-face/g) || []).length;

	console.log(
		`Generated:\n  public/variables.css (${totalCount} tokens on :root, ${diffCount} theme-specific overrides)\n  public/fonts.css (${faceCount} @font-face rules)`,
	);
}

main().catch(console.error);
