#!/usr/bin/env node
/**
 * Reltio Design Platform — font stylesheet generator.
 *
 * Emits `public/fonts.css` — 20 `@font-face` rules (10 SAP 72 faces × 2 subsets:
 * a Latin subset + an extended `-full` subset) whose `src` points at the CDN at
 * `https://reltio.design/fonts/*.woff2`.
 *
 * The SAP 72 font binaries (`public/fonts/*.woff2`) are vendored directly in the
 * repo. This script verifies they are present but does not copy them.
 *
 * Design tokens (`public/variables.css`) are generated separately — see
 * `scripts/build-tokens.mjs` (`npm run build-tokens`).
 */

import { mkdir, stat, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

// ── Paths ────────────────────────────────────────────────────────────────

const ROOT = resolve(import.meta.dirname, "..");
const PUBLIC_DIR = join(ROOT, "public");
const PUBLIC_FONTS_DIR = join(PUBLIC_DIR, "fonts");

const FONTS_REL = "public/fonts";

// ── Font configuration ───────────────────────────────────────────────────

const FONT_CDN_BASE = "https://reltio.design/fonts";

// [font-family, font-weight, font-style, file basename]
// Two @font-face rules per row (Latin subset + extended -full subset) → 20 rules.
const FONT_FACES = [
	["72", 300, "normal", "72-Light"],
	["72", 400, "normal", "72-Regular"],
	["72", 400, "italic", "72-Italic"],
	["72", 600, "normal", "72-Semibold"],
	["72-SemiboldDuplex", 400, "normal", "72-SemiboldDuplex"],
	["72", 700, "normal", "72-Bold"],
	["72", 700, "italic", "72-BoldItalic"],
	["72", 900, "normal", "72-Black"],
	["72 Mono", 400, "normal", "72Mono-Regular"],
	["72 Mono", 700, "normal", "72Mono-Bold"],
];

const LATIN_RANGE =
	"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+20AC, U+2122, U+2212, U+2215, U+FEFF, U+FFFD";
const FULL_RANGE = "U+0100-FFFF";

// ── Utilities ────────────────────────────────────────────────────────────

function autoGeneratedHeader(sources) {
	return [
		"/**",
		" * Auto-generated by scripts/build-fonts.mjs — do not edit manually.",
		" * Run: npm run build-fonts",
		` * Source: ${sources.join(", ")}`,
		" */",
		"",
	].join("\n");
}

// ── CSS generator ────────────────────────────────────────────────────────

function generateFontsCss() {
	const subsets = [
		{ suffix: "", range: LATIN_RANGE },
		{ suffix: "-full", range: FULL_RANGE },
	];

	const rules = [];
	for (const [family, weight, style, basename] of FONT_FACES) {
		for (const { suffix, range } of subsets) {
			const file = `${basename}${suffix}.woff2`;
			rules.push(
				[
					"@font-face {",
					`\tfont-family: "${family}";`,
					`\tfont-style: ${style};`,
					`\tfont-weight: ${weight};`,
					"\tfont-display: swap;",
					`\tsrc: url("${FONT_CDN_BASE}/${file}") format("woff2");`,
					`\tunicode-range: ${range};`,
					"}",
				].join("\n"),
			);
		}
	}

	return `${autoGeneratedHeader(["FONT_FACES table in scripts/build-fonts.mjs"])}\n${rules.join("\n\n")}\n`;
}

// ── Font verification ──────────────────────────────────────────────────────

function expectedFontFiles() {
	const files = [];
	for (const [, , , basename] of FONT_FACES) {
		for (const suffix of ["", "-full"]) {
			files.push(`${basename}${suffix}.woff2`);
		}
	}
	return files;
}

async function verifyFonts() {
	const expected = expectedFontFiles();

	await mkdir(PUBLIC_FONTS_DIR, { recursive: true });
	for (const file of expected) {
		try {
			await stat(join(PUBLIC_FONTS_DIR, file));
		} catch (err) {
			if (err && err.code === "ENOENT") {
				throw new Error(
					`Expected vendored font file ${file} not found in ${FONTS_REL}. ` +
						"The SAP 72 fonts are vendored in the repo — restore it from version control.",
				);
			}
			throw err;
		}
	}

	return expected.length;
}

// ── Main ─────────────────────────────────────────────────────────────────

async function main() {
	const fontsCss = generateFontsCss();

	await writeFile(join(PUBLIC_DIR, "fonts.css"), fontsCss);

	const fontsVerified = await verifyFonts();
	const faceCount = (fontsCss.match(/@font-face/g) || []).length;

	console.log(
		`Generated:\n  public/fonts.css (${faceCount} @font-face rules)\n  public/fonts/ (${fontsVerified} vendored .woff2 binaries verified)`,
	);
}

main().catch((err) => {
	console.error(err.message ?? err);
	process.exit(1);
});
